### ISSUE TITLE
Download link for wallet on nano website

### ISSUE THREAD

**Issue by BlackBeltBob** [nanocurrency/raiblocks#1021]
Hi,

I always have to use google to find out where the download of the nano wallet can be found. I know I could add a bookmark to this page, but that doesn't solve the problem for new users. 

I would like to suggest that a link is added on nano.org/en/resources for the github to this client.

**Comment by rkeene** [comment]
I think that there is a link from nano.org to the wallets.  Can you confirm and close this ticket ?

**Comment by icarusglider** [comment]
Link to github releases page added to Resources section of nano.org

**Comment by BlackBeltBob** [comment]
Seen the change. Closing the issue. Thanks!
