### ISSUE TITLE
account_representative_set sends back "Empty reply from server" when invalid rep is put into the field

### ISSUE THREAD

**Issue by not-idol** [nanocurrency/raiblocks#1023]
**Description of bug:**
If you send a request to change the rep and put a invalid rep into the representative field u dont get any response back from the node making it difficult to understand what the problem was.
Basically the socket hung up to the node.

no error response in form of json 

**Steps to reproduce the issue:**
1. action account_representive_set
2. put in invalid rep
3. no error respone back, instead: "Empty reply from server"

**Describe the results you received:** no error response

**Describe the results you expected:** an actual error response like: "invalid rep"

- OS information  
- (Linux) Kernel (e.g. `uname -a`): ubuntu 16.04
- Node version 15
- (docker node) docker version: from source

**Comment by SergiySW** [comment]
Will be fixed with merging https://github.com/nanocurrency/raiblocks/pull/970

**Comment by SergiySW** [comment]
Fixed in 15.0
