### ISSUE TITLE
Lost send block (not pending) in beta network

### ISSUE THREAD

**Issue by dandanua** [nanocurrency/raiblocks#1034]
I've been testing beta network with nano wallet desktop. 

I've sent 2 consecutive blocks to unopened account: 

1st send block:
https://beta.nano.org/block/index.php?h=9531D690C2B2D09F3586D6389D8603273A9B5D36885EF1F7CE71B0B52C3DCC52

2nd send block:
https://beta.nano.org/block/index.php?h=C4A99F2B295004CFE597BEA9F31BA62BAE673BF9AB1B2FFFB976B701B5BAA517

When I opened receiving wallet it created an open block with the second block:
https://beta.nano.org/block/index.php?h=915F93591833484B2887E3C6941A6DB07B6915764B5EC08A64716CC9D619FC82

Now, the 1st send block is basically lost. Those funds are not pending in the receiving address.

You can check logs of my node. 

[log_2018-08-07_17-29-01.29.log](https://github.com/nanocurrency/raiblocks/files/2267151/log_2018-08-07_17-29-01.29.log)

**Comment by argakiig** [comment]
There are no funds being sent in the first send block, that is an example of an epoch block, the balance has not changed. The second block referenced is your send to another account, and the third is the open block corresponding to your send. see https://github.com/nanocurrency/raiblocks/pull/955 for more information

**Comment by clemahieu** [comment]
Closing this since creating an epoch block isn’t accidental.

**Comment by dandanua** [comment]
@argakiig 
I'm pretty sure that 1000000 raw > 0 raw, so the funds WERE sent and the sender balance WAS changed.
Both send blocks have the same receiving address, why do you state the opposite?

@clemahieu 
I don't quite understand what is epoch block, but I'm sure this is not the case here.
Maybe there is a bug that caused incorrect recognition of my 1st block as epoch block.

**Comment by argakiig** [comment]
yeah looked at this again,
![image](https://user-images.githubusercontent.com/6511720/43794810-79203bf4-9a4d-11e8-84b9-b9a7b0874180.png)
Epoch was the previous one to what you referenced. So what is your minimum receive set to in the config.json? I will be in discord if you would like to troubleshoot

**Comment by dandanua** [comment]
Yeah, the amount was too small. That 1st block is in the pending state (so I believe I can receive it manually), but the UIs just don't show it and don't automatically receive.
