### ISSUE TITLE
Upgrade to v15 caused the node to get de-peered

### ISSUE THREAD

**Issue by lephleg** [nanocurrency/raiblocks#1077]
**Description of bug:**
After upgrading to v15, the CLI stopped responding and the logs got flooded with `Bootstrap stopped because there are no peers`.

**Steps to reproduce the issue:**
1. Upgrade Docker node to v15 using the `latest` image tag
2. Try to execute some sort of CLI command against the daemon like `/usr/bin/rai_node --wallet_list`
3. Open the logs and observe the repeated `Bootstrap stopped because there are no peers` message

**Describe the results you received:**
No output at all.

**Describe the results you expected:**
CLI command output or an error message about the daemon.

**Additional information you deem important (e.g. issue happens only occasionally):**
RPC calls seems to work so far.

I also tried to delete my old `config.json` file and let the daemon generate a fresh one. Didn't help much.

**Environment**:

- Host OS: Ubuntu 16.04.4 LTS
- Node version: v15:latest
- Docker version: 18.03.0-ce
- Docker Compose version: 1.21.0, build 5920eb0

**logs**

```
[2018-08-19 23:54:33.172577]: Starting bootstrap attempt
[2018-08-19 23:54:33.172741]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172768]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172772]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172775]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172778]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172781]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172784]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172787]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172790]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172793]: Bootstrap stopped because there are no peers
[2018-08-19 23:54:33.172796]: Exiting bulk push client
[2018-08-19 23:54:33.172800]: Exiting bootstrap attempt
```

**Comment by argakiig** [comment]
can you stop the daemon, nuke the config, start it back up, and then provide the config.json that is created as well as what are you using to launch the docker?

**Comment by lephleg** [comment]
I did it nuke the `config.json` and restarted, but didn't help much.

I managed to get it back up by deleting everything in `/root/RaiBlocks/` and fast-syncing from scratch.

The fresh `config.json` is now the following:

```
root@nano-node:/# cat /root/RaiBlocks/config.json
{
    "version": "2",
    "rpc_enable": "true",
    "rpc": {
        "address": "::ffff:0.0.0.0",
        "port": "7076",
        "enable_control": "true",
        "frontier_request_limit": "16384",
        "chain_request_limit": "16384"
    },
    "node": {
        "peering_port": "7075",
        "bootstrap_fraction_numerator": "1",
        "receive_minimum": "1000000000000000000000000",
        "logging": {
            "version": "4",
            "ledger": "false",
            "ledger_duplicate": "false",
            "vote": "false",
            "network": "true",
            "network_message": "false",
            "network_publish": "false",
            "network_packet": "false",
            "network_keepalive": "false",
            "network_node_id_handshake": "false",
            "node_lifetime_tracing": "false",
            "insufficient_work": "true",
            "log_rpc": "true",
            "bulk_pull": "false",
            "work_generation_time": "true",
            "log_to_cerr": "false",
            "max_size": "16777216",
            "rotation_size": "4194304",
            "flush": "false"
        },
        "work_peers": "",
        "preconfigured_peers": [
            "rai.raiblocks.net"
        ],
        "preconfigured_representatives": [
            "xrb_3arg3asgtigae3xckabaaewkx3bzsh7nwz7jkmjos79ihyaxwphhm6qgjps4",
            "xrb_1stofnrxuz3cai7ze75o174bpm7scwj9jn3nxsn8ntzg784jf1gzn1jjdkou",
            "xrb_1q3hqecaw15cjt7thbtxu3pbzr1eihtzzpzxguoc37bj1wc5ffoh7w74gi6p",
            "xrb_3dmtrrws3pocycmbqwawk6xs7446qxa36fcncush4s1pejk16ksbmakis78m",
            "xrb_3hd4ezdgsp15iemx7h81in7xz5tpxi43b6b41zn3qmwiuypankocw3awes5k",
            "xrb_1awsn43we17c1oshdru4azeqjz9wii41dy8npubm4rg11so7dx3jtqgoeahy",
            "xrb_1anrzcuwe64rwxzcco8dkhpyxpi8kd7zsjc1oeimpc3ppca4mrjtwnqposrs",
            "xrb_1hza3f7wiiqa7ig3jczyxj5yo86yegcmqk3criaz838j91sxcckpfhbhhra1"
        ],
        "online_weight_minimum": "60000000000000000000000000000000000000",
        "online_weight_quorum": "50",
        "password_fanout": "1024",
        "io_threads": "4",
        "work_threads": "4",
        "enable_voting": "true",
        "bootstrap_connections": "16",
        "bootstrap_connections_max": "64",
        "callback_address": "",
        "callback_port": "0",
        "callback_target": "",
        "lmdb_max_dbs": "128",
        "generate_hash_votes_at": "1535760000",
        "version": "14"
    },
    "opencl_enable": "false",
    "opencl": {
        "platform": "0",
        "device": "0",
        "threads": "1048576"
    }
}
```

**Comment by argakiig** [comment]
so, it is working now? Had you been running master on the live network before this point?

**Comment by lephleg** [comment]
It seems so, yeah... But I'm not really sure if it's voting now. 

Has the voting log message changed from `Block XXX was confirmed to peers` to `Block XXX was republished to peers`? Cause I can no longer see the former in my logs..

Nope, I've upgraded straight from `v14.2` (the previous `latest`).

**Comment by argakiig** [comment]
republished does not indicate a vote, is your wallet unlocked, you have the correct seed or private key imported?

**Comment by arzarif** [comment]
Just wanted to add that I'm hitting the same issue. 

I restarted the node after removing config.json and it doesn't appear to be peering with other nodes. 

I'm also upgrading directly from the 14.2 release.

**Comment by lephleg** [comment]
@argakiig The wallet has not password and `--wallet_decrypt_unsafe` prints my seed and public address, so I suppose it's correct.

**Comment by lephleg** [comment]
OK I dont know how, but I got voting up again! 

```
[2018-08-20 02:43:44.135225]: Block 969A1204CCE3609687E5CAF3B847392AD42141EEB304F660CE739D696AFFE8D1 was confirmed to peers
```

It happened after I've restarted the node again to turn off the vote logging. Yay! 🎉

**Comment by BitDesert** [comment]
Had the same issue, fresh docker node on master tag wouldn't peer with the preconfigured node. Releases-v15 tag works fine.

**Comment by arzarif** [comment]
Confirming that I was also able to restore the node, but only after resyncing from scratch. 

Based on [MeltingIce's network status page](https://nano.meltingice.net/network), it appears there are several other v15 nodes that fell out of sync as soon as the latest Docker image was updated to point to the v15 image. Not sure if it has anything to do with this, though there are a couple of instances that are only showing 1 peer.

**Comment by lephleg** [comment]
> Not sure if it has anything to do with this, though there are a couple of instances that **are only showing 1 peer.**

I can confirm that my node appeared like this on the network page, when I looked, while I was having the issue described above. So, they are probably in the same state after auto-upgrading.

Now, it seems to catch up normally, but voting happens once in a while and not every minute (as it used to).

**Comment by rkeene** [comment]
We are going to release V15.1 to address this
