### ISSUE TITLE
Get amount from legacy block using lightwallet

### ISSUE THREAD

**Issue by Inkeliz** [nanocurrency/raiblocks#1082]
Since legacy blocks don't include the balance, makes hard to know how much was sent/received. In case of *lightwallet* it becomes painful, since need to check, download and request votes of too much data.

My suggestion:

1. Creates a new mode of `confirm_ack` which inform the amount sent/received and signs the data, the signature must includes the amount too; or
2. Creates a new mode of `bulk_pull` which includes the amount of each block, also the node will signs the data.

This change should't increase the vote requests, because current more votes are needed. If a *lightwallet* wants to know the amount received of one legacy block, they need to download more blocks and request votes of some blocks too. However, with my suggestion, the complexy will be always one, because one vote are needed for each block or just one request will be enough at all.

The lightwallet will check the signature against their pre-configured trusted authorities/representatives. If the signature is correct, the lightwallet will trust in the amount given.

**If anything similar is already available, let's me know.**

**Comment by renesq** [comment]
RPC commands deliver the metadata you need. `"action": "blocks_info"` will show the amount.

**Comment by Inkeliz** [comment]
@renesq, it's using the RPC, not at "protocol level". Most nodes don't have a RPC public enabled. Also, even if some node has the RPC, it's impossible to know if the amount is correct, the node can be biased and lie about the amount. 

The lightwallet in this case don't have any central server to rely on, just common nodes from the network itself.

**Comment by clemahieu** [comment]
Legacy blocks should not be used anymore. We’ve created changes that, when finally enabled, will disable support for old blocks.

We’ve been working with service providers to upgrade over the last few months since state blocks were released. State blocks were introduced to solve the issue you’re describing and no new services should be generating state blocks.

**Comment by Inkeliz** [comment]
@clemahieu, still have two problems:

1. If I'm using legacy block and want to use the state-block, I need to know the amount of my account, which is hard without a full-node.

2. If the account never uses the state-block before. If someone have a account with legacy blocks and now start uses the state-block, this first state-block still painfull for a lightwallet. If this first state-block is a payment to me, I can't compare the balance against the previous block, because the previous is a legacy.

_Even if the state-block is mandatory it not fixes the problem._

**Comment by clemahieu** [comment]
This is why epoch blocks are signed by an epoch block signer instead of the account itself. 1 state block will be able to be injected over accounts that have a head legacy block. This will put a state/epoch block at the head which contains the current account balance.
