### ISSUE TITLE
Support CentOS 7, RHEL 7 in release builds

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/raiblocks#1091]
glibc 2.17

**Comment by rkeene** [comment]
Will a static binary work for V15.2 ?

**Comment by SergiySW** [comment]
I'm not sure if Glibc can be static library?

**Comment by rkeene** [comment]
For the most part it can, there are two issues though NSS (name service switch) and the runtime dynamic linker (libdl).  The name service switch is defined by a few shared objects and so they are linked at runtime without much ABI guarantee.  There are ways to work around this.  We can produce a binary to test.

**Comment by SergiySW** [comment]
Or if thread_local can be somehow replaced

**Comment by rkeene** [comment]
Let's implement this by supplying a yum/dnf repository with RPMs -- there is a ticket related to this that I will find and consolidate.

**Comment by rkeene** [comment]
This is related to #12

**Comment by rkeene** [comment]
I'm going to close this ticket and keep the older ticket open for this, since the older one is more general.
