### ISSUE TITLE
RPC call "pending" returning active blocks

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/raiblocks#1122]
During investigation of Issue #1107 it was discovered that the RPC call "pending" may return active blocks.  As part of pull request #1028 active blocks were removed from "*_pending" RPC calls but may not have been removed from "pending".

Investigate if "pending" does or does not filter out active blocks, then update it to filter out active blocks unless the "include_active" object is specified with a value of true, just like "accounts_pending" and "wallet_pending"

**Comment by PaulBGD** [comment]
If you're looking for a clear example on the live network, I have a few blocks that I sent myself listed as pending even though they're clearly processed: https://www.nanode.co/account/xrb_1ex3t617hfc4g17g4ttoosnwhszydiuibrr1o7d99eed4rrutmkdpcpdjkmo
