### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/raiblocks#1132]
Mailing list for announcements

**Comment by icarusglider** [comment]
Being integrated into new site design

**Comment by nanotroy** [comment]
Telegram/Skype bot to mass communicate to exchanges/services instead of needing individual messages to each

**Comment by brunoerg** [comment]
If it will be integrated into new site design the people could register their main/native language (email + main language), and receive the announcements translated.

**Comment by zhyatt** [comment]
Handling this internally with new website updates.
