### ISSUE TITLE
Fork resolution causes callback of old block - is that correct?

### ISSUE THREAD

**Issue by gokr** [nanocurrency/raiblocks#1139]
On the Canoe server I am seeing lots of "old callbacks" - in other words, callbacks for blocks that are old, like many months old. The pattern is that whenever Canoe manages to make a "bad" call to the "process" RPC (to publish a new block) - for example causing a "Fork" or "Old block" or similar error, the node triggers a callback for the account in question - with one of its older blocks. The reason I know this is because our timestamps we keep in PostgreSQL has a "unique key constraint" so it bugs out whenever I get a callback for a block that I have already gotten a callback for earlier in time.

After looking at node logs I conclude this is due to the fork resolution logic where the node decides to broadcast a "confirmation req" to a bunch of representatives. Now... is the callback supposed to happen in this case?

We are using the binary download of 15.2. We recently upgraded from 14.2, just dropped 15.2 in. The database has been running for quite some time.

gokr@getcanoe:/etc/nginx$ uname -a
Linux getcanoe.io 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Node version: 15.2

**Comment by icarusglider** [comment]
V16.3+ Resolved this with changes made to both block addition to ledger and active confirmation queue adjustments. Old blocks were likewise popping up in the confirmation queue.

**Comment by zhyatt** [comment]
Closed as resolved in 16.3
