### ISSUE TITLE
Feature request: ability to clear Send Idempotency IDs and force send

### ISSUE THREAD

**Issue by jcraigk** [nanocurrency/raiblocks#1162]
https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#send states `You can (and should) specify a unique id for each spend to provide idempotency`.  For development purposes it would be helpful if RPC API could provide:

(1) Ability to clear all of these Idempotency IDs with one command
(2) Ability to provide "force" option to override node behavior of preventing duplicate send request

If it was deemed more secure to make (1) a CLI `rai_node` command, that would also be acceptable.

**Comment by PlasmaPower** [comment]
For (2) you can simply not pass the id parameter in. We may remove that in the future, but we haven't yet.

**Comment by jcraigk** [comment]
@PlasmaPower Yep that's what I'm doing currently.  My suggestion for (2) was getting ahead of that potential requirement in the future (which I personally support).

**Comment by jcraigk** [comment]
@argakiig in production, no.  In fact, these features I'm suggesting shouldn't be used in production at all.  In development, I have a local database table storing transaction IDs.  These are auto-increment, starting at 1 and counting up.  When I flush the database and start over with ID 1, this means if I want to use the send idempotency feature, I need to start with a fresh data.ldb to clear the send IDs stored in its history.  This incurs resource usage (and development slowdowns) to get the data.ldb up to date with current public block before transactions can be performed against the node.  Having to save "virgin data.ldb files" on an ongoing basis locally as its done daily on Google Drive now isn't really feasible given file sizes and time to process blocks.

One way I've circumvented this issue is by using GUIDs instead of standard integer IDs on transaction records in DB, and that works fine, but this got me thinking about development niceties especially if these idempotency IDs will be required in the future.

My naive opinion is that local node state like wallets, accounts, and idempotency IDs should be decoupled from public block storage.  In such a scenario we'd have `public_data.ldb` and `local_data.ldb` or something.  Deleting `local_data.ldb` would wipe local wallets, accounts and send IDs but you'd remain completely up-to-date in `public_data.ldb` with current latest block.  This would result in better app developer experience.  I have no idea if that's possible/desirable from a protocol perspective, however.

**Comment by renesq** [comment]
Regarding separated databases... There has been a wallet_separation branch for months now, but it isn't merged yet, probably due to a lack of upgrade paths. https://github.com/nanocurrency/raiblocks/pull/843
