### ISSUE TITLE
v16 Windows Desktop keeps crashing

### ISSUE THREAD

**Issue by stevang** [nanocurrency/raiblocks#1176]
beginning with v15.2 i had malwarebytes antimalware popups warning for a inbound connection related to nano windows desktop wallet/node

v16 Beta ran just fine without any malwarebytes antimalware popups, blocked inbound connections or crashes.

but since i installed the officially released v16 it keeps crashing after some minutes. Not sure if that is related to the initial malwarebytes antimalware reactions.

https://pastebin.de/497/

http://pastebin.de/499/

i don't know if it is just related to a "bad" or blacklisted node ip, but i guess nano desktop wallet/node  still should not crash.

Regards,
Stephan

**Comment by argakiig** [comment]
if  you whitelist the nano_wallet executable does it still crash?

**Comment by stevang** [comment]
i whitelisted the nanowallet within Malwarebytes Antimalware, but i guess thats another problem. Basicly i think one of the nano nodes is blacklisted for whatever reason.

But the crashes continue anyway. Now i saw a significant RAM usage up to 100% of my systems memory. so it seems i have a problem with nanowallet using each and every system memory. The Beta was running absolutly low on memory. Something has to be different between v16 Beta and v16 Release Version.
Also, one time nanowallet just hung up on the logo while starting up.
i also got all the latest windows updates just to make sure.
i'm running win7 64bit, as you can see in the pastebin 499 

![image](https://user-images.githubusercontent.com/5052540/45475467-cb357880-b73c-11e8-957a-a43929ee510f.png)

Regards,
Stephan

**Comment by argakiig** [comment]
This may be resolved with #1213 which should be in the next release. lets test it then and see what you find?

**Comment by rkeene** [comment]
This should now be resolved in V16.1, which has just been released.  If it has not, please re-open this ticket so we can track it further.  Thanks !

**Comment by stevang** [comment]
sadly, the problem seems unchanged. still, the memory usage is running up agressivly to several GB. My PC becomes unusable as it is busy swapping everything it can to swapfile. i'm using a 5 year old 8GB RAM office PC with win7 64bit.
