### ISSUE TITLE
[v16] [Win] Syncing extremely slowly after a while

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [nanocurrency/raiblocks#1183]
**Description of bug:**
Issue described in more detail in the last two posts from here, from me and @james-five: https://github.com/nanocurrency/raiblocks/issues/1168, starting with "While not crashing anymore,"

**Steps to reproduce the issue:**
1. Start program
2. Be happy that it's syncing fast
3. "Huh, what's happening, now it's so slow!"

**Describe the results you received:**
Sadness

**Describe the results you expected:**
Happiness

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
OS Name	Microsoft Windows 10 Pro
Version	10.0.17134 Build 17134

**logs**
I'm probably stupid, but I can't find logs anymore. Maybe they're only generated when the program crashes.

**Comment by Laurentiu-Andronache** [comment]
Issue not fixed by me turning off Windows Firewall and Defender (I don't have any other antivirus or firewall).

**Comment by Sovxx** [comment]
I have noticed the same thing since v16.
The downloaded blocks count goes from 30000 to 29500 in ~1 hour...
The wallet does not crash though.
I am using ubuntu 64.

**Comment by Sovxx** [comment]
switched back to v15.2
it went from 27000 to 3000 in 5 minutes...

**Comment by Sovxx** [comment]
restarting v16 helps in decreasing the downloaded block counts (a few thousands during the first 10 or 20 minutes, then it slows down a lot)

**Comment by vrozsas** [comment]
Same thing happening here in Ubuntu 18.04 64bits.

**Comment by rkeene** [comment]
This issue should be resolved by Nano V16.1, which is scheduled to be released later today.

**Comment by rkeene** [comment]
We're moving this release back a few days.

**Comment by rkeene** [comment]
This should now be resolved in V16.1, which has just been released. If it has not, please re-open this ticket so we can track it further. Thanks !

**Comment by james-five** [comment]
Here's my experience with v16.1 on a powerful Win10 x64 rig with gigabit connection.

Deleted exisiting db for a fresh bootstrap. After running for 7 hours had reached about 13.28 / 13.45 million blocks. Seemed to have stopped syncing further or at best going extremely slowly. Logs look normal.

Restarted the node and within a few minutes perfectly in sync.

So doesn't seem entirely stable / fixed yet. But better for sure.

**Comment by Laurentiu-Andronache** [comment]
for me, it worked fine
