### ISSUE TITLE
Enhancement: Add own protocol version to RPC version action

### ISSUE THREAD

**Issue by BitDesert** [nanocurrency/raiblocks#1189]
It would be nice if the protocol version would be returned via RPC:

Request:

```
{  
  "action": "version" 
}
```

Response:

```
{
    "rpc_version": "1",
    "store_version": "11",
    "protocol_version": "14",
    "node_vendor": "RaiBlocks 16.0"
}
```

The variable is set here: https://github.com/nanocurrency/raiblocks/blob/c03351b8ba246c6b6a856996178c97d5e8964b9f/rai/secure/common.hpp#L28

I'm lacking C++ knowledge so I can't create a PR but with this change I could add it to the Nano Node Monitor ( https://github.com/NanoTools/nanoNodeMonitor ). The network version does not always match the node version e.g. v16.0RC2 has the protocol version 13, v16.0 release has 14. Thanks!

**Comment by rkeene** [comment]
This work has been done as part of pull request #1194 and will be in V17.0.  I'm closing this ticket based on the future release of V17.0.

Thanks !
