### ISSUE TITLE
Signed Export and Import of Ledger

### ISSUE THREAD

**Issue by severalif** [nanocurrency/raiblocks#1190]
It would be nice to add features for exporting and importing only the ledger (without wallets or seeds/keys). The CLI command `--snapshot` includes wallets, seeds, etc, which makes it cumbersome to backup the ledger. Thus, it would be good to add commands like `--ledger_export` and `--ledger_import`. The `--ledger_import` command would only import the ledger, without touching the wallets or seeds, which would make it very easy for doing a fast sync.

I also think it would be useful to sign the exported ledger using the private key of an account. For example:
```
rai_node --ledger_export <FILE> --account <ACCOUNT>
``` 

You can then import the exported ledger:
```
rai_node --ledger_import <FILE> --account <ACCOUNT>
```
The node would then verify the integrity of the ledger with respect to the given account. I think it would be useful to add this functionality to the node software since it encourages people to import signed ledgers. It would also make sense since the node already deals with private and public keys. Thus, a representative could easily export its ledger signed with its account.

**Comment by renesq** [comment]
It will probably make more sense to implement #843 and therefore simply make those importing and exporting commands obsolete. But you're right, the export could be scripted in a way that it deletes existing accounts. 

As far as i know, the main reason why #843 still hasn't been merged is the lack of an upgrade path. And maybe the new database abstraction interfered too.

**Comment by argakiig** [comment]
Yup this will be obsoleted by #843. It was on hold. It almost sounds like you are describing the function of the node in regards to the verification of an account?

**Comment by rkeene** [comment]
We are actively working on #843 and although this describes a custody mechanism I think for the most part we'd like to avoid passing around ledgers altogether.  Lazy bootstrapping (#995) should also further significantly ameliorate the need for this for almost all uses.

I'm going to close this request due to the on-going work towards resolving it.  Please let me know if you have further questions !
