### ISSUE TITLE
2 feature requests for the RPC call 'representatives_online'

### ISSUE THREAD

**Issue by nano128** [nanocurrency/raiblocks#1192]
**Description of bug:**

**Steps to reproduce the issue:**
Make a representatives_online RPC call

**Describe the results you received:**
    "representatives": {
        "xrb_14nfwekkenidj3nczefx5snpe6do6d49e4f33cpaeqdq59hkc6tc6wxwkem5": "",
        "xrb_1cmtk7x7eeicbe434tqcjzhdiwxkaqdntbfj1tgxmufyidcdjw3wuk5p67d1": "",
        "xrb_1beta4nkzb3g6b1a1qhae89earmz3gk3kfrp3f8hyztm8qyjkeyz9kajfutq": "",
        "xrb_1beta5zm6rq4ghp6c9n99j8fz3am8e44dewae5ea7addsjtfo8umsafmr1r7": ""
    }

**Describe the results you expected:**
1) Include voting weight in the response. Or even better, add an option argument to the call, 'weight' with which the client can specify whether they want that information.
2) Provide an optional argument, 'account(s)' or 'representative(s)' with which the client can query the status of a specific representative(s).

**Comment by BitDesert** [comment]
The weight in that response would be nice because currently we would need another RPC call for every representative if we wanted to calculate the currently online weight.

**Comment by guilhermelawless** [comment]
@rkeene 
Documentation for the "weight" option is missing on the wiki: https://github.com/nanocurrency/nano-node/wiki/RPC-protocol#representatives-online
