### ISSUE TITLE
Conflicting bit positions in message_header

### ISSUE THREAD

**Issue by catenocrypt** [nanocurrency/raiblocks#1196]
The following message header extensions bit positions are defined:
(file rai/node/common.hpp)
class message_header:
  static size_t constexpr ipv4_only_position = 1;
  static size_t constexpr bootstrap_server_position = 2;
class node_id_handshake:
  static size_t constexpr query_flag = 0;
  static size_t constexpr response_flag = 1;

Both ipv4_only and response uses bit 1, which may lead to conflict.
It looks like the ipv4_only bit is in fact not used, nonetheless this is confusing.

**Comment by PlasmaPower** [comment]
Neither ipv4_only nor bootstrap_server are used. We should probably just get rid of the constants.

**Comment by catenocrypt** [comment]
Correct.  The bitfield constants should be moved to class message_header (from class node_id_handshake), so that they are in one place, and conflicts are less likely when new flags are introduced in the future.

**Comment by catenocrypt** [comment]
Solution is available here:

https://github.com/nanocurrency/raiblocks/compare/master...catenocrypt:issue_1196

**Comment by catenocrypt** [comment]
Merged to master (nov 19)

**Comment by cryptocode** [comment]
Fixed by #1199
