### ISSUE TITLE
Rai node very slow sync since v15

### ISSUE THREAD

**Issue by i3bitcoin** [nanocurrency/raiblocks#1204]
The same issue was added to V19 milestone #1102

The Dev team should closer check this issue, cause now it's not possible to keep the wallet well-synced and many users here have the same problem.
Within the last 24 hours my wallet was 10k blocks behind while working all the time.
And now it's a frequent problem to be stuck on a few thousands blocks behind.
Even restarting the wallet don't help much. I've read that you changed the algo of putting/checking blocks in the new versions, it might be somehow connected.
When downgrade to the previous V14.2 version, it's syncing great, but don't see new in-wallet transactions and can't submit transaction via RPC (it's returning TRX ID but do not include in blockchain).

My server:
2 x Xeon E5-2650v2 (16c/32th) - 128GB DDR3 ECC 1866 MHz

Node:
From V15.2 to V16  same issue

Sync Status:
Array ( [count] => 13312890 [unchecked] => 10379 )

Please check it asap.

**Comment by i3bitcoin** [comment]
@rkeene
Yep, now it seems better! Right after the launch, the node caught the latest blocks in 15 minutes, when the V16 was stuck at 15k blocks behind. Great job! I'm going to monitore it for the next few days and will reply if see something strange.

Thanks!

**Comment by rkeene** [comment]
Thank you.  I am marking this issue as resolved based on your feedback.  If the problem does re-occur please let me know by re-opening this issue.
