### ISSUE TITLE
Outbound Usage

### ISSUE THREAD

**Issue by argakiig** [nanocurrency/raiblocks#1214]
While bootstrapping outgoing confirmation requests can drop observed stake weight for the network below the online_minimum slowing block confirmation until that batch is complete and saturating most networks.

**Comment by rkeene** [comment]
I started looking into this for a V16.1 issue.

**Comment by rkeene** [comment]
@argakiig, Can you test this with the changesets from pull requests #1229 and #1230 applied ?

**Comment by rkeene** [comment]
Marking this as fixed until proven otherwise.
