### ISSUE TITLE
[Suggestion] show current representative of current address in the wallet

### ISSUE THREAD

**Issue by RaiBlocksDisciple** [nanocurrency/raiblocks#122]
(Repost). Might be useful as the only way to view current rep is through the website.

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/commit/788da9965f772b52b05cd2368397577dcdf56cb2

**Comment by nylazormalaca** [comment]
Hello

**Comment by SergiySW** [comment]
Can be closed
