### ISSUE TITLE
"Error deserializing config"  for "./rai_node --daemon" on clean build macos

### ISSUE THREAD

**Issue by SaleProperly** [nanocurrency/raiblocks#1220]
I've seen other solved issues which say to delete "config.json", but I have no such file.

When I build I get a few messages and warnings:

4x like:

`/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libcryptopp.a(simple.cpp.o) has no symbols`

1x like:

```
In file included from /Users/user123/git/raiblocks/ed25519-donna/ed25519.c:17:
In file included from /Users/user123/git/raiblocks/ed25519-donna/ed25519-donna.h:12:
/Users/user123/git/raiblocks/ed25519-donna/ed25519-donna-portable.h:23:10: warning: 
      'ALIGN' macro redefined [-Wmacro-redefined]
        #define ALIGN(x) __attribute__((aligned(x)))
                ^
/usr/include/i386/param.h:83:9: note: previous definition is here
#define ALIGN(p)        __DARWIN_ALIGN(p)
        ^
1 warning generated.
```

1x like:

`ld: warning: text-based stub file /System/Library/Frameworks//OpenCL.framework/OpenCL.tbd and library file /System/Library/Frameworks//OpenCL.framework/OpenCL are out of sync. Falling back to library file for linking.`

45x like:

`ld: warning: direct access in function 'boost::log::v2s_mt_posix::core::reset_filter()' from file '/usr/local/lib/libboost_log-mt.a(core.o)' to global weak symbol 'boost::log::v2s_mt_posix::aux::light_function<bool (boost::log::v2s_mt_posix::attribute_value_set const&)>::impl<boost::log::v2s_mt_posix::filter::default_filter>::destroy_impl(void*)' from file '../node/libnode.a(node.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.`

**Comment by argakiig** [comment]
Do you know the commit you built from?

**Comment by SaleProperly** [comment]
I found the issue. As mentioned elsewhere, deleting the config.json resolves the problem. 

My issue was that config.json did not turn up an any search of my computer (and doesn't exist in same folder as executable).

It did, however, exist in ~/Library/Raiblocks

So, if you have a mac and you can't find it, check there.

As to why searching for it doesn't find it? Who knows. But macos still refuses to find it by search despite me having located it and interacted with it...
