### ISSUE TITLE
v16.1 Windows Desktop keeps crashing

### ISSUE THREAD

**Issue by stevang** [nanocurrency/raiblocks#1244]
_Originally posted by @stevang in https://github.com/nanocurrency/raiblocks/issues/1176#issuecomment-425706036_

sadly, the problem seems unchanged. still, the memory usage is running up agressivly to several GB. My PC becomes unusable as it is busy swapping everything it can to swapfile. i'm using a 5 year old 8GB RAM office PC with win7 64bit.

**Comment by argakiig** [comment]
@stevang take a look at 16.2 and let me know if the issue still persists or if we were able to resolve it?

**Comment by argakiig** [comment]
also, are you able to test and see if the issue persists upon moving to another machine or OS?

**Comment by stevang** [comment]
@argakiig sadly this again.. the computer i am running this on runs into excessive ram usage and insane swapdrive activity to compensate the ram usage (4GB+ ram usage for the nanowallet process). First it does use a decent amount of ram and it slowly builds up the something over 100MB. But then, after maybe 5 minutes it quickly goes up and up and up. is there a way to clean out realy everything nano related from my computer? i have the feeling that an uninstall does not remove everything that interferes with the nano desktop wallet. Also the status line is orange always, from the start. 

i now have the desktop wallet installed and started on a completely different computer that never had any nano software on it. the status line started in blue and ram usage is around 200MB after 30min

**Comment by rkeene** [comment]
This issue should be resolved as a part of V17.0's memory usage reduction changes.

**Comment by rkeene** [comment]
Please re-open this issue or create a new issue if this problem persists with V17.0 or later.
