### ISSUE TITLE
Avoid lock pessimisation

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/raiblocks#1284]
Locks on a given mutex shouldn't cover notifications on conditional variables over the same mutex as it leads to pessimization.

Reference: https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all

One example is going from:
```
    std::lock_guard<std::mutex> lock (mutex);
    free.push_back (data_a);
    condition.notify_one ();
```

to 

```
    {
        std::lock_guard<std::mutex> lock (mutex);
        free.push_back (data_a);
    }
    condition.notify_one ();
```

An alternative is to `unlock` instead of scoping.

**Comment by wezrule** [comment]
I agree except for the last remark, as we don't want to be doing manual cleanup. If the data_a copy constructor throws an exception the mutex will never be unlocked, let RAII automatically handle it for you.

**Comment by termoose** [comment]
Added a pull request for this issue #1461. Tests are passing and everything looks normal.
Like mentioned in the pull request, some of the explicit locking would be unnecessary if we used `std::atomic_bool` on those flags instead.

This is something I want to add later unless someone has an issue with atomics in `std`.
