### ISSUE TITLE
Display target block count in wallet header during synchronization

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/raiblocks#129]
As 1 (900000) of 1200000

**Comment by jamescoxon** [comment]
Would this need a api request to raiblockscommunity.net to get the latest block count or is it available internally?

**Comment by SergiySW** [comment]
I hope we should avoid using centralized web resources and other nodes can answer with their block count. At least that's the idea

**Comment by rkeene** [comment]
Ultimately I think the synchronization will become less relevant as the lazy bootstrapping client gets implemented.  I'm going to close this issue but we can revisit it again if this is still desirable.
