### ISSUE TITLE
need mdb_reader_check  to Check for stale readers in lockfile

### ISSUE THREAD

**Issue by huye0728** [nanocurrency/raiblocks#1295]
https://github.com/nanocurrency/raiblocks/blob/e24a39ab5f08d47d079d68946b2232a8ee7a9ea3/rai/node/lmdb.cpp#L740

**Comment by clemahieu** [comment]
Can you expand on what needs to be done here?  Is this checking of another process has the database opened?

**Comment by huye0728** [comment]
Program, aborted when last run, cause transactions not commit. These transactions need to be check and cleared in the next run.

**Comment by rkeene** [comment]
I'm checking with the LMDB guys since the documentation on `mdb_reader_check()` indicates it should be called when the process map is full, and I would expect aborted/interrupted transactions to be automatically freed up on process restart.

**Comment by rkeene** [comment]
Given that we only have a single process at a time working on the database generally I don't think that we need to call `mdb_reader_check()` unless we get a map full error.  If there are no active processes, the lock file is re-initialized on startup.

**Comment by rkeene** [comment]
@huye0728 Can you clarify your concern here ?  Based on what has been posted so far I'm not sure there's anything that needs to be done.

**Comment by huye0728** [comment]
if the lock file is re-initialized on startup, it`s no problem. I read lmdb source code roughly, may miss this point.
