### ISSUE TITLE
Implement PoW work-based prioritization

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/raiblocks#1298]
To prioritize blocks as the network scales up, implement a simple greater-work-processed-sooner mechanism for incoming blocks for voting.

On a representative, as blocks to vote on are ingested, add them to a sorted data structure where their index is their work value.  When dequeuing those items, pull from the highest first.

This is related to issues #196, #506, and #1064.

**Comment by rkeene** [comment]
This work did not get completed in time for V17.0 and I don't want to burden our cleanup efforts in V18.0 with it, so it has been pushed to V19.0.  It may get done sooner and included in V18.0, or a patch release to V17 if it is of acceptable risk/reward.

**Comment by clemahieu** [comment]
My working branch of this is https://github.com/nanocurrency/raiblocks/tree/parameterized_difficulty

**Comment by rkeene** [comment]
We're going to split this work up and this part (simple greater-work means greater-priority) in V17 and then later implement further enhancements:

1. Client resending when it detects it won't get processed quickly enough by the network
2. Rate limiting on server dequeuing

**Comment by rkeene** [comment]
The initial part of this has been merged into V17, pending testing it will be deployed as part of V17
