### ISSUE TITLE
rai_node not exiting with success code in certain situations

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [nanocurrency/raiblocks#1340]
for the latest version 16.2, on Linux

even if "rai_node --daemon" isn't started in the background, if you run "rai_node --wallet_change_seed --wallet ... -key ...", even though the command is successful, it doesn't exit with a success code, you have to ctrl+c yourself

when "rai_node --daemon" is running in the background, many commands don't work, for example "rai_node --wallet_list"

**Comment by renesq** [comment]
I am still on V15.2, but the wallet_list works flawless even if the daemon is running. 

I found wallet-altering CLI commands' behavior odd in general, so I advise using RPC whenever possible.

**Comment by cryptocode** [comment]
wallet_change_seed does exit, but it may take a while due to work caching for the first four deterministic accounts.

I'll make a PR to give some feedback indicating work is being generated when running this command.
