### ISSUE TITLE
After RAIBLOCKS_SECURE_RPC ON getting compile error

### ISSUE THREAD

**Issue by talentdeveloper** [nanocurrency/raiblocks#1383]
**Description of bug:**

I am going to build node with TLS mode but getting compile error.

`cmake  -DRAIBLOCKS_GUI=ON DBOOST_ROOT=../boost1_66_0/[boost]/ -DRAIBLOCKS_SECURE_RPC=ON`

`OpenSSL include dir: /usr/local/include`
`OpenSSL libraries: /usr/local/lib/libssl.so;/usr/local/lib/libcrypto.so`
`OpenSSL lib: /usr/local/lib/libssl.so`
`Crypto lib: /usr/local/lib/libcrypto.so`
`-- Boost version: 1.66.0`
`-- Found the following Boost libraries:`
`--   filesystem`
`--   log`
`--   thread`
`--   program_options`
`--   system`
`--   date_time`
`--   log_setup`
`--   regex`
`--   chrono`
`--   atomic`
`-- Compiler:` 
`-- Flags:  -march=native`
`-- Build type: Release`
`-- The following OPTIONAL packages have been found:`
` * Threads`
`-- The following REQUIRED packages have been found:`

` * OpenSSL (required version >= 1.0)`
` * Boost (required version >= 1.66.0)`

`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /media/dev/7E44D55644D511AF/Working/rai-node`

`make rai_node`

`[100%] Linking CXX executable ../../rai_node`
`../node/libnode.a(rpc.cpp.o): In function `rai::get_rpc(boost::asio::io_context&, rai::node&, rai::rpc_config const&)':`
`rpc.cpp:(.text+0x1b25): undefined reference to` `rai::rpc_secure::rpc_secure(boost::asio::io_context&, rai::node&, rai::rpc_config const&)'`
`../node/libnode.a(rpc.cpp.o): In function` `std::_Sp_counted_ptr<boost::asio::ssl::detail::openssl_init_base::do_init*,` `(__gnu_cxx::_Lock_policy)2>::_M_dispose()':`
`rpc.cpp`: `(.text._ZNSt15_Sp_counted_ptrIPN5boost4asio3ssl6detail17openssl_init_base7do_initELN9__gnu_cxx`12_Lock_policyE2EE10_M_disposeEv[_ZNSt15_Sp_counted_ptrIPN5boost4asio3ssl6detail17openssl_init_base7do_initELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv]+0x10): undefined reference to `CONF_modules_unload'
../node/libnode.a(rpc.cpp.o): In function `boost::asio::error::detail::ssl_category::message[abi:cxx11](int) const':
rpc.cpp:(.text._ZNK5boost4asio5error6detail12ssl_category7messageB5cxx11Ei[_ZNK5boost4asio5error6detail12ssl_category7messageB5cxx11Ei]+0x8): undefined reference to `ERR_reason_error_string'
../node/libnode.a(rpc.cpp.o): In function `boost::asio::ssl::detail::openssl_init_base::instance()':
rpc.cpp:(.text._ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv[_ZN5boost4asio3ssl6detail17openssl_init_base8instanceEv]+0x11c): undefined reference to `CONF_modules_unload'
collect2: error: ld returned 1 exit status
rai/rai_node/CMakeFiles/rai_node.dir/build.make:140: recipe for target 'rai_node' failed
make[3]: *** [rai_node] Error 1
CMakeFiles/Makefile2:994: recipe for target 'rai/rai_node/CMakeFiles/rai_node.dir/all' failed
make[2]: *** [rai/rai_node/CMakeFiles/rai_node.dir/all] Error 2
CMakeFiles/Makefile2:1006: recipe for target 'rai/rai_node/CMakeFiles/rai_node.dir/rule' failed
make[1]: *** [rai/rai_node/CMakeFiles/rai_node.dir/rule] Error 2
Makefile:444: recipe for target 'rai_node' failed
make: *** [rai_node] Error 2`

There was no compile error when I didn't use `RAIBLOCKS_SECURE_RPC` parameter.

Been trying to fix this but failed.

**Comment by clemahieu** [comment]
Looks like you filed this to the wrong project then edited the contents.
