### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by i3bitcoin** [nanocurrency/raiblocks#1387]
Last days I'm experiencing a very high cpu usage of my rai node 16.2.
It uses over 700% of my 8 cores 3.6 GHz.
I faced such values when rai was generating new address or sending transactions, but now it keeps loaded all the time.

Is there a way to fix this?

**Comment by guilhermelawless** [comment]
@i3bitcoin  does it still happen with V16.3 ?

**Comment by i3bitcoin** [comment]
> @i3bitcoin does it still happen with V16.3 ?

Yep, now it's fine and after update missed blocks appeared in my wallet.
Thanks for your help!
