### ISSUE TITLE
[Suggestion] Add ability to clear password

### ISSUE THREAD

**Issue by icarusglider** [nanocurrency/raiblocks#157]
Currently once a data file has a password, the wallet wont accept a blank new password if you wish to clear the password. When creating a bootstrap database from a fully synced and password protected account, it is desired to initialize the wallet with a new seed and clear the password to allow distribution to others. There is no way to set a blank password or clear the password completely.

**Comment by dizda** [comment]
Wallet destroy doesn't do the job? https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#wallet-destroy

**Comment by icarusglider** [comment]
Thinking more along the lines of preserving the data, but voluntarily decrypting the wallet after authenticating.
