### ISSUE TITLE
error: ‘unsigned int* CryptoPP::SecBlock while running make rai_node

### ISSUE THREAD

**Issue by kasaram** [nanocurrency/raiblocks#228]
https://github.com/clemahieu/raiblocks/wiki/Build-rai_node-samples

getting error while building rai-node

Command: make rai_node
response with error message: 
/root/rai_build/cryptopp/secblock.h: In member function ‘virtual void CryptoPP::Salsa20_Policy::OperateKeystream(CryptoPP::KeystreamOperation, CryptoPP::byte*, const CryptoPP::byte*, size_t)’:
/root/rai_build/cryptopp/secblock.h:802: error: ‘unsigned int* CryptoPP::SecBlock<unsigned int, CryptoPP::FixedSizeAllocatorWithCleanup<unsigned int, 16ul, CryptoPP::NullAllocator<unsigned int>, true> >::m_ptr’ is protected

![image](https://user-images.githubusercontent.com/12134388/34048687-e8ebce8c-e1b4-11e7-8ec6-8a6f7af49d18.png)

**Comment by SergiySW** [comment]
Try run cmake with additional option
-DCRYPTOPP_CUSTOM=ON
