### ISSUE TITLE
Feature Request: Utilize all cores during sync

### ISSUE THREAD

**Issue by pRizz** [nanocurrency/raiblocks#230]
The wallet is only utilizing one of my cores at 80-90%. It should utilize all to speed up the syncing. Maybe cap it at 90% of all cores.

**Comment by tdassonville** [comment]
As stated [here](https://steemit.com/raiblocks/@icarusglider/raiblocks-wallet-sync-workaround), the bottleneck seams to be disk I/O to write loads of small chunk of data...
