### ISSUE TITLE
Wallet 8 crashes on open on Mac 

### ISSUE THREAD

**Issue by satb** [nanocurrency/raiblocks#242]
The wallet was syncing and syncing and syncing and then....crash!

Then, won't restart. On every restart it crashes again. Great. Now I have to start over?

Do you log anything somewhere that I can attach?

**Comment by thehen101** [comment]
It is possible that there is not enough disk space left. How much do you have left on your main disk?

**Comment by satb** [comment]
Nope. There is sufficient disk space. All other apps are running just fine.

**Comment by satb** [comment]
![raiblocks_quit_2](https://user-images.githubusercontent.com/2095367/34116937-e30fe7de-e3ce-11e7-86b1-31c7c282235c.png)
![raiblocks_quit](https://user-images.githubusercontent.com/2095367/34116938-e33f2d14-e3ce-11e7-87db-e8a8d966329d.png)

**Comment by thehen101** [comment]
How many GB of disk space do you have left?

Also, try posting the log. On windows logs are located in C:\Users\<username>\AppData\Local\RaiBlocks\log, I don't know where they are on Mac but you could try doing a few searches for 'RaiBlocks' in your Library: https://apple.stackexchange.com/questions/28928/what-is-the-osx-equivalent-to-windows-appdata-folder

**Comment by satb** [comment]
More than 250GB. However, that isn't the problem. I troubleshooted the problem to be the below. I think it is better to add a fix so it doesn't crash without any indication of what might be wrong. This one happened for no apparent reason. The app just crashed when it was synching (actually the window disappeared entirely, then I went in to force quit the application, then this)

`
2017-12-18 08:47:41.178812-0800 rai_wallet[39062:11073390] MessageTracer: load_domain_whitelist_search_tree:73: Search tree file's format version number (0) is not supported
2017-12-18 08:47:41.178852-0800 rai_wallet[39062:11073390] MessageTracer: Falling back to default whitelist
2017-12-18 08:47:41.332764-0800 rai_wallet[39062:11073390] Month 13 is out of bounds
2017-12-18 08:47:41.349595-0800 rai_wallet[39062:11073390] Month 13 is out of bounds
2017-12-18 08:47:41.409477-0800 rai_wallet[39062:11073390] Month 13 is out of bounds
2017-12-18 08:47:43.813226-0800 rai_wallet[39062:11073390] Month 13 is out of bounds
2017-12-18 08:47:43.814193-0800 rai_wallet[39062:11073390] Month 13 is out of bounds
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: bind: Address already in use
<End of Run>
`

**Comment by jamescoxon** [comment]
Right yeah restart your mac and this should go away - there is an issue with 'unbinding' from the ports - we are in the process of hunting this down - its really annoying OS X issue.

**Comment by MikeyMT** [comment]
I'm having the same issue. Have tried a restart as well as a re-install and can't get it to re-open.

**Comment by Kthulu120** [comment]
It's due to a file path issue on MacOS either that or something is on the port RaiBlocks is on @satb try and make sure nothing is running on your ports that Rai is, if not then I'll submit a pull request to try and fix the file tree issue.

**Comment by satb** [comment]
@Kthulu120 - I am sure no other app is took up that port because the wallet was up and running. Its only after the wallet crash that it continues to have some orphaned process still holding up the port. Therefore, restarting the wallet cannot bind to that port again. However, instead of showing the right message that the port is already in use, it crashes.

**Comment by Kthulu120** [comment]
Alright cool I'll be up for a while so I'll look into it and try and have a pull request soon if no one else can figure it out.

**Comment by Yaama** [comment]
I have the same problem!

**Comment by androm3da** [comment]
I'm sorry you folks are having trouble.  I will push for a new release soon -- there's been some recent fixes.  Hopefully that should address a couple of causes of these crashes.

**Comment by deronsizemore** [comment]
Just chiming in to add I'm having the same issue. I can't get the wallet to load at all. Just "quits unexpectedly" upon open.

**Comment by arkxu** [comment]
same problem here.

**Comment by esauvisky** [comment]
Same problem on linux here.

**Comment by djkomong** [comment]
Same issue here! I have version 10 running on mac. Everything was running fine before I updated to version 10.
