### ISSUE TITLE
"RaiBlocks quit unexpectedly." on start, macOS High Sierra

### ISSUE THREAD

**Issue by romanpeters** [nanocurrency/raiblocks#243]
When I try to open the application, the icon bounces a few times before disappearing, followed by a Problem Report containing [this output](https://pastebin.com/LpJJ8LUP).

I'm running macOS High Sierra 10.13.2 (had the same problem on 10.13.1).
I'm using the latest release 9.0.0-Darwin, but had the same problem with the release before that.
I tried redownloading/reinstalling.
I've also found a post on [reddit](https://www.reddit.com/r/RaiBlocks/comments/7ka2t6/mac_wallet_crashing_on_startup/) from a user with the same issue.

**Comment by androm3da** [comment]
This error means that the wallet tried to execute an instruction that the CPU couldn't decode.  It's usually due to using instructions which are too new for your CPU.

I'd wager that the macOS binary was built with options that aren't supported by your computer.  Can you rebuild from source?

**Comment by romanpeters** [comment]
Could very well be, since it's a MacBook Pro from mid-2010. Unfortunately I don't have much experience with building from source, and got stuck somewhere along the way using the build instructions.

Any plans on adding support for older systems? 😅

**Comment by MikeyMT** [comment]
I have a 2015 MBP running Sierra having the same issue.

**Comment by wintermutt** [comment]
Same here with a 2010 MBA running Sierra.

**Comment by androm3da** [comment]
Looks like the `memset()` being called from here https://github.com/clemahieu/raiblocks/blob/master/rai/secure.cpp#L13 is using features not supported by the local CPU.  But that would break everything else, right?

What am I missing?

**Comment by clemahieu** [comment]
I’m guessing vector instruction incompatibility as well. It’s compiled for sse4 and avx instructions and it’s likely memset tried to make use of that.
We’ll have to come up with a plan for compatibility so old machines can run it while new machines can also use new instructions.

**Comment by wintermutt** [comment]
@androm3da Same problem with 9.0 RC3 ([report](https://gist.github.com/wintermutt/9db94e57982e19a5b4d6a81ffecb769d))

**Comment by MikeyMT** [comment]
I have tried uninstalling 8 and installing 9. Same issue.

**Comment by MikeyMT** [comment]
Anyone have any luck getting it to reboot? I've restarted, reinstalled and still getting this error.

**Comment by MikeyMT** [comment]
For what its worth...after deleting all the library files I was able to re-install the wallet (8.0) and I'm re-starting the sync.
