### ISSUE TITLE
Symbol lookup error

### ISSUE THREAD

**Issue by reinaldomendes** [nanocurrency/raiblocks#246]
Hi,

I downloaded Release Candidate 3: file rai-9.0.0-Linux.tar.xz.

When I run the wallet in the bash and click in some options like (import adhock key, unlock, set/change password )  the wallet closes suddenly: 

```bash 
./rai_wallet
./rai_wallet: symbol lookup error: ./rai_wallet: undefined symbol: _ZN7QString18toLocal8Bit_helperEPK5QChari
```

I'm using ubuntu 14.04 LTS kernel 4.4.0-59:
```bash
lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

```

**Comment by clemahieu** [comment]
Hmm, sounds like one of the QT libraries can’t be found when dynamically loading. 

The long term solution for linux runtime dependency issues is going to be compiling on the host, some people have submitted package scripts and I’ll be getting them integrated.

**Comment by androm3da** [comment]
The library is present but is missing dependencies.  

If you bootstrap a newer boost build then you can probably get all of the other dependencies from the raiblocks repo + Trusty.

**Comment by reinaldomendes** [comment]
@androm3da How can I do this?

**Comment by androm3da** [comment]
@reinaldomendes unfortunately this is part of building from source.

https://github.com/clemahieu/raiblocks/wiki/Build-Instructions

**Comment by reinaldomendes** [comment]
@androm3da Thanks.

I solved my problem by compiling with system version of QT.
I am used a modified version of the Dockerfile to do this

```bash
diff --git a/Dockerfile b/Dockerfile
index 7b749b2..7e95b7c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM debian:8.9
+FROM ubuntu:14.04
 MAINTAINER Zjeraar <zjeraar@palmweb.nl>
 
 ENV BOOST_BASENAME=boost_1_63_0 \
@@ -15,6 +15,7 @@ RUN \
   apt-get install -yq cmake && \
   apt-get install -yq g++ && \
   apt-get install -yq curl && \
+  apt-get install -yq qtbase5-dev qt5-default && \
   apt-get clean && \
   rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
   dpkg-reconfigure locales && \
@@ -39,10 +40,13 @@ ADD ./ /tmp/app
 RUN \
   cd app && \
   git submodule update --init --recursive && \
-  cmake -DBOOST_ROOT=${BOOST_ROOT} -G "Unix Makefiles" && \
+  cmake -DBOOST_ROOT=${BOOST_ROOT}  -DQt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5/ -DRAIBLOCKS_GUI=1 -DCRYPTOPP_CUSTOM=on -G "Unix Makefiles" && \
   make rai_node && \
   cp rai_node /usr/local/bin/rai_node &&  \
   ln -s /usr/local/bin/rai_node /usr/bin/rai_node && \
+  make rai_wallet && \
+  cp rai_wallet /usr/local/bin/rai_wallet && \
+  ln -s /usr/local/bin/rai_wallet /usr/bin/rai_wallet && \
   cd .. && \
   rm -rf app && \
   rm -rf ${BOOST_ROOT}
```

After that I'm build the docker
```bash
  docker build -t raiblocks-gui .
```
And run the container interactivelly with command /bin/bash

```bash
 docker run --rm -it -v $(readlink -f ../rai-9.0.0-Linux):/local-rai raiblocks-gui /bin/bash
 #inside docker
 cp /usr/local/bin/rai_wallet /local-rai/rai_wallet_new 
```
