### ISSUE TITLE
Docker node,  wiki Installation on ubuntu 14.04 uses old version of docker.

### ISSUE THREAD

**Issue by reinaldomendes** [nanocurrency/raiblocks#251]
The first step in the tutorial is uninstall old versions:
Older versions of Docker were called docker or docker-engine. If these are installed, uninstall them:
```$ sudo apt-get remove docker docker-engine docker.io```

Please check the docker docs installation for Ubuntu: 
[Get Docker CE for Ubuntu](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-docker-ce-1)

I need to abort testing a node because the version installed by command apt-get install docker.io is not compatible with my existing images.

Thanks.

**Comment by reinaldomendes** [comment]
Addition:

I'm be able to run a node with my current version of docker-ce: Docker version 17.09.1-ce.

Please only update the wiki because when I installed the 'docker.io' it's remove my previously installed docker version and my images was not recognized by the the new installed docker version.

Thanks

**Comment by icarusglider** [comment]
Wiki has been updated to direct users to docker's installation instructions

**Comment by zhyatt** [comment]
Closing as already resolved.
