### ISSUE TITLE
Getting "Illegal instruction" when running rai_node

### ISSUE THREAD

**Issue by lra** [nanocurrency/raiblocks#253]
```
$ uname -a
Linux bitcoin 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

$ ldd rai_node
	linux-vdso.so.1 (0x00007ffd1e35c000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc8f1bb4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc8f19b0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc8f16ac000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc8f130d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc8f1dd1000)

$ ./rai_node
Illegal instruction
```

I tried with both 8.0 and 9.0.

**Comment by SergiySW** [comment]
cat /proc/cpuinfo

**Comment by lra** [comment]
```
$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 77
model name	: Intel(R) Atom(TM) CPU  C2338  @ 1.74GHz
stepping	: 8
microcode	: 0x125
cpu MHz		: 2100.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm arat
bugs		:
bogomips	: 3500.14
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 77
model name	: Intel(R) Atom(TM) CPU  C2338  @ 1.74GHz
stepping	: 8
microcode	: 0x125
cpu MHz		: 2100.000
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm arat
bugs		:
bogomips	: 3500.14
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by androm3da** [comment]
Can you rebuild from source?  If so, use `-DCRYPTOPP_CUSTOM=ON` during cmake.

**Comment by lra** [comment]
I tried a binary I compiled myself (without `-DCRYPTOPP_CUSTOM=ON` first) and it works.

Want me to try with `-DCRYPTOPP_CUSTOM=ON`?

**Comment by androm3da** [comment]
No, you probably don't need to.

**Comment by JFreegman** [comment]
Same issue here with or without `-DCRYPTOPP_CUSTOM=ON`

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 645 Processor
stepping	: 3
microcode	: 0x10000b6
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch fxsave_leak sysret_ss_attrs
bogomips	: 6228.89
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 645 Processor
stepping	: 3
microcode	: 0x10000b6
cpu MHz		: 1900.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch fxsave_leak sysret_ss_attrs
bogomips	: 6228.89
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 2
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 645 Processor
stepping	: 3
microcode	: 0x10000b6
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch fxsave_leak sysret_ss_attrs
bogomips	: 6228.89
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

processor	: 3
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 645 Processor
stepping	: 3
microcode	: 0x10000b6
cpu MHz		: 800.000
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt hw_pstate vmmcall npt lbrv svm_lock nrip_save
bugs		: tlb_mmatch fxsave_leak sysret_ss_attrs
bogomips	: 6228.89
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate

**Comment by JFreegman** [comment]
The illegal instruction is occurring somewhere within the ROUND macro.

```
Program received signal SIGILL, Illegal instruction.
0x00007ffff7a8cc7a in blake2b_compress () from /home/jfreegman/rai_wallet/raiblocks/librai_lib.so
1: x/5i $pc
=> 0x7ffff7a8cc7a <blake2b_compress+170>:	pshufb xmm12,xmm3
   0x7ffff7a8cc80 <blake2b_compress+176>:	movdqa xmm9,xmm3
   0x7ffff7a8cc85 <blake2b_compress+181>:	movdqa xmm3,xmm4
   0x7ffff7a8cc89 <blake2b_compress+185>:	punpckhqdq xmm3,xmm5
   0x7ffff7a8cc8d <blake2b_compress+189>:	movdqa XMMWORD PTR [rsp+0x50],xmm3
(gdb) 
```

**Comment by androm3da** [comment]
Try `master` with `RAIBLOCKS_SIMD_OPTIMIZATIONS=OFF`.

If that doesn't work try commenting out this line from `CMakeLists.txt`

`set_target_properties (blake2 PROPERTIES COMPILE_FLAGS "${PLATFORM_C_FLAGS} ${PLATFORM_COMPILE_FLAGS} -D__SSE2__")
`

**Comment by JFreegman** [comment]
> Try master with RAIBLOCKS_SIMD_OPTIMIZATIONS=OFF.
This did the trick, thanks.

**Comment by androm3da** [comment]
Recommend closing this one -- others who need this fix can try one of the Ubuntu Trusty nightlies like I mentioned over in #124

**Comment by dannyvankooten** [comment]
Same or similar issue here using the prebuilt `rai_node` binary from the 9.0.0 release.

```
Starting program: /home/dvk/rai_node
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
0x0000000000837e14 in CryptoPP::DetectX86Features() ()
```

On Ubuntu 16.04 LTS 64-bits.

**Comment by thiago17** [comment]
I'm facing the same issue by opening rai_wallet.

> ./rai_wallet 
> Illegal instruction (core dumped)

Is there a way to fix it without compiling from source? I'm not used to it.

**Comment by isriam** [comment]
is there a link to a precompiled binary with that switch off?  i don't want to have to compile on my NAS.
