### ISSUE TITLE
Mac Wallet Disconnected

### ISSUE THREAD

**Issue by joel2762** [nanocurrency/raiblocks#262]
I can't get past "Disconnected, Block 1" with the Mac wallet.

I get the Network accept/deny firewall popup box on launch, click accept, and it should be fine from there.

I tried the trick of downloading the library file, which then changes the status to "Disconnected, Block XXXXX" (Can't remember the number, but it shows a big number rather than X's) 

What can I do? Nothing seems to change it from Disconnected.

**Comment by tolinwei** [comment]
Mine has the same error message on top of the Mac client, the log file keeps showing:
```
Starting bootstrap attempt
[2018-01-08 17:46:55.883499]: Bootstrap stopped because there are no peers
[2018-01-08 17:46:55.883541]: Exiting bootstrap attempt
```

I'm using the version 9.0.

**Comment by psimondo** [comment]
same problem. v9.0
basically disconnected forever.

**Comment by indiejoseph** [comment]
+1
