### ISSUE TITLE
Need logo in SVG format

### ISSUE THREAD

**Issue by bartclaeys** [nanocurrency/raiblocks#267]
For a project (overview of coins) I need the Raiblocks logo in SVG format. Can you provide please?

**Comment by SergiySW** [comment]
:)
https://www.dropbox.com/s/5ec3sclb1vy25ax/RaiBlocks-Logo-Final.svg?dl=0
https://www.dropbox.com/s/4y74mtdcp4qs9t6/RaiBlocks-Icon-Final-01.svg?dl=0

**Comment by pocesar** [comment]
@SergiySW what about the new Nano logo? could you provide those as well?

**Comment by bartclaeys** [comment]
You can grab it from their site:

https://nano.org/assets/img/logo.svg

**Comment by anarkrypto** [comment]
2021, where is the nano logo svg ?

**Comment by keerifox** [comment]
> 2021, where is the nano logo svg ?

https://nano.org/resources#media-kits
