### ISSUE TITLE
rai_wallet 9.0 is interfering with my music (foobar2000)

### ISSUE THREAD

**Issue by Kokkomaki** [nanocurrency/raiblocks#268]
The music lags for 0.1-0.5 seconds but then continues normally. This happens from time to time during listening. I closed rai_wallet and then it stopped. Not a big issue, but weird still. It is noticeable though.

**Comment by pocesar** [comment]
same as #227

**Comment by MtKokko** [comment]
Ooo, nice to know I am not alone! Thanks for letting me know.

**Comment by citizen2077** [comment]
Yes I have updated to version 9.0 release and am still getting audio buzzed every 30 seconds - minute during wallet syncing at least. No apps open in tray, just running Windows 10 64bit, audio playing through chrome -> youtube

**Comment by Dekoze** [comment]
Open config.json at:

**Comment by rkeene** [comment]
Duplicate of #227
