### ISSUE TITLE
Contribution to source code

### ISSUE THREAD

**Issue by samacumen** [nanocurrency/raiblocks#276]
This is not an issue that I am raising but didn't know where else to raise a technical question otherwise.
  
I would like to contribute to the source code of RaiBlocks and its development. I would like to know about any design documents and also why is there no 'src' folder in RaiBlocks github code - it kinda makes it hard on where to get started ;)

Any comments are appreciated.

**Comment by androm3da** [comment]
The implementation isn't described by any design docs afaik.  The protocol is described in the whitepaper. 

 The wiki here on GitHub has some docs about how to build it. 

A great place to get started is the issues list IMO. Several of these are clear bug reports that just need some legwork to investigate and fix.

**Comment by samacumen** [comment]
I cannot find a design document. Can you please share that with me?

In spite of being a core software developer, I find it hard to get started with RaiBlocks source. With a project (now worth a Billion $) I would expect some more open-ended design than the one iI currently see. No comments in source code. What is the starting point of Rai? 

PS: I have worked on Bitcoin source code before so I am aware of how it functions and how that it is structured.

Thanks!
