### ISSUE TITLE
Wallet doesn't show any decimal places for account balance

### ISSUE THREAD

**Issue by brockajones** [nanocurrency/raiblocks#278]
I sent 0.1 Mxrb to my wallet and it says my current balance is 0. When I change the unit from Mxrb to Kxrb it shows the correct amount.

**Comment by paulmelis** [comment]
It should also show the current unit for the balance, as showing just the number is asking for confusion. Btw, the Account viewer under Advanced has the same issue.

**Comment by rkeene** [comment]
Duplicate of #249
