### ISSUE TITLE
Canot create wallets by rai_node service

### ISSUE THREAD

**Issue by vudangnt** [nanocurrency/raiblocks#280]
Install rai_node on centos 7
Service rai_node run success but can't create wallet

[vudangnt@rai-node ~]$ sudo service rai_node status
Redirecting to /bin/systemctl status rai_node.service
● rai_node.service - RaiBlocks node service
   Loaded: loaded (/etc/systemd/system/rai_node.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-12-25 06:27:45 UTC; 7s ago
 Main PID: 1162 (rai_node)
   CGroup: /system.slice/rai_node.service
           └─1162 /home/vudangnt/rai_node --daemon
Dec 25 06:27:45 rai-node systemd[1]: Started RaiBlocks node service.
Dec 25 06:27:45 rai-node systemd[1]: Starting RaiBlocks node service...
[vudangnt@rai-node ~]$ curl -g -d '{ "action": "wallet_create" }' 127.0.0.1:7076
curl: (7) Failed connect to 127.0.0.1:7076; Connection refused

Config file:
    "rpc_enable": "true",
    "rpc": {
        "address": "::ffff:127.0.0.1",
        "port": "7076",
        "enable_control": "true",
        "frontier_request_limit": "16384",
        "chain_request_limit": "16384"
    },

**Comment by orrybaram** [comment]
I'm having similar issues connecting via rpc. @vudangnt have you figured it out yet?

**Comment by androm3da** [comment]
Check `sudo netstat -ltnp` look for the addresses and ports that the node is listening on.

Config file shows `"::ffff:127.0.0.1"` and not `127.0.0.1`.

**Comment by vudangnt** [comment]
Just use normal user in config service, do not use root
