### ISSUE TITLE
HElp 

### ISSUE THREAD

**Issue by asiatek2017** [nanocurrency/raiblocks#285]
what we can reset pasaword if forgot password on wallet rai block,
I really forgot because this is a long time, does anyone have a solution to solve this problem thanks
![bitcoin](https://user-images.githubusercontent.com/34849162/34346323-ffaa4ed8-ea28-11e7-913c-92b51dedefcf.png)

**Comment by orhanhenrik** [comment]
Did you back up your seed? If so, you can recreate the wallet with the seed. Otherwise I think you're out of luck.
