### ISSUE TITLE
Build steps incorrect

### ISSUE THREAD

**Issue by DogLikeSparky** [nanocurrency/raiblocks#295]
Due to the new shared object, librai_lib.so your build script needs updating.

Please change 

cp rai_node ../rai_node && cd .. && ./rai_node --diagnostics  
to
cp rai_node ../rai_node && cp librai_lib.so .. && cd .. && ./rai_node --diagnostics

**Comment by androm3da** [comment]
Thanks for the note.  If you don't mind, please go ahead and update the relevant wiki entries with the "edit" button.

**Comment by dan-klasson** [comment]
@DogLikeSparky @androm3da Changed for Ubuntu and CentOS too.
