### ISSUE TITLE
Notification about new version available

### ISSUE THREAD

**Issue by HostFat** [nanocurrency/raiblocks#3]
It can be good that users can find that there is a new version just by looking at the UI.

It shouldn't auto-update.

This is only an example:
![image](https://cloud.githubusercontent.com/assets/644416/14671007/ecc02414-06ef-11e6-9cb4-60ed1dfa425e.png)

**Comment by baundul** [comment]
When Rai will decide. According to some

**Comment by mikerow** [comment]
The future will be only CLI rai_node. This feature can be closed.
