### ISSUE TITLE
(Windows) Locks up PC for 100ms every 5 seconds

### ISSUE THREAD

**Issue by JeroenvdV** [nanocurrency/raiblocks#314]
Whenever the wallet is open, there is this regularly recurring lockup that happens every few seconds during which my cursor doesn't move and spotify skips a bit. This isn't solved by lowering the process' priority in task manager.

**Comment by dannyvankooten** [comment]
This is a possible duplicate of #268 and #227

**Comment by Jaxkr** [comment]
I also have this issue. Audio and cursor problems when using the wallet. It makes my computer nearly unusable, and by extension the wallet is unusuable.

**Comment by rkeene** [comment]
There is ongoing work to improve this situation as part of node stratification #1092 

I'm going to close this issue so we can track the improvement more centrally.
