### ISSUE TITLE
Code fixing for compiling on ARM 

### ISSUE THREAD

**Issue by ghost** [nanocurrency/raiblocks#32]
Code fixing for compiling on ARM

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/pull/54

**Comment by HostFat** [comment]
This can be closed.

**Comment by SergiySW** [comment]
Can be closed: http://butter.yaps.it/~drizzt/rai_node/latest_snapshot/

**Comment by Nearnotes** [comment]
Why in raiblocks , when i put my xrb and start captcha why isnt pocket to my xrb address.. Is there i have do to fix i and using representative xrb address
