### ISSUE TITLE
Desktop wallet bug

### ISSUE THREAD

**Issue by stephenhwang** [nanocurrency/raiblocks#322]
Sent a test amount (10XRB) to the desktop wallet and the wallet is show a pending balance even though the wallet is synced up. Transfer was initiated on 12/27. OS is Mac 10.12.6.

https://raiblocks.net/account/index.php?acc=xrb_1rturss531maoekf6xifdd8mcwyt13fck3uzxt6uga8g1w9k6roxarphgo99

**Comment by stephenhwang** [comment]
I was able to recover the test amount by using the seed to recover the wallet with raiwallet. I sent 1 XRB back to the desktop wallet and tried to send it back but the address is highlighted in red.

**Comment by lzep1968** [comment]
Have the same problem. Sent 10 XRB to my desktop wallet after I had bootstrapped the wallet with the daily blockchain download. The wallet shows it as pending. In the logs, I see that it finds the pending block and broadcasts the confirm req to representatives:

[2017-12-29 13:50:44.446604]: Beginning pending block search
[2017-12-29 13:50:44.455086]: Found a pending block 8103048616AFE89952FC3A02490B6F1EA5E5821C31407C0B227C1CCB9E6AA1D7 from account xrb_31a51k53fdzam7bhrgi4b67py9o7wp33rec1hi7k6z1wsgh8oagqs7bui9p1 with head 1DA1C9E6108EBE58809FCCD5259E61858AB816490DD7127236A1CAA0DDA2E608
[2017-12-29 13:50:44.455086]: Broadcasted confirm req to 7 representatives
[2017-12-29 13:50:44.456064]: Pending block search phase complete

But the block never confirms. I won't use the web wallet as I want to maintain security over my own seeds. Is there any known workaround for this issue?  (Have tried creating another account, switching to it and then switching back, no luck.)

**Comment by androm3da** [comment]
I saw this symptom with a recent transaction (using rai wallet 8.0).  Eventually (~many minutes/hours later) the balance went from pending to in the account proper.

**Comment by webofunni** [comment]
Faced same issue. Using wallet version 9 for Linux. Wallet shows the amount as pending even after completing wallet sync. Tried to switch account, "Search for receivables" in advance option, refreshed wallet. etc atlast switched scale to Mxrb, kxrb, xrb back and forth to fix it.
