### ISSUE TITLE
Can't open my Wallet

### ISSUE THREAD

**Issue by Yaama** [nanocurrency/raiblocks#324]
Hello, I have some problems with my wallet. This error shows all the time up when I try to open the wallet:
![bildschirmfoto 2017-12-29 um 13 01 12](https://user-images.githubusercontent.com/34939201/34436777-2b94d820-ec99-11e7-9e7f-3c13b6a45431.png)

This is the whole error code: https://pastebin.com/c9BXpug6

One problem is also that I already send XRB's to the wallet but I didn't write my seed down. So I don't have it. I just have the files from the installation.
At the first day, The wallet worked fine and then I couldn't get in anymore. 
I already tried to download the wallet again and the same error showed up again. 

What can I do that my funds are not lost?
Thank you for help. 

02.01.2018 Update:I think the data.ldb ist the problem if I delete this data the wallet works and creats a new data.ldb. But this didn't solve the problem. I need to open it with the old data.ldb.  

02.01.2018 Update: https://github.com/clemahieu/raiblocks/issues/366

**Comment by weedpizza** [comment]
I have the same problem. I get error initializing node.

**Comment by rkeene** [comment]
This ticket is overtaken by #366
