### ISSUE TITLE
Can this be considered as poor nesting in the code?

### ISSUE THREAD

**Issue by majieux-mond** [nanocurrency/raiblocks#325]
https://github.com/clemahieu/raiblocks/blob/master/rai/node/common.cpp#L79 

Thanks

**Comment by reteps** [comment]
no that's how you can do it

**Comment by tomstuchinski** [comment]
I'd agree that it's poorly constructed, but reteps is correct in that you "can" do it that way -- it's just pretty ugly. One fix would be to invert the if's and have early return statements inside each. That'd be my preference.

**Comment by bc10000** [comment]
Damn that is ugly as fk, you reminded me of myself when i was studying C++ for the first time.

**Comment by ealtamir** [comment]
Yeah the code is pretty ugly. I wonder if it's done that way for some particular reason, for example, efficiency, or if it's because the coder didn't know better. I remember working on similarly ugly looking code before, but it was very efficient.

**Comment by tomstuchinski** [comment]
I saw a comment from Colin (lead dev) that indicated his preference was to have only 1 return statement per function. His provided reason was that he believed it made the code easier to split up into smaller chunks as it grew (paraphrasing). So I don't think it's a matter of efficiency in this case, but rather a style preference.
