### ISSUE TITLE
rai_node ignores data_path

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/raiblocks#328]
I encountered an issue listing wallet info using rai_node. While it shows "data_path" as an option when passing "--help", the information is always extracted from /Users/name/Library/RaiBlocks.

Judging from the code, the data_path flag is never used in rai_node.

**Comment by pawapps** [comment]
I see the same issue.  On an Ubuntu 16.04, when I run as a service, it uses the data_path I give.  When I run on command line, it seems to ignore.  A workaround is to create a symbolic link at /Users/name/Library/RaiBlocks or ~/RaiBlocks to wherever you care to keep your RaiBlocks directory.

`$ cat /etc/systemd/system/rai_node.service`
`[Unit]
Description=RaiBlocks node service
After=network.target
[Service]
ExecStart=/home/ubuntu/rai_node/rai_node --daemon --data_path="/home/ubuntu/rai_node/RaiBlocks"
Restart=on-failure
User=ubuntu
Group=ubuntu
[Install]
WantedBy=multi-user.target`

**Comment by cryptocode** [comment]
@pawapps https://github.com/clemahieu/raiblocks/pull/342 should fix this.

**Comment by cryptocode** [comment]
Fixed by https://github.com/nanocurrency/raiblocks/pull/586
