### ISSUE TITLE
Exception while running wallet: No such node (wallet)

### ISSUE THREAD

**Issue by dan-klasson** [nanocurrency/raiblocks#329]
I succesfully built the wallet for Linux and it was running fine. Then I decided to also build the node and now my wallet won't start. I get

`Exception while running wallet: No such node (wallet)` and `Gtk-Message: Failed to load module "overlay-scrollbar"`

I've tried to delete everything and start from scratch but still no dice. Any pointers?

**Comment by johntitus** [comment]
I get this error when running the wallet downloaded from the website on Ubuntu 16.04.

**Comment by Blystad** [comment]
I tried starting the rai_node first, then shut it down and started the wallet, but it didn't work. I suspect that it might be differences in the config files in `~/RaiBlocks/` between nodes and wallets. (Though I didn't care to dig into it any further).

I fixed it by deleting `~/RaiBlocks/`.
