### ISSUE TITLE
RPC response problem

### ISSUE THREAD

**Issue by toxonaut** [nanocurrency/raiblocks#336]
Why are there double quotes before the curly braces in some responses (e.g. Retrieve Block)?
E.g.
{  
  "contents" : "{
    "type": "open",
    "account": "xrb_3e3j5tkog48pnny9dmfzj1r16pg8t1e76dz5tmac6iq689wyjfpi00000000",
    "representative": "xrb_3e3j5tkog48pnny9dmfzj1r16pg8t1e76dz5tmac6iq689wyjfpi00000000",
    "source": "FA5B51D063BADDF345EFD7EF0D3C5FB115C85B1EF4CDE89D8B7DF3EAF60A04A4",
    "work": "0000000000000000",
    "signature": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
}"
}

The "{ and the }"

**Comment by pocesar** [comment]
the `contents` is actually a string, and you need to decode from JSON

**Comment by toxonaut** [comment]
Thanks. I thought so too :)
