### ISSUE TITLE
Feature request: fast 1st sync [and nodes blacklist]

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/raiblocks#34]
Fast sync option for first wallet launch (important for slow connections).

[?] Nodes blacklist in config.json to prevent bootstrap poisoning.

**Comment by mikerow** [comment]
A boostrap attacker change its IP to avoid black list. To be deleted IMHO.

**Comment by SergiySW** [comment]
Protect against bootstrap poisoning – iptables or firewall. Perhaps
