### ISSUE TITLE
Ubuntu PPA for wallet and possibly other tools?

### ISSUE THREAD

**Issue by IvanAnishchuk** [nanocurrency/raiblocks#343]
Could really help with adoption, I believe... Something for other distros too (ebuilds for gentoo, AUR for arch, etc.), but I can't help with that as I'm on ubuntu myself.

**Comment by androm3da** [comment]
There is an AUR already, feel free to make a PPA.

**Comment by nikodean1** [comment]
Hi. I can't get rai_wallet (the official Nano wallet/node software for Linux) to run on Gentoo 2018 (AMD64). It says 'Illegal Instruction' when I try to run it.

What can I do to make it work?

**Comment by rkeene** [comment]
Duplicate of #12
