### ISSUE TITLE
unit tests and build instructions / doc

### ISSUE THREAD

**Issue by mpalomas** [nanocurrency/raiblocks#347]
Hello XRB team,

A few comments as I've just tried to build and run the wallet from sources:

When running the qt_test suite, I got several failures (MacOS 10.3.2, master). The thing is:

- I don't know if those failures were known issues (temporary situation) or something really wrong with my local build (I would go for the latter)
- I could not find any information about a Continuous Integration build, or at least expected test results on latest commit by platform
- The build instructions wiki page is good enough to build but does not really mention anything about tests
- It's unclear for instance if some qt_tests are what I would call integration tests and therefore need the full DB file, internet connection...

It would be nice to clarify a bit the doc especially about unit tests, so that people willing to contribute can submit pull requests with confidence.

Thanks for your great work!

**Comment by androm3da** [comment]
Yeah, there are a few failing tests on `master`.  :(

See e.g. a recent build -- https://gitlab.com/raiblocks/raiblocks_core/-/jobs/46339806

In general, the project has few core contributors and a handful of very new contributors.
