### ISSUE TITLE
How to send raiblocks without syncing

### ISSUE THREAD

**Issue by Marc477** [nanocurrency/raiblocks#349]
How can I export the private keys and send raiblocks (that was deposited in a wallet) without syncing that wallet ?

I ask because it is definitely not going to sync after so many hours (still havent sync 5%). I think there are some serious scalability issues with raiblock since it takes days to sync and its still very new (imagine if we have 100x more accounts), that would become impossible. 

Now my raiblocks are stuck in a unsyncable wallet and I would like to know how to send that (just like it is possible to do with ether, bitcoin, litecoin. They can be sent by importing the private key into a light wallet then sending it. But i dont find how to do that for raiblocks. Thanks.

**Comment by pressplay21** [comment]
@marc477 I had the same problem. The workaround is take your local wallet seed and import it to their online wallet. Your balance would be available right away. Yes I agree they need to fix the local wallet sync problems ASAP.

**Comment by Marc477** [comment]
Thanks for your answer.  I am aware of the web wallet but to me its a bit fishy and not trustworthy for these reasons:

1) It is third party and not official
2) It uses both client-server code when most web wallet are client only (for privacy/security reasons)
3) The code of the server is not published and unknown
4) There is no way to download the github code and run it yourself because it requires the server and they don't give the source code of it.
5) There seem to be some confidential data sent to the server according to a thread, the seed or ciphered seed. But this need to be confirmed
6) There is only 1 contributor to the github project. 
7) The 1 contributor has no email or link to public social media profile so no way to know who it truly is.

So I try to avoid using it for now because there are so many reasons it could be a scam.

**Comment by pressplay21** [comment]
Hi yeah you have a valid point. The seed is everything for Raiblocks and I just realized that I shouldnt trust any site with it. 
Raiblocks.net provides 3 links to an online web wallet. The one I’m using, which I think, is their own. The other two are 3rd parties.

As you mentioned, they are fishy and we want our local wallets working.

**Comment by Marc477** [comment]
Yes i don't know why they have a link to the web wallet raiwallet.com on raiblocks.net since it seems like a very unofficial and unverified wallet.
