### ISSUE TITLE
desktop wallet sync time

### ISSUE THREAD

**Issue by tosadvisor** [nanocurrency/raiblocks#351]
is there any way this could be improved?

i realize it's not an inhibitor since it's something that only happens once but it may bottleneck adoption on a macro scale.

**Comment by androm3da** [comment]
There's discussion about improving the synchronization time among the devs and on these GH issues.

I think people might need to adjust their expectations for the time being.  But I expect various proposals to improve it will be high on the list of features.

**Comment by tosadvisor** [comment]
it is also kind of compounding emotionally, if you purchase tokens and then transfer them to your wallet (which isn't synced), and you can't "claim" those tokens off the exchange to your software wallet until it is finished, it becomes sort of a confidence killer for potential new investors.

**Comment by androm3da** [comment]
> it just seems like we could cache somewhere and solve the problem

Without a doubt there are design changes that would speed things up.

>  can't "claim" those tokens off the exchange to your software wallet until it is finished,

Make no mistake: the terminology might be confusing but the coins are yours and yours alone, they'll never revert back to the sender, they're either yours or no one's (if your wallet never pockets them).  The only thing you can't do is spend them until after they're pocketed.

In a very real sense this is hardly different from the bitcoin protocol.  Your wallet has to sync up there, too.  That takes quite a bit of time.

>  so technically it makes sense to procrastinate

There are very few core developers on the wallet.  It's primarily just Colin until very recently.  The exploding interest in the coin is great but in some ways the software is still a little immature.

The web wallet is a great compromise for folks who face the frustrations of maintaining the wallet/node.

**Comment by tosadvisor** [comment]
with the web wallet, i have a few addresses associated with my account and it seems to have selected the last one when i login to it. so i can't use the web wallet to pocket anything. is this normal?

the wallet software is really nostalgic. it reminds me of the super, super early bitcoin clients. that being said maybe we could start something more modern from scratch in something more elegantly cross platform, dom based like electrum?

**Comment by Marc477** [comment]
> In a very real sense this is hardly different from the bitcoin protocol. Your wallet has to sync up there, too. That takes quite a bit of time.

No bitcoin, litecoin, ether, etc.... are totally different. They will complete the transaction without the need for the user to sync. Raiblock puts the transaction "pending" and if you never are able to catch up (let say the speed of block creation becomes faster than the speed at which you can download blocks (which will happen eventually, as the crypto becomes more popular and if not fixed), then you are screwed. You will lose your coins forever. This is a real issue and that must be fixed.

**Comment by Marc477** [comment]
> the wallet software is really nostalgic. it reminds me of the super, super early bitcoin clients. that being said maybe we could start something more modern from scratch in something more elegantly cross platform, dom based like electrum?

I totally agree that Raiblock needs a better core wallet that can sync fast AND a client-side only light wallet like myetherwallet, bitaddress or electrum.

Litecoin-core is a very good example of a wallet that syncs fast and has good ui while still being simple. Use as reference.
