### ISSUE TITLE
Korean translation for white paper

### ISSUE THREAD

**Issue by woniesong92** [nanocurrency/raiblocks#353]
Would you be interested in a PR?

**Comment by Dekoze** [comment]
Absolutely, Korean and Japanese translated whitepapers are needed greatly in my opinion. Both are large markets that likely haven't heard much about the tech.

**Comment by woniesong92** [comment]
I already started it and will take about 14 days from now.

**Comment by AyiSoli** [comment]
Thank you so much for doing this!
