### ISSUE TITLE
"Block Not Found" XRB never arrived

### ISSUE THREAD

**Issue by doonit** [nanocurrency/raiblocks#354]
Hi,
I sent some XRB from MERCATOX to my rai-wallet desktop app last night but the xrp has never arrived. I've sent xrp back and forth quite a lot in the past without issue.

- MERCATOX transaction says the Tx was made, sent, green tic

- I've checked and rechecked the send address and it is correct

- I've checked that rai-wallet is sync'd. It's usually 2 blocks ahead of the block explorer

- I've been through the app and refreshed everything I can find.

I'm not very technical. Please someone help me through this.

Thanks

**Comment by tomstuchinski** [comment]
Please provide the "network hash" (listed in the Tx Info displayed by Mercatox) and the receive address (xrb_...)

**Comment by doonit** [comment]
Hi.

Network hash:
8465C310335A0E7E23FDA674E46B699398CF2A9AE93E0DE0390C6B57CECEC687

Withdrawal address:
xrb_3uzrzgt4nm7suqu7swedy9i7s5d8ojkg57ajyay9bxs78rwup5qpmxue8yf8


Thanks. Much appreciated,

Giles

**Comment by tomstuchinski** [comment]
Here's a summary of the receive address: 
https://www.raiblocks.club/account/xrb_3uzrzgt4nm7suqu7swedy9i7s5d8ojkg57ajyay9bxs78rwup5qpmxue8yf8

It shows that 314.841051 XRB's were deposited. Then, it shows two withdrawals: 314 XRB's and 0.00 XRB's (not sure what the zero value withdrawal is about).

Unfortunately, raiblocks.club is giving a 500 error when I try to look up the network hash you provided. I'm not sure if you copied it incorrectly or if something is wrong with the website. What amount were you trying to send to that address?

**Comment by doonit** [comment]
Hi Tom.

It was only 11 xrb. You're correct regarding previous transactions in the wallet. It's just this one tx that is the empty void. I'll copy the hash and address again to be sure of error correction...

Hash:
8465C310335A0E7E23FDA674E46B699398CF2A9AE93E0DE0390C6B57CECEC687

Withdrawal address:
xrb_3uzrzgt4nm7suqu7swedy9i7s5d8ojkg57ajyay9bxs78rwup5qpmxue8yf8

**Comment by AyiSoli** [comment]
The hash does not exist. You can verify hashes valid using the block viewer in advanced menu (desktop wallet) 
I think its related to mercatox, they may have not broadcast the block

**Comment by doonit** [comment]
I think it has to be that, yes. I hope the xrb still exists!!!

Mercatox just tweeted:


MERCATOX
‏ @MercatoxCom
31m31 minutes ago

Due to high overload of our system and attempts of DDos attacks we forced temporarily suspend website for upgrading our hardware and software. The service will be restored as soon as possible. All coins are SAFE! Sorry for inconvenience.

**Comment by doonit** [comment]
They've not made any comment about the loads and loads of people in my situation. Not good

**Comment by MrGoesToWar** [comment]
Hi can someone help me here, maybe. Same issue for me, pending deposit from a transfer bitgrail to rai wallet 9.0. I have import seed again and no receive fund. my sync is all done status running. when I go in block viewer and put the hash block in they say ''bad block hash''

hash block: EA4CEBBC48D8584B8D0F7425D3BC4E3D097B43C20B0EBEAA551B190565E46D7B

Withdrawal adress : xrb_31ps1pspec8k65mj58qxd4jp8jk8q5ykd5q7nqzstt4tn1y3jct14u4f54ni

When I try to create block and receive with the hash block, it say ''unable to decode source''

What I'm suppose to do now !? thanks a lot!

**Comment by tomstuchinski** [comment]
@MrGoesToWar - There have been some issues with BitGrail today. BitGrail and RaiBocks devs are working on it. Advice for now would be to just hold tight. Look for updates from BitGrail on Twitter: https://twitter.com/BitGrail

**For anyone else looking for support: please do not post your issue here. Instead, use the #support channel in the RaiBlocks Discord: http://chat.raiblocks.net **

**Comment by MrGoesToWar** [comment]
Thanks for fast respond! I'll do! It's appreciate!
