### ISSUE TITLE
Wallet 9 crashes on Windows 7 OS on startup

### ISSUE THREAD

**Issue by phantompharter** [nanocurrency/raiblocks#358]
Application error message:
"The application was unable to start correctly (0xc000007b ). Click OK to close the application."

I also installed Wallet 8 and I received this error message as well.
I have searched for this error online and nothing comes up.

Is there a log I can append?  I had a look through the RAI 9.0.0 directory and could not see a log easily.

Thanks.

**Comment by catenocrypt** [comment]
Note: though this is old and closed, it may be the same as Issue #1402.
