### ISSUE TITLE
Account history for all accounts in wallet via RPC

### ISSUE THREAD

**Issue by AdvancedStyle** [nanocurrency/raiblocks#363]
Is there a way via RPC to get the account history for all accounts?

For example if i want to get a list of history for all accounts in the last X days?

Currently it appears that "account_history" RPC takes only 1 account parameter.

**Comment by kryptocode** [comment]
Call "account_list", then "account_history" for each account?

**Comment by AdvancedStyle** [comment]
I'm assuming this doesn't work well at scale (ie 1,000,000 accounts = 1,000,000 RPC calls)

**Comment by orhanhenrik** [comment]
I guess you could extend the API to have support for fetching multiple histories like with blocks: https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#retrieve-multiple-blocks

**Comment by cryptocode** [comment]
@AdvancedStyle ok, I figured you meant accounts for a given wallet. If *all* accounts, yeah, you'll have to extend the api.
