### ISSUE TITLE
Wallet 8 & 9 crashes on Ubuntu 17.10 with illegal instruction using older hardware (without AES-NI)

### ISSUE THREAD

**Issue by levy** [nanocurrency/raiblocks#365]
I'm trying to run both rai_wallet 8 & 9 on Ubuntu 17.10 using an older CPU without AES-NI. According to gdb the wallet crashes with illegal instruction in DetectX86Features(). Is there any way to get over this problem without recompiling the wallet myself?

**Comment by androm3da** [comment]
No, unfortunately not.  For the next release we'll have unoptimized binaries.

**Comment by lgvz** [comment]
SIGILL on OSX: #316
