### ISSUE TITLE
json wallet restores failing

### ISSUE THREAD

**Issue by Syd** [nanocurrency/raiblocks#366]
json backups of wallets are not importing under rai_wallet 9.0 as well as 8.0.

At present if you already have a data.ldb containing the seed then the import will work, if you load a wallet json in with a data.ldb that does not contain the seed it seems to fail.

I'm able to reproduce this on both mac and windows and with multiple wallet backups.

**Comment by SergiySW** [comment]
It won't restore seed, only existed at backup time private keys

**Comment by JoeyKhd** [comment]
How am I able to restore a wallet that has the json containing addr + seed?

**Comment by AugustoResende** [comment]
@Syd have you managed to solve this in any way manually?

**Comment by AugustoResende** [comment]
Import json backup manually? i need this to recover 600 XRB lost.

**Comment by AugustoResende** [comment]
@clemahieu
