### ISSUE TITLE
Light RPC for light wallets

### ISSUE THREAD

**Issue by ghost** [nanocurrency/raiblocks#39]
Light RPC with very limited access to node to functions like: retrieve a particular account's chain, etc... to allow light nodes to connect.

Example in config.json

"lightrpc_enable": "true"

**Comment by SergiySW** [comment]
**Light RPC proposals**
Future light wallets will retrieve info from light_peers

- **accounts_balances** (bulk request, limit 32) to receive wallet accounts balance
- **available_supply** to retrieve network available supply (info)
- **blocks_info** (bulk request, limit 32) to retireve full blocks info: amount, source, content
- **block_count** to retrieve network block count (info)
- **accounts_frontiers** (bulk request, limit 32) to receive wallet accounts frontiers (head blocks)
- **account_history**, **history** (limit 128) to retrieve account history
- _draft_ **light_peers** to receive list of available light peers
- **accounts_pending**  (bulk request, limit 32) to receive list of pending blocks for wallet accounts
- **process** to process new block to rai network
- **version** to retrieve node version

**Comment by rkeene** [comment]
This should go along with #1092
