### ISSUE TITLE
rai_wallet.exe stays running when closed

### ISSUE THREAD

**Issue by 5k1ttl3** [nanocurrency/raiblocks#395]
Trying to diagnose some sync issues and get my head around how the wallet operates.
In doing so, I've been watching the log file(s) to gain insight into why I may not be syncing (I reach around 10% synchronized after a handful of hours and then it never goes appreciably further.)

I noticed that upon closing the client (rai_wallet.exe), the window closes, the log file reports that the client is trying to shut down ("Node Stopping"), and then the process stays running indefinitely, using .1 - .2% of CPU, and around 2GB of ram.

The log file continues to state that the client is broadcasting a confirm req, or that it has received a fork, or that it has republished a block.

Sysinternals Process Monitor shows the process continuing to do things, primarily "UDP Receive" and "ReadFile"

Not sure what I can do to diagnose this further, but this is just my initial findings.

Platform:
Server 2016 standard (VM)
4x CPU cores, 4GB RAM

**Comment by DestyNova** [comment]
I've noticed the same behaviour running rai_wallet in Ubuntu; I have to ctrl-c it after closing the UI.

**Comment by androm3da** [comment]
185cb324720fcca3dc04774e11e270c60fbacc44 added a join to a destructor.   @Dekoze can you see if you can reproduce this condition?  Something that would cause that join to create a delay or deadlock on shutdown?

**Comment by androm3da** [comment]
Oh, actually -- that only matters if this was on a build from `master`.

@5k1ttl3 what release were you using?

**Comment by 5k1ttl3** [comment]
I'm running 9.0 release

**Comment by androm3da** [comment]
@5k1ttl3 Can you reproduce this condition?  If so can you get a backtrace when it's in this state?

**Comment by 5k1ttl3** [comment]
I can reproduce. But I'm going to ask a stupid question:

What is a backtrace and how can I get you one?

**Comment by DestyNova** [comment]
I'm getting it on master (last commit 2bd3d235688b41832553a0e44301539a01bbce7e).

**Comment by androm3da** [comment]
@5k1ttl3 nevermind it's probably not trivial on windows 

Anyone who sees the same behavior on linux, please attach with gdb (like `gdb -p $(pgrep rai_wallet)`) and get output from `thread apply all bt full`
