### ISSUE TITLE
Support IPv4 only hosts

### ISSUE THREAD

**Issue by androm3da** [nanocurrency/raiblocks#399]
Right now rai_lib uses IPv4-mapped region of IPv6.  Hosts w/o a dual-stack will see failures to bind to addresses (`EADDRNOTAVAIL` etc).

**Comment by androm3da** [comment]
Other mitigations include:
* provide clearer error message describing the problem
* offer a no-rpc command line option that won't consider this error to be fatal
* add appropriate details to the troubleshooting guide

**Comment by bra1n** [comment]
Any updates here? Or workarounds? Would love to run a node on an IPv4-only server...

**Comment by clemahieu** [comment]
I don't think it's worthwhile, aside from removing the ipv6 stack intentionally I don't think there are any operating systems capable of running a node that don't support IPv6.

**Comment by rkeene** [comment]
I'm closing this issue based on the information we have at hand that having an IPv6 stack is sufficient to run the node, even with no IPv6 addresses or routes.  Having an IPv6 stack currently seems like a reasonable requirement for a network daemon in the current environment.  If there are further questions, let me know !
