### ISSUE TITLE
Could not unlock my wallet

### ISSUE THREAD

**Issue by OskarZhang** [nanocurrency/raiblocks#400]
After I initiated a transfer from Bitgrail to my local wallet, I locked my wallet with my password as remembered and immediately could not unlock my wallet. It gives me "invalid password" no matter how many times I tried. The deposit is shown as pending and I could no longer access the fund. Is this a bug on the wallet client? Any tips on how I can get my XRBs back?
  

<img width="343" alt="screen shot 2018-01-05 at 2 13 27 pm" src="https://user-images.githubusercontent.com/3388349/34597598-b27f4e22-f222-11e7-9f84-ae462856af28.png">

**Comment by 5k1ttl3** [comment]
Is it possible you never had a password on your local wallet and that it was locked with a blank password?

Worth a try.

Otherwise, do you have a backup of your wallet seed? (fingers crossed). You can import that into a fresh install of the client.

**Comment by OskarZhang** [comment]
@5k1ttl3 Yeah I did not know what I was doing and clicked around too fast and I don't have a backup... The weird thing is that the first time I clicked `lock`, it gave me an error and the second time went through after I retyped my password, but then I was never able to unlock it with the same password, which makes me wonder if there is something wrong with the desktop wallet client.

**Comment by 5k1ttl3** [comment]
There might be. Try to recall everything you can, and post it here:
When did you first install the wallet?
Has the wallet ever been fully sync'd? (I notice that it's only about half synchronized in the screenshot)


I guess you don't have a backup copy of your raiblocks database (data.ldb) or anything like that (perhaps you copied it to a flash drive, or made a backup copy of it if you used the manual bootstrapping process, or something?) Maybe you have a backup utility that runs on your PC? (trying to think of the easy ways to get you back up and running)

I guess you don't recall what that error message said?

Did you post this to Reddit today? If not, I think I saw someone else mentioning the same thing.

**Comment by yousifa** [comment]
I had the same issue a couple days ago. I was able to backup the data.ldb file, generate a new one and then overwrite it with the backup. This removed the password (I'm unsure how, because it should be locked).

**Comment by OskarZhang** [comment]
@yousifa Did you have your seed backed up? Could you give more details on how you backup the data.Idb file?

**Comment by OskarZhang** [comment]
@5k1ttl3 No luck yet :( But thanks for the help!

**Comment by yousifa** [comment]
I did have my seed backed up, but I did not use it. Move the data.ldb and data.ldb-lock files to another directory or rename it, then open the wallet and generate a new seed. Next, close your wallet and overwrite the new data.ldb and data.ldb-lock files. Not sure how this worked for me as it didn't make any sense.

**Comment by OskarZhang** [comment]
@yousifa Thanks.. I gave it a shot but mine still remains locked :(

**Comment by OskarZhang** [comment]
@yousifa One more thing before I gave up. What OS were you using? Maybe I will try reproduce it on the same OS you were using

**Comment by dannyvankooten** [comment]
Does trying to unlock the wallet with an empty password works? 

> The weird thing is that the first time I clicked lock, it gave me an error and the second time went through after I retyped my password, but then I was never able to unlock it with the same password, which makes me wonder if there is something wrong with the desktop wallet client.

Version 9.0 of the wallet has a weird UX flow when it comes to locking the password. If you fill the password field and click "Lock", the button will flash a red "Error" message because locking you wallet does not actually require a password. This is improved upon in #311, but could it be that you accidentally changed your password then?

**Comment by OskarZhang** [comment]
@dannyvankooten No, empty password did not work for me.

**Comment by yousifa** [comment]
I was using Mac OS. I will try to replicate the method I used tomorrow and update you.

**Comment by OskarZhang** [comment]
If this is indeed happening for other people, this is a real bug that needs to be addressed by the team. Sadly due to the nature of cryptography, we might never be able to unlock our wallet due to this bug.

**Comment by WegFetZ** [comment]
Just lost 10 Nano because of this (yes I know, I should have backed up my seed...).

I installed the wallet on my Windows 10 desktop, created a new Enpass entry and had it generate and store a new password, then copy pasted the password to lock my wallet.

I closed the wallet after a few minutes and after another ~10 minutes, I tried to open it again, but got an "Exception while running socket bind: Only one socket addres...". Clearly, the wallet didn't close properly, so I killed the process with the help of the task manager. Now I can't unlock my wallet with the password that I saved in Enpass.

**Comment by argakiig** [comment]
@WegFetZ I would recommend restarting your computer and trying to load unlock the wallet again.

**Comment by WegFetZ** [comment]
Thanks for the advice! Unfortunately, that didn't help. I'm not 100% sure that I didn't make any mistake while setting the password, so maybe it isn't an issue with the wallet at all. But the fact that the wallet didn't close properly seems suspicious. I thought I'd report here, maybe it can help to identify the issue sometime (if there is any).
