### ISSUE TITLE
Potential node seg fault bug and null check

### ISSUE THREAD

**Issue by thomas7** [nanocurrency/raiblocks#420]
In node/rpc.cpp, line 2748, there is no null check after getting a block. The hash is changing within the for loop, it's possible the hash could be invalid for various reasons such as block_successor failing to read. In that case, the result would be nonzero, the for loop would continue, and the next block_get would be invalid. On line 2751 you would dereference a null block and seg fault.

**Comment by clemahieu** [comment]
This one's inside a transaction and the hash it's querying for is linked through successors.  If the successor block wasn't available that would indicate a database corruption.  Have you seen this be null in the wild?

**Comment by thomas7** [comment]
Haven't seen it in the wild, but felt it could be one of those possible edge cases you might want to check for considering there's a null check everywhere else.  Just something I saw proof reading the code.
