### ISSUE TITLE
Wallet fails to continue updating after waking up from sleep

### ISSUE THREAD

**Issue by yousifa** [nanocurrency/raiblocks#427]
**Description of bug:**

Wallet intermittently stuck and fails to continue updating after computer awakens from sleep on Mac OS 10.13.2 with wallet 9.0

**Steps to reproduce the issue:**
1. Run wallet
2. Put computer to sleep
3. Wake up computer
4. Raiblocks wallet fails to continue updating

**Describe the results you received:**
I noticed this when the wallet did not show my most recent deposit after waking up the computer.

**Environment**:
Macbook Pro Touchbar 15" with MacOS 10.13.2
Raiblocks wallet 9.0

**Comment by androm3da** [comment]
Thanks for the bug report.  Can you gather logs that span the time from when the computer was put through the sleep/wake cycle and shortly afterwards?

**Comment by yousifa** [comment]
File attached below. The computer was put to sleep from 1/5 to 1/6 2018, you will see the gap in time in the log. From the log it seems that everything is fine, but it did not show the new wallet balance (including pending) until the wallet was restarted.

[log_2018-01-05_00-31-06.9.log](https://github.com/clemahieu/raiblocks/files/1609574/log_2018-01-05_00-31-06.9.log)
