### ISSUE TITLE
Block Lattice Diagram has incorrect Account A Balance of 40, it should be 60.

### ISSUE THREAD

**Issue by comeback** [nanocurrency/raiblocks#428]
**Description of bug:**

https://github.com/clemahieu/raiblocks/wiki/Block-lattice

The Balance in Account A prior to Sending 40 XRB to Account B is listed as 100 XRB.  After the send (of 40 XRB to Account B), the Balance in Account A is 40 XRB.  This is incorrect.  The Balance should be 60, because if it's 60, then this indicates there must have been another transaction to Send/Spend 20 XRB or there is missing currency since there are only two transactions in Account A's blockchain:  A1 (100 balance before Send) and A2 (60 balance after Send, not 40).

After the Send, Account B's balance is mysteriously 80, when it should be 60 XRP (overall the accounts reconcile to 120 total XRB).

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by Afkbio** [comment]
Hmm 100-60 = 40 XRB left in balance A
20+60 = 80 XRB in balance B
No probleme there, move on.
