### ISSUE TITLE
Unique diffent log file for each kind of log

### ISSUE THREAD

**Issue by ghost** [nanocurrency/raiblocks#43]
Unique log file for each kind of log:
Max size refer to each unique log.

       "logging": {
            "ledger": "false",
            "ledger_duplicate": "false",
            "network": "true",
            "network_message": "false",
            "network_publish": "false",
            "network_packet": "false",
            "network_keepalive": "false",
            "node_lifetime_tracing": "false",
            "insufficient_work": "true",
            "log_rpc": "true",
            "bulk_pull": "false",
            "work_generation_time": "true",
            "log_to_cerr": "false",
            "max_size": "16777216",
            "version": "2",
            "work_peers": "",
            "vote": "false"
        },

**Comment by rkeene** [comment]
I think overall we have decided not to do this.
