### ISSUE TITLE
Add RPC method to get list of all wallet ids

### ISSUE THREAD

**Issue by kennell** [nanocurrency/raiblocks#430]
Hi there, would it be possible to add a RPC method that works similar to the `./rai_node wallet_list` command?

So, e.g. client sends

```json
{
  "action": "wallet_list"
}
``` 

Node returns

```json
{
  "wallets": [
     "AAAABBBBCCCCDDDDEEEEFFFF",
     "GGGGHHHHJJJJ....."
  ]
}
```

**Comment by cryptocode** [comment]
@kennell I'll take a look

**Comment by kennell** [comment]
Yes this looks fine - thank you for the fast response.

**Comment by androm3da** [comment]
This feature is abandoned, at least for now.  It would be contingent on more significant design changes.
