### ISSUE TITLE
"error initializing node"

### ISSUE THREAD

**Issue by ML432** [nanocurrency/raiblocks#433]
**Description of bug:**

**Steps to reproduce the issue:**
1. Start software
2.
3.

**Describe the results you received:**
The software saying "error initializing node" and then the software crashes.

**Describe the results you expected:**
I want to open the software.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried reinstalling version 9 and 8 several times, nothing helped.

**Environment**:
Windows 7 Swedish language

**logs**

**Comment by Dekoze** [comment]
How much free space do you have on C:?

**Comment by ML432** [comment]
I have 80 GB of free space.
I click to open the software, and within 1 second, I see this popup with "error initializing node",
then it crashes (ie not responding...crash).

**Comment by daranger** [comment]
same problem https://clip2net.com/s/3QZfmA5

**Comment by ML432** [comment]
daranger: Yes, that is the one I'm getting.

**Comment by daranger** [comment]
nothing helps

**Comment by bayoep** [comment]
I hope dev must help this case cause many users got this trouble
