### ISSUE TITLE
RPC Localhost BUG?

### ISSUE THREAD

**Issue by AugustoResende** [nanocurrency/raiblocks#435]
config.json only accept ::1 as a rpc address, not accept localhost or 127.0.0.1.

When i try to call 127.0.0.1, connection refused.

How solve this?

**Comment by donutloop** [comment]
Hi there, 

Did you enabled RPC in your config json? 

# How to find config
https://github.com/clemahieu/raiblocks/wiki/config.json#where-is-the-configuration-file-located

# Structure of config
https://github.com/clemahieu/raiblocks/wiki/config.json#structure-of-configuration-file

Best regards,
Donutloop

**Comment by Dekoze** [comment]
only ipv6 is supported atm

**Comment by luizstacio** [comment]
You need to change config.json these specific properties.
```
    "rpc_enable": "true",
    "rpc": {
        "address": "::ffff:127.0.0.1",
        "port": "7076",
        "enable_control": "true",
        "frontier_request_limit": "16384",
        "chain_request_limit": "16384"
    }
```
To access via 127.0.0.1 you must have the ```"address": "::ffff:127.0.0.1"``` configured.

@AugustoResende please close the issue if it works for you!
