### ISSUE TITLE
Should we go for exceptions?

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/raiblocks#446]
The topic of exceptions came up in https://github.com/clemahieu/raiblocks/pull/439

There's a lot of code in the source tree that does error handling by checking return codes.

I don't  necessarily think throwing exceptions everywhere is appropriate, but some of the code would certainly benefit from a well designed exception hierarchy/structure. And a lot of boost/std methods throw exceptions anyway.

**Comment by pocesar** [comment]
unless the failure result is not discardable, there's no point of exceptions. for example, in the `read_header` method, does it matter if the magic number doesn't match or the version is wrong? I think that would only matter for analyzing debug logs, but without the payload itself, would be of no use. I guess the short-circuiting is the way to go

**Comment by PlasmaPower** [comment]
With exceptions though, you don't have to do short circuiting. You can just call the functions and only worry about failure where it needs handled.

**Comment by cryptocode** [comment]
@pocesar I don't think the read_header method is a good example. There's a lot more complex methods (and chains thereof) that would benefit more.

**Comment by pocesar** [comment]
I'm not fond of exceptions for code that are executed in tight loops, that's something to be aware of. even if it's better for code maintainability, exceptions shouldn't be thrown in functions that performance is crucial (`read_header` is one of them)

**Comment by PlasmaPower** [comment]
C++ exceptions are only slow for the failure case though. How crucial is performance then? I don't think it'll be the bottleneck.

**Comment by cryptocode** [comment]
@PlasmaPower Right. I think the summary at the end of https://mortoray.com/2013/09/12/the-true-cost-of-zero-cost-exceptions/ is good (at least for Itanium ABI compilers). 

In short, it probably doesn't matter, especially not in code dominated by IO where exception cost is basically noise. The "happy path" is fast, but the concern is definitely something to consider in critical paths.

**Comment by pocesar** [comment]
if you think that the nodes / clients will always receive sane packets, indeed, exceptions will be rare. that's not the case

**Comment by PlasmaPower** [comment]
No, I just think that the vast majority (but not 100%) of packets will be sane. I'm also confident this is not the weakest link for a DDOS attack.

**Comment by cryptocode** [comment]
Not always, but almost always.

**Comment by lukealonso** [comment]
In this particular instance it's a dumb waste of cpu cycles in code where the benefit is zero, minus the time that could have been spent programming something useful.

**Comment by cryptocode** [comment]
@lukealonso yeah, there are much better candidates than `read_header` for exception treatment.

**Comment by Dekoze** [comment]
I think node_init is a good example. Any error triggered with it is fatal at run-time and currently the context of the error is lost to a success/fail flag. The result is the user only sees a "error initializing node" output with little else to go off of.

**Comment by cryptocode** [comment]
@Dekoze right, I had the same problem in the daemon, which I've addressed in https://github.com/clemahieu/raiblocks/pull/480

**Comment by cryptocode** [comment]
Going for std::error_code / std::expect instead.
