### ISSUE TITLE
Whitepaper translation to Brazilian Portuguese (PTBR)

### ISSUE THREAD

**Issue by gconcon** [nanocurrency/raiblocks#451]
Guys, I want to translate the whitepaper, how can I get into the PDF source? In english, please.

**Comment by dada1134** [comment]
[RaiBlocks_Whitepaper__English.pdf](https://github.com/clemahieu/raiblocks/files/1613531/RaiBlocks_Whitepaper__English.pdf)

**Comment by julioscalves** [comment]
I think he meant the source file like a .doc as it is easier to edit.

**Comment by gconcon** [comment]
Thats right Colin, to maintain all formatting.

**Comment by brunoelyg** [comment]
We already have a portuguese translation!

**Comment by gconcon** [comment]
Where? Can you share it?

Em 9 de jan de 2018 10:29 PM, "Bruno Ely Reis Garcia" <
notifications@github.com> escreveu:

**Comment by brunoelyg** [comment]
I sent it to DasBoss (Community Manager), he will put it on the official website
