### ISSUE TITLE
Two RPC command descriptions missing

### ISSUE THREAD

**Issue by toxonaut** [nanocurrency/raiblocks#459]
Add description to RPC commands:
- Stop node
- Retrieve node versions

**Comment by androm3da** [comment]
Descriptions on the wiki?   https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#stop-node shows the stop node.

**Comment by toxonaut** [comment]
Yes the wiki descriptions of these two commands lack a one sentence description just under the title (all other entries contain such a description).
