### ISSUE TITLE
Implement an additional data attribute in account state

### ISSUE THREAD

**Issue by triwebb1** [nanocurrency/raiblocks#463]
Currently every account can specify a representative for voting.  It would be very useful to add an additional attribute to account state for arbitrary data.  Even just 32 or 40 bytes could extend the usefulness of XRB by several orders of magnitude.

Create a new message type, maybe called "DATA", which is used to overwrite the 32-byte data attribute which is to be available in every account's state.  Limiting the size to 32 bytes incurs the smallest practical impact to disk and network utilization, and because PoW will be required on this transaction it will not be practical for anybody to abuse this storage space.  Allowing for more space would be more useful.

The 32 bytes that I'm proposing could be used to store a hash of data, perhaps a reference to a document in IPFS.

**Comment by androm3da** [comment]
I think this is an interesting innovation.  Other than arbitrary IPFS references, can you cite some specific use cases for how it could be leveraged?

I think asking the cryptocoin to carry these at no cost is inviting abuse, despite the PoW.  But if the uses are compelling, it's worth discussing how we could find a solution.

**Comment by triwebb1** [comment]
Another way to prevent abuse is to do as Ripple has done and impose a minimum account balance.  In order for an account to be opened it must have a minimum amount of funds sent to it.  In Ripple that balance can never be withdrawn, but it could be possible to have a CLOSE message to prune an account out and return the funds to another account.

The IPFS use case is the most extensible because the document being linked to can be of any size and for any use.  In that case XRB is acting as a name service sorta like IPNS / ENS / NameCoin, where the name is the XRB account and the target is the IPFS document.

The IPFS document being linked to could contain any number of things, here's some that come to mind:

1. Signed messages proving identity (PGP perhaps)
2. Contact information (email, phone, website, whatever)
3. Attestations from 3rd parties (KYC or other authorization)
4. User described policies or configurations

One neat application I just thought of is verification of the destination account.  Say you are sending funds to an address, you paste it in your wallet to send, then async in the background the wallet looks up the IPFS document for that address you pasted, locates the name of the business that it claims to be, and then presents you with the name and logo so that you feel better about sending your funds to that address.

A different take on that could be verification of payment routing.  Say I want to pay business.com via a link on their website.  Their link says "pay to addressA".  I click the link, it opens in my wallet, it's ready to pay addressA.  Through that IPFS document I can verify that addressA really does claim to be business.com, especially if it's signed with a business.com PGP key or something.  This way if someone hacks business.com and injects their own address I won't get fooled.

Another use could be for KYC/AML.  When a user completes KYC the provider that verified the identity could provide a signed message stating this user is "ok" (whatever that means), and the user could put that in their IPFS document.  Now when someone considers sending funds to this address they can see that the KYC provider signed off on this account, so it's safe to interact with.

The possibilities are endless.  This shouldn't be used for frequently changing data, but the actually storage and bandwidth consumption for 32 bytes is quite low so the PoW really makes sense.  DATA could have a 3x higher PoW requirement than SEND to further deter abuse.

**Comment by triwebb1** [comment]
Instead of creating a new message type, the existing CHANGE type can be re-purposed to set the DATA attribute instead of only being used to change the representative.  It would still be possible to 3x the PoW difficulty requirement if the CHANGE message includes the DATA attribute.

If the 1 packet size limit is an issue then the CHANGE message could be only allowed to change 1 attribute at a time: data or representative.

**Comment by clemahieu** [comment]
Nano won't support a data payload.

**Comment by Inkeliz** [comment]
You can use the "Representative" field for that, it's 32-byte. It's not an data-field, but you can use as one. (:
