### ISSUE TITLE
Mac desktop wallet doesn't support IPv6?

### ISSUE THREAD

**Issue by tolinwei** [nanocurrency/raiblocks#465]
**Description of bug:**

 Cannot connect the Mac desktop RaiBlocks wallet in company's wifi network (I guess they don't support IPv4)

**Steps to reproduce the issue:**
1. Download the Mac desktop wallet from https://raiblocks.net/
2. Drag RaiBlocks into Application folder, open it
3. On top the the window, it says `Status: Disconnected, Block: xxxxx`
4. Go to the log folder `cd /Users/{user}/Library/RaiBlocks/log`, tail the log `tail -f log_2018-01-09_14-32-54.4.log`, it keeps showing
```
[2018-01-09 14:34:32.624484]: Starting bootstrap attempt
[2018-01-09 14:34:32.624798]: Bootstrap stopped because there are no peers
[2018-01-09 14:34:32.624886]: Exiting bootstrap attempt
```
5. Go to the desktop wallet --> Advanced --> Peers, it seems it can only connect to peers at IPv6 addresses, that why I suspect the company's wifi doesn't support IPv6
6. If I use the same laptop (Macbook) and connect to the wifi at my home, the wallet can be connected successfully

**Describe the results you received:**

**Describe the results you expected:**
Get the wallet connected!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**
I pasted the log above, the logs are just the repeats of that three sentences.

**Comment by jondwillis** [comment]
It could also be that your peering port is being blocked by your company. Port 7075, UDP.

**Comment by tolinwei** [comment]
Thanks for the explanation, is there any way to use other port?

**Comment by clemahieu** [comment]
In config.json you can set the peering_port to whatever you want.

The rai node internally only operates on IPv6 and it interacts with IPv4 through mapped addresses e.g. "::ffff:127.0.0.1"

If the node is only able to connect to IPv6 addresses it seems your network is disallowing IPv4 for some reason.  Though if you have IPv6 peers in the list it should be listed as connected.  Disconnected should only be there if it has no peers.
