### ISSUE TITLE
Investigate using custom lmdb comparison function

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/raiblocks#470]
Rather than blocks being a mapping of hash -> {block_data, extra_info} and using a normal comparison operator on hash store block_data -> extra_info and use a custom comparison operator that hashes the block data.

The idea is to reduce storage by not storing the hash which can be derived from the block data.

**Comment by chpio** [comment]
Are there lockups done by hash?

**Comment by chpio** [comment]
But the system would store a hash anyway for faster access/indexing?

**Comment by rkeene** [comment]
Ultimately, I think that the hash is valuable to us in general and for at least the active (non-pruned) dataset we should store the hash.  For archival data, we can implement these optimizations but it will be a different set of work.

I'm going to close this ticket, but we can keep the idea of minimizing stored data in mind.
