### ISSUE TITLE
Translations into Dutch?

### ISSUE THREAD

**Issue by ahakla** [nanocurrency/raiblocks#472]
Hi everyone,

I'm really enthusiastic about the RaiBlocks project.
If I can help doing some translations into Dutch (wallets for instance?), let me know.

Best regards,
Ahakla (I prefer not to use my real name)

**Comment by GoneUp** [comment]
I think at the moment it is not possible to translate the wallet to induvidual languages. The strings are hardcoded in english. (like [this](https://github.com/clemahieu/raiblocks/blob/0291abfe48df8ab080a5b67fe42d26dfd729d0ca/rai/qt/qt.cpp#L121))
We would first need somone to lay the fondation and move the strings out of the code. Looks like qt has already support for [this](https://wiki.qt.io/How_to_create_a_multi_language_application).
