### ISSUE TITLE
Empty send transactions are broadcast

### ISSUE THREAD

**Issue by frankh** [nanocurrency/raiblocks#473]
**Description of bug:**

If you send an empty transaction, (i.e. where the send block's balance is equal to the previous block's balance), nodes will still rebroadcast the block and you can still create a receive block for it

**Steps to reproduce the issue:**
Using desktop rai wallet, send 0 rai to an address

**Describe the results you received:**
The 0 send is valid, and broadcast. See e.g. https://raiblocks.net/block/index.php?h=5B1BB1BBFE9427FD6330D6D3B64BAC7706EF4EDF9BC74D56765B391B3F914637

**Describe the results you expected:**
Nodes should not relay empty sends

It may not actually be a problem as penny spends are so cheap anyway, but it doesn't feel right

**Comment by PlasmaPower** [comment]
You can also send rai to yourself (send it to the same address you sent it from). I don't think this is really a bug, as it doesn't seem to have negative side effects.

**Comment by eirikrye** [comment]
What is the value in being able to send zero-value transactions? They should be discarded as invalid blocks since they do nothing but use bandwidth and increasing the size of the ledger.

Sure, you could send 1 Raw instead, but at least this actually changes the state of the ledger, and **is** a value transfer.

**Comment by eirikrye** [comment]
> I don't think this is really a bug, as it doesn't seem to have negative side effects.

Unnecessary resource usage is a negative side effect.

**Comment by PlasmaPower** [comment]
Then how do you deal with existing zero sends? The "solution" is complicated and doesn't have much benefit.

**Comment by frankh** [comment]
@PlasmaPower I was thinking maybe make representatives stop issuing votes for zero sends from now on and make nodes only relay zero sends with some significant % of votes (10?) or something

**Comment by frankh** [comment]
While I agree this isn't a high priority to fix at all, it does raise some questions about how it would be done.

In bitcoin you can specify a fork block and ensure you have consensus before then, but I'm not sure how RaiBlocks can cleanly implement a non-compatible change

**Comment by Afkbio** [comment]
For this case, you just implement it. Who cares if a few 0 sends are lost.

**Comment by eirikrye** [comment]
@Afkbio Because it would make the account chains with zero-value sends invalid.

**Comment by PJ5891** [comment]
The ability to have blocks with zero value sends, does this not open the network to spam attacks. If it costs some one nothing to send a zero value sends, could they not broadcast a ridiculously high number to some detrimental effect??

**Comment by PlasmaPower** [comment]
Not any more than spending 1 raw, which is extremely small (something like 10^-30 XRB). The spam prevention is PoW.

**Comment by senikk** [comment]
> What is the value in being able to send zero-value transactions? They should be discarded as invalid blocks since they achieve nothing but consume resources.
I disagree with you, I could see several use cases for zero value sends which costs nothing and her is two of them like triggering something even your light bulb if you want to where a service is listen for transaction from a specific address or another user case could be as part of two factor login.

**Comment by eirikrye** [comment]
@senikk Why would you use Raiblocks to turn on your light bulb, or any decentralized blockchain solution for that matter? You're cracking nuts with a sledgehammer.

Raiblocks has been designed from the ground up to be used for simple value transfers: `Do one thing - and do it well`. They have, by design, decided against any method of arbitrary data storage in the Raiblocks ecosystem.

 With that in mind, zero value transactions seem like an oversight and a flaw in the design.

**Comment by senikk** [comment]
Light bulb was just a simple example, here is a more real world example. Say you own a unmanned gym where you would like to have the door opened when paying with XRB for those who use it not that much and for those who have allready payed for a subscription you want them to open the door for free. Sure if 0 value transaction isn't allowed you could still send the smallest amount of XRB and the receiver door locker service just sending the XRB back causing yet another send and receive transaction on the network.

**Comment by senikk** [comment]
I have read about another good use case for zero transactions and that is for verification of an account. Lets say you have entered a deposit account address into a 3rd party solution it could be a marketplace or exchange or whatever solution which is going to send you payments afterwards. Just send a zero transaction to the solutions address and your deposit address could when be verified.
