### ISSUE TITLE
Block shows ZERO balance when shouldn't

### ISSUE THREAD

**Issue by embatbr** [nanocurrency/raiblocks#476]
I did a deposit in CoinFalcon, sending funds to an address `xrb_3wf86opw7stwy3jx1yo4ew8j6b8ous4jfxfijtxmhpebx6fghzo8sm8ss4pi`, that sends to their hot wallet `xrb_3p6cuqctk3jhcezj7dz9zg3ykrup1y8d5sar6wrxssw546feofpmcyciruee`.

In block explorer shows 100 Mrai received from my personal account to this intermediary and 100 Mrai sent from this intermediary to their hot wallet.

However, when exploring the send block, the balance shown is ZERO, even shown as 100 in the hot wallet's transactions list. Is this a bug in RaiBlocks implementation or in the exchange's automation?

**Comment by embatbr** [comment]
I address the question in reddit: https://www.reddit.com/r/RaiBlocks/comments/7peug0/daily_general_discussion_january_10th_2018/dsi78e9/

**Comment by embatbr** [comment]
The problem with the exchange was solved (funds credited). They said the node had a problem (my transaction hadn't appeared there).

I think their system went down for a moment and they may have lost the info (in the node itself or in the integration with the exchange).

**Comment by frankh** [comment]
This was a problem with the exchange's node

The balance being zero on the send from intermediate to their hot wallet is expected, balance is the sending account's balance AFTER the transfer, not the amount being transferred

**Comment by embatbr** [comment]
@frankh could you guys help them to configure the node better? Similar to what you're doing with Bitgrail and Mercatox?

**Comment by frankh** [comment]
I'm not on the team :)

I'm sure they're working with them, though in my experience coinfalcon withdrawals and deposits have been quick

**Comment by embatbr** [comment]
Deposits were always quick (this one was due to a system failure). Withdrawals depend on the amount.

They're a very small exchange.

**Comment by argakiig** [comment]
Please reopen if still persistent
