### ISSUE TITLE
Why not pull the accounts that we already have stored firstly

### ISSUE THREAD

**Issue by 6612172** [nanocurrency/raiblocks#482]
I have read the code for some days to find out why sync is slow. It seems that sync by pulling all of the accounts' blockchain in order then processing the blocks.

here are some my suggestions:
pull the accounts that we have stored.
when receive a send block, store the destination if the account has not been stored yet.

**Comment by PlasmaPower** [comment]
It's important to network stability (and ironically, sync speed) to have most nodes be full nodes. What you're describing could work for an individual node, but not for the whole network.

**Comment by 6612172** [comment]
@PlasmaPower 
Could new node try this suggestion untill it reach 1/2 or more of full nodes.

When a node is new, it will pull the data over and over again, and blocks remain unchecked. It is also a waste of network. 

Maybe I  have not thought about all the cases, but it is really slow for the destkop wallet and the rain node on centos is just ok.t

**Comment by rkeene** [comment]
This will be implemented as part of lazy bootstrapping #995.
