### ISSUE TITLE
Wallet balance issue

### ISSUE THREAD

**Issue by Afkbio** [nanocurrency/raiblocks#490]
Windows wallet 9.0 (and linux wallet too apparently) does not show correct balance under 1 XRB when default unit (Mxrb) is selected.
Does not show transactions under 1 XRB either.

If you send 0.1 XRB when you have 1XRB in a wallet, balance appears as 0 and it looks like you transferred 0. 

You can see the real balance by switching units in the advanced tab.

**Comment by GoneUp** [comment]
Two interesting observations while confirming this issue: 
-  I can't send sub XRB transactions. If I send 0.1 XRB a block with the same balance as the previous one is made.
- Neither the account balance nor the amount transacted support support decimals.
- Also (XRB) at the balance text isn't updated to (KXRB). 
Screen with setting xrb: https://i.imgur.com/u4iVBGV.png
Screen with setting kxrb: https://i.imgur.com/naSQlH3.png

**Comment by Afkbio** [comment]
Yes I was not sure about the sub XRB transactions, but now that you say it...

**Comment by stefonarch** [comment]
I guess it's misleading the units name: xrb in the rai_wallet are the non divisible smallest unit, what we refer to usually is Mxrb, just set in "advanced" tab scale to xrb and you will see real big numbers.
