### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/raiblocks#494]
A C API would provide a fast and secure interface to the node and wallets (one less open port) 

I've been prototyping a tiny subset, namely starting a daemon and shutting it down. Most of the work was making `daemon::run` non-blocking, really. If anyone else is doing something similar, please let me know ;)

@clemahieu suggested that RPC can later be rewritten in terms of the C api, and we can obviously provide many language bindings.

Sample Python (ctypes) script:

```
from ctypes import *
lib = cdll.LoadLibrary('./librai_api.dylib')

class NodeClient(object):
    def __init__(self):
        lib.xrb_node_daemon.restype = c_void_p
        lib.xrb_node_daemon_join.argtypes = [c_void_p]
        lib.xrb_destroy.argtypes = [c_void_p]

        # Start a daemon
        self.rai = lib.xrb_node_daemon('./test/node-1')

        # Start a thread, interact with node via API based on events or whatnot

        # Later on
        lib.xrb_node_daemon_join(self.rai);
        lib.xrb_destroy(self.rai);

NodeClient();

```

Another idea is using something like Duktape to expose the C api to JS for automation purposes and whatnot (embed node, load JS scripts which calls into the API)

These are early days and I'll be working on and off on this. Suggestions and considerations welcome.

**Comment by learnforpractice** [comment]
Here is a python binding.

https://github.com/learnforpractice/pyraiblocks/commits/master <https://github.com/learnforpractice/pyraiblocks/commits/master>


./rai_node --daemon --data_path data-dir

>>> dir(rai)
['JsonStruct', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '__test__', 'account_balance', 'account_block_count', 'account_create', 'account_get', 'account_history', 'account_info', 'account_key', 'account_list', 'account_move', 'account_remove', 'account_representative', 'account_representative_set', 'account_weight', 'accounts_balances', 'accounts_create', 'accounts_frontiers', 'accounts_pending', 'available_supply', 'block', 'block_account', 'block_count', 'block_count_type', 'block_create', 'blocks', 'blocks_info', 'bootstrap', 'bootstrap_any', 'chain', 'delegators', 'delegators_count', 'deterministic_key', 'frontier_count', 'frontiers', 'genesis_account', 'get_last_error', 'history', 'json', 'keepalive', 'key_create', 'key_expand', 'krai_from_raw', 'ledger', 'mrai_from_raw', 'mrai_to_raw', 'password_change', 'password_enter', 'password_valid', 'payment_begin', 'payment_end', 'payment_init', 'payment_wait', 'peers', 'pending', 'pending_exists', 'process', 'receive', 'receive_minimum', 'receive_minimum_set', 'representatives', 'search_pending', 'search_pending_all', 'send', 'successors', 'unchecked', 'unchecked_clear', 'unchecked_get', 'unchecked_keys', 'validate_account_number', 'version', 'wallet_add', 'wallet_balance_total', 'wallet_balances', 'wallet_change_seed', 'wallet_contains', 'wallet_create', 'wallet_destroy', 'wallet_export', 'wallet_frontiers', 'wallet_locked', 'wallet_pending', 'wallet_representative', 'wallet_representative_set', 'wallet_republish', 'wallet_work_get', 'work_cancel', 'work_generate', 'work_get', 'work_peer_add', 'work_peers', 'work_peers_clear', 'work_set', 'work_validate']

>>> rai.block_count()
{'count': '246838', 'unchecked': '3803448'}


>>> rai.account_block_count(b'xrb_13ezf4od79h1tgj9aiu4djzcmmguendtjfuhwfukhuucboua8cpoihmh8byo')
40284

>>> rai.account_balance(b'xrb_13ezf4od79h1tgj9aiu4djzcmmguendtjfuhwfukhuucboua8cpoihmh8byo')
{
    "balance": "1891102769630454844999490984052240694",
    "pending": "91614483401791124778600855847014518456"
}


Have fun!

**Comment by cryptocode** [comment]
@learnforpractice That's generated with CPython, right? 

Python bindings based on the C api would probably end up looking quite similar.

**Comment by PlasmaPower** [comment]
No I think @learnforpractice misunderstood the question. Those look like RPC bindings.

**Comment by cryptocode** [comment]
@PlasmaPower Are you sure? There's definitely CPython generated code in his repo, as well as wrappers accessing transactions directly.

**Comment by PlasmaPower** [comment]
Oh yeah never mind. They just looked modeled after the RPC endpoints.

**Comment by cryptocode** [comment]
Currently being implemented
