### ISSUE TITLE
Why there is always some blocks unchecked?

### ISSUE THREAD

**Issue by libaniocv** [nanocurrency/raiblocks#505]
I finally get to completely sync (Release 9.0 Ubuntu 64x)
But slowly the "unchecked" started to grow. The "count" is equal the total blocks statistic in https://www.raiblocks.club/blocks, so i think is not that bad.
But it will slow down transactions in the future? These 215 unchecked blocks are always the same problematic blocks?
Should i use the command "clear_unchecked"?

**Comment by pocesar** [comment]
because the transactions are much faster than 5400 RPM hard disks and bandwidth (at least home internet) can handle, so it'll always be behind, and if people start using on RaspPi, it will be even slower. But it's just a matter of time and having more nodes and distributing the workload better

**Comment by eirikrye** [comment]
@pocesar This is just outright false, but keeps being brought up as the reason for sync issues for some reason.

Even a fully synced node, which sees about 5 new transactions per -minute- will have lots of unchecked blocks. Here is the current status of my node:

```
{
    "count": "5032691",
    "unchecked": "3203"
}
```

If you actually look at resource usage (disk i/o and bandwidth), you will notice that they are not saturated at all.

**Comment by pocesar** [comment]
mine is, and a lot of people are reporting massive I/O

**Comment by FSMaxB** [comment]
My wallet is not doing more than 200kiB/s of disk IO and the number of unchecked blocks keeps growing slowly, but still faster than the number of checked blocks. Something is really wrong here.

**Comment by stefonarch** [comment]
My idea is that the cleaning of the brackets just don't work well, it makes you  think you are not in synv but you are:
![schermata-19-14-05-11](https://user-images.githubusercontent.com/10681413/35152239-cd5528f2-fd21-11e7-81a1-175304ae7438.png)

**Comment by stefonarch** [comment]
On my server node I tested [this](https://github.com/clemahieu/raiblocks/wiki/RPC-protocol#clear-unchecked-blocks)

`curl -g -d '{ "action": "unchecked_clear" }' '[::ffff:127.0.0.1]:7076'
{
    "success": ""
}
`

and it brings the count to zero. But still wondering what exactly those blocks are and why they  grow.

**Comment by rkeene** [comment]
Unchecked blocks are blocks which cannot be tied through any chain to the Genesis block which is distributed as part of the Nano software.  These blocks can be generated by anyone and added to the network for nodes to attempt to add to the chain as the missing "gap" or intermediate blocks are broadcast.

The plan for the future is to clear unchecked blocks out as either a circular buffer of fixed size or as they expire, or both.

I'm going to close this issue with this explanation and leave the implementation of the plan above to a separate ticket.  Please let me know if you have further questions.
