### ISSUE TITLE
Data size in raiblocks folder looks too big

### ISSUE THREAD

**Issue by niltonvasques** [nanocurrency/raiblocks#513]
Is this **9.5G** size correct?

Everytime that I open my wallet, the syncronization starts again and it takes a lot of time to finish.

:~/RaiBlocks$ ls -lh
**total 9.5G**
drwxr-xr-x 2 user user 4.0K Jan 17 14:07 backup
-rw-r--r-- 1 user user 2.4K Jan 17 14:07 config.json
**-rw------- 1 user user 9.5G Jan 19 23:04 data.ldb**
-rw------- 1 user user 8.0K Jan 19 23:04 data.ldb-lock
drwxr-xr-x 2 user user 4.0K Jan 19 22:59 log

**Comment by matiwinnetou** [comment]
I was wondering the same. I am running full node and have no idea why it is already almost 10 GB...

**Comment by PlasmaPower** [comment]
The vacuum feature should help with this. If you built raiblocks from git, you can do `rai_wallet --vacuum`. I don't think the latest release has this though.

**Comment by matiwinnetou** [comment]
I did do vacuum, results:
```

**Comment by Armalon** [comment]
my data.ldb is 107GB!

**Comment by matiwinnetou** [comment]
@Armalon read above comments and you vacuum feature

**Comment by Armalon** [comment]
@matiwinnetou Thank you, but I've already solved the problem by downloading a data.ldb from the internet, then I replaced my big file with it.

**Comment by stefonarch** [comment]
While trying running rai_node (git version) on a linode.com ubuntu16.04 I have similar issues:

```
/RaiBlocks# ls -lh
total 15G
drwxr-xr-x 2 root root 4.0K Jan 28 20:39 backup
-rw------- 1 root root 9.0G Jan 31 09:16 backup.vacuum.ldb
-rw-r--r-- 1 root root 2.3K Jan 30 20:43 config.json
-rw-rw-rw- 1 root root 2.4K Jan 30 20:32 config.json.newest
-rw-r--r-- 1 root root 6.1G Jan 31 09:14 data.ldb
-rw------- 1 root root 8.0K Jan 31 09:16 data.ldb-lock
drwxr-xr-x 2 root root 4.0K Jan 31 08:13 log

```
Vacuum did work somehow but confronted with rai_wallet vacuumd 1,4GB/1,6GB)  on my PC it's still huge and  I run nearly out of space (19GB) on the server.

**Comment by matiwinnetou** [comment]
@stefonarch You just need to remove backup file after running vacuum command.

**Comment by stefonarch** [comment]
Sure I did after, but while vacuuming there were both present and disk usage went to 99%

**Comment by cryptocode** [comment]
@stefonarch vacuuming *must* work on a copy, there's no way around that.

**Comment by stefonarch** [comment]
That is clear, but why are both su huge? Here it says ledger size is little more than 2gb 
https://rai.watch/stats/node

**Comment by stefonarch** [comment]
Looks better, after some hour I'am at half blocks (unchecked) and the size of data.ldb is 1.6G
