### ISSUE TITLE
Infinity data.lbd grow. 20GB

### ISSUE THREAD

**Issue by morzhantsev** [nanocurrency/raiblocks#522]
Data.lbd grows infinity. File takes over 20GB

**Steps to reproduce the issue:**
1. just run rai_node (9.0) from scratch
2. don't use daily backup file

**Describe the results you received:**
data.lbd file grows infinity. It takes 20 GB (~ 600k blocks downloaded)

**Describe the results you expected:**
data.lbd file size should be around 1.7GB (~5 mln blocks should be downloaded)

**Additional information you deem important (e.g. issue happens only occasionally):**
maybe 

**Environment**:

Ubuntu 64
rai_node (9.0)

**logs**

**Comment by PlasmaPower** [comment]
Does the new vacuum feature fix it?
