### ISSUE TITLE
Node attempts to connect to local address peers

### ISSUE THREAD

**Issue by icarusglider** [nanocurrency/raiblocks#523]
It has been found that when discovering peers, any node with local address peers will advertise these peers to others. This causes every node to attempt to connect to local address ranges, which can cause issues for certain hosting providers (seen with Hetzner.de so far, "suspicious traffic").

Suggest removing 192.168.0.0/16, 172.22.0.0/12, 10.0.0.0/8 from peer list before it is sent to other nodes. Also suggest preventing attempts to connect to peers on said subnets if the bound ip of the node is not also on such a subnet.

![image](https://user-images.githubusercontent.com/7392093/35232235-96d25872-ff60-11e7-933e-1bb5ddcb9bff.png)

**Comment by elliottneilclark** [comment]
http://www.team-cymru.org/bogon-bit-notation.html
