### ISSUE TITLE
requeue_pull

### ISSUE THREAD

**Issue by cryptocode** [nanocurrency/raiblocks#524]
Could someone help me shed some light on `bootstrap_attempt::requeue_pull` ?

It's called with a fresh `pull_info` (and thus `attempts` is 0), and the first thing the function does is copy it.

Seems to me that `attempts` can never be anything but 1 after the increment, hence the other if-branches are effectively dead code. A debugging session seems to confirm this, but please let me know if I'm missing something.

I'm also wondering about the intention behind incrementing twice in the case where attempts is 3 initially (which I don't think can ever happen though)

**Comment by androm3da** [comment]
This looks like a bug to me.

**Comment by SergiySW** [comment]
Where is it called with fresh pull_info?
https://github.com/clemahieu/raiblocks/blob/4a491069b81ac3a717e64dbc1ad288d9fc9410de/rai/node/bootstrap.cpp#L473

**Comment by cryptocode** [comment]
@SergiySW right, that creates a new pull_info every time (with attempts 0)

**Comment by SergiySW** [comment]
Right
