### ISSUE TITLE
v9.0 aarch64 rai_node binary 404ing

### ISSUE THREAD

**Issue by itdaniher** [nanocurrency/raiblocks#532]
```
wget https://www.raiblocks.net/wallet/V9.0/aarch64/rai_node
--2018-01-24 11:50:23--  https://www.raiblocks.net/wallet/V9.0/aarch64/rai_node
Resolving www.raiblocks.net (www.raiblocks.net)... 104.31.69.185, 104.31.68.185, 2400:cb00:2048:1::681f:44b9, ...
Connecting to www.raiblocks.net (www.raiblocks.net)|104.31.69.185|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-24 11:50:28 ERROR 404: Not Found.
```

**Comment by stefonarch** [comment]
Where did you find that link? Correct links are:
https://github.com/clemahieu/raiblocks/releases
https://github.com/clemahieu/raiblocks/releases/download/V9.0/rai_node.xz

**Comment by itdaniher** [comment]
![screenshot 2018-02-06 at 9 52 45 am](https://user-images.githubusercontent.com/22683/35865821-89b75920-0b23-11e8-8194-c045dd72a2be.png)

on raiblocks.net

the button for aarch64 still points to https://www.raiblocks.net/wallet/V9.0/aarch64/rai_node and still 404s.

**Comment by aasgaard** [comment]
Same problem on nano.org since the rebrand.

**Comment by rkeene** [comment]
I am closing this ticket as overcome by events.
