### ISSUE TITLE
Desktop wallet breaks my network

### ISSUE THREAD

**Issue by BWagener** [nanocurrency/raiblocks#533]
**Description of bug:**
While the desktop wallet is running, most of the time, no device on the network can access most websites.

**Steps to reproduce the issue:**
1. For me, I just have to launch the desktop wallet and wait

**Describe the results you received:**
Most websites are no longer reachable (for instance reddit).
Pinging a website that is not accessible returns the message "Destination net unreachable".
See the following two videos, recorded on the 23rd and the 24th where I'm trying to showcase the issue.
1: https://youtu.be/_1Esvz_h9wg
2: https://youtu.be/EBIr6VVoC8E
You will see that the issue doesn't always appear right away or at all when launching the wallet. The problem only appears when the wallet was executed and can remain until the router is restarted.

Every google site is still accessible, facebook as well. The wallet application itself also has no issues synchronizing and running.

**Describe the results you expected:**
An unimpeded access to all sites :)

**Additional information you deem important (e.g. issue happens only occasionally):**
It's possible the issue lies with my ISP. All I know is that it only occurs when the wallet is running. It took me a long while to connect my internet issues to the wallet application, yesterday I had a technician from my ISP come over and diagnose the issue, he couldn't figure it out and replaced my router. After the problem turned up again later on the same day I tested with the wallet application running / not running and now am certain that the issue is caused by running the wallet.

**Environment**:
- Windows 10 Professional 64 bit
- Windows Wallet 9.0

Logs are from the days on which the videos were captured.
[logs.zip](https://github.com/clemahieu/raiblocks/files/1660521/logs.zip)

**Comment by pocesar** [comment]
basically, you're being DDoS'ed by the UDP packets sent by the network. this will be better soon with improvements upcoming to the wallet

**Comment by stefonarch** [comment]
Same issue on fresh git build with nano_wallet, it makes Internet unusable.

And more than that: it does not shut down connections, there is remaining still a  lot of outgoing traffic, only suspending for half an hour works. Should  I open a separate issue for that?

**Comment by rkeene** [comment]
We are working to resolve this issue with node stratification (#1092) as well as moving the real-time network to TCP to resolve many issues with using UDP as part of a peer to peer network where reliably sending datagrams to the entire network.

I'm going to close this issue so that we can track the two above issues more centrally.  Let me know if you have any questions.
