### ISSUE TITLE
Bug in my Wallet seed

### ISSUE THREAD

**Issue by Enckyrium** [nanocurrency/raiblocks#557]
Hello, I recently sent XRBs to my desktop wallet, but it was new and I did not put a password, and I left it synchronizing at night, only then, when I tried to get into it, it would not open, as if I had a password, and I could not enter because neither the option to rescue the seed I had, because I had not put a password to recover it, help me.

Windows 10 pro x64
node 8.0.0
![26194407_1884020004958917_793711118_o](https://user-images.githubusercontent.com/35894600/35483239-ebd4b462-0426-11e8-9f68-4e56ab5e6d74.jpg)

**Comment by stefonarch** [comment]
0.8 is outdated, try installing the latest version 0.9 and launch it.
