### ISSUE TITLE
iOS & Android code

### ISSUE THREAD

**Issue by goktugyil** [nanocurrency/raiblocks#560]
Are the codebases for mobile close source? If so why?

**Comment by BenedictP** [comment]
Would be nice to have more informations. I'm a native android developer and could do some contributions.

**Comment by icarusglider** [comment]
Right now, we could use a libsodium JNI AAR with the ed25519 signing functions changed to use blake2b instead of sha512. I started on this but my modifications didnt quite pan out.

**Comment by rkeene** [comment]
The code bases are now open and can be interacted with on GitHub: https://github.com/nano-wallet-company
