### ISSUE TITLE
Idea to increase speed of a single transaction

### ISSUE THREAD

**Issue by fel2fram** [nanocurrency/raiblocks#565]
This change doesn't improve maximum tx/s, it only makes a single transaction faster.
Currently for a block to be confirmed and relayed by a node, it has to validate all these criteria, whitepaper says :

1) The block must not already be in the ledger (duplicate
transaction).
2) Must be signed by the account’s owner.
3) The previous block is the head block of the account-chain. If it exists but is not the head, it is a fork.
4) The account must have an open block.
5) The computed hash meets the PoW threshold requirement.

If it is a receive block, check if the source block hash is
pending, meaning it has not already been redeemed. If it is a
send block, the balance must be less than the previous balance.
Then the node signs the block with its own key and broadcasts it.
_______________________________________

What I'm suggesting would reduce  these criteria to one :
1) this block is signed by an account that's in the node's OK-list.

Then the node signs the block with its own key and broadcasts it, removes the account from the OK-list and does the remaining verifications in order to put it back on the list.

Attack vectors :

- Spam ? No because the only way to be in someone's OK-list is to have done a correct PoW in the previous block (or in case the block is an open block, that there was a send block to the account with a correct PoW)
- Invalid block ? Clients have to be careful and check when receiving money if the send block is correct. To make it even safer, nodes can broadcast a message as soon as they see a discrepancy in a block.

What do you guys think ?

EDIT : I found a flaw. People can spam other people's previous transactions without having to do any PoW. This can be solved by require accounts to define a new public key at every transaction.

**Comment by frankh** [comment]
As far as I can tell, the idea is to save time by doing the following asynchronously:


1. The block must not already be in the ledger (duplicate
transaction).
2. Must be signed by the account’s owner.
3. The previous block is the head block of the account-chain. If it exists but is not the head, it is a fork.
4. The account must have an open block.
5. The computed hash meets the PoW threshold requirement.

All of these can be verified in less than a millisecond total easily, so best case scenario with this change is to make sends 1ms faster
