### ISSUE TITLE
Non-voting nodes should only broadcast blocks once

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/raiblocks#57]
To reduce outbound traffic

**Comment by rkeene** [comment]
Given vote-by-hash and our changes to block resending, what should we do here ?

**Comment by SergiySW** [comment]
Not sure if this will not break network integrity. Broadcasting node connection can be broken for a few seconds at broadcasting time

**Comment by SergiySW** [comment]
Was it resolved with broadcasting until confirmed, @clemahieu ?

**Comment by clemahieu** [comment]
Yes this was fixed when we removed the 4-count of rebroadcasting. Closing.
