### ISSUE TITLE
Bootstrap server limiting

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/raiblocks#571]
Add a config option to disable bootstrap serving or the number of incoming connections / speed.
Add a flag to rai::message header flags signifying if a node claims it will not respond to bootstrap attempts.
Track this flag in peer_information and don't attempt to contact these nodes for bootstrap.

**Comment by renesq** [comment]
Possible duplicate 
https://github.com/clemahieu/raiblocks/issues/255
https://github.com/clemahieu/raiblocks/issues/419

Where do you actually draw the line between initial bootstrapping (few peers, much bandwith per each) and ongoing peer block exchange (many peers, low bandwith per each)? Especially if the "limited" node wants to broadcast a new block, it's supposed to be able spread packets anyway!?

**Comment by PlasmaPower** [comment]
@renesq "bootstrapping" refers to the TCP connection, for receiving blocks in bulk. Normal broadcasting is done over UDP.
