### ISSUE TITLE
search_pending should iterate over wallet keys and search for pending blocks instead of scanning entire list

### ISSUE THREAD

**Issue by clemahieu** [nanocurrency/raiblocks#58]

**Comment by rkeene** [comment]
This appears to be an optimization that it is likely we have already done

**Comment by SergiySW** [comment]
Improved in https://github.com/nanocurrency/raiblocks/commit/2b203b1923bcde489616639600c8d6d62303b8c8
Can be closed

**Comment by SergiySW** [comment]
Done in https://github.com/nanocurrency/raiblocks/pull/866
