### ISSUE TITLE
Error deserializing config

### ISSUE THREAD

**Issue by toboe524** [nanocurrency/raiblocks#596]
**Steps to reproduce the issue:**
1. git clone --recursive https://github.com/clemahieu/raiblocks.git
2. cd raiblocks && mkdir b && cd b
3. cmake .. -DRAIBLOCKS_GUI=ON              
4. start nano_wallet from build dir

**Describe the results you received:**
Window with "Error deserializing config" and program terminates

**Describe the results you expected:**
Nano wallet works

**Additional info**
Linux 4.14.14-300.fc27.x86_64 #1 SMP Fri Jan 19 13:19:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
g++ (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)

**Comment by cryptocode** [comment]
What do the version numbers in your say?

**Comment by toboe524** [comment]
What config?

**Comment by cryptocode** [comment]
Well, are you creating a new wallet with --data_dir or opening an existing data dir (the default locations are located at the end of https://github.com/clemahieu/raiblocks/wiki/config.json)

**Comment by toboe524** [comment]
No, unless the above commands do it. I haven't run anything xrb related prior to above commands.

**Comment by toboe524** [comment]
Ok the gui started working after I ran `./rai_node --wallet_create`. Suprising that this wasn't found in testing...

**Comment by cryptocode** [comment]
@toboe524 nah, the generic config error is a known issue. Will be fixed.
