### ISSUE TITLE
WTF: 'Access-Control-Allow-Origin: *

### ISSUE THREAD

**Issue by tnkmt** [nanocurrency/raiblocks#609]
Looks like it's affected by the same bug as Electrum...

<img src="https://i.imgur.com/5sxn4QZ.png" />

**Comment by PlasmaPower** [comment]
The RPC is:

1. not enabled for the wallet
2. secure by design - even with RPC access, an attacker couldn't do anything harmful (except maybe shut down your node or use it for work if `enable_control` is enabled)

**Comment by tnkmt** [comment]
On my node I typed these commands in order to be able to turn it off cleanly.

    sed -i 's/"rpc_enable": "false"/"rpc_enable": "true"/g' ~/RaiBlocks/config.json   
    sed -i 's/"enable_control": "false"/"enable_control": "true"/g' ~/RaiBlocks/config.json  

What I (or attacker) can do with the RPC in this case?

**Comment by PlasmaPower** [comment]
RPC documentation is here: https://github.com/clemahieu/raiblocks/wiki/RPC-protocol

**Comment by tnkmt** [comment]
If I understand correctly payments can be mane with an RPC.

**Comment by PlasmaPower** [comment]
Yes, but you need the wallet ID for that. An attacker couldn't guess that.

**Comment by tnkmt** [comment]
Is it safe to turn off the node with 'Ctrl+C' instead of using RPC call?

**Comment by PlasmaPower** [comment]
Yep. It'll shut down naturally that way. Just don't `pkill -9` it.

**Comment by tnkmt** [comment]
I figured out how to protect the daemon from browsers of other users:

    iptables -I OUTPUT -p tcp --dport 7076 -j REJECT
    iptables -I OUTPUT -p tcp --dport 7076 -m owner --uid-owner ONLY.THIS.USERNAME.IS.ALLOWED.TO-ACCESS.THIS.PORT -j ACCEPT

    ip6tables -I OUTPUT -p tcp --dport 7076 -j REJECT
    ip6tables -I OUTPUT -p tcp --dport 7076 -m owner --uid-owner ONLY.THIS.USERNAME.IS.ALLOWED.TO-ACCESS.THIS.PORT -j ACCEPT

Looks like it listens only on IPv6, but I am adding IPv4 rules just in case.

Of course the user running the daemon should not run browsers in order to be safe.
