### ISSUE TITLE
Block explorer issues

### ISSUE THREAD

**Issue by paulmelis** [nanocurrency/raiblocks#618]
(Not sure if this is the place for bugs of the explorer on nano.org, but reporting anyway)

The "Previous" and "Source" links to blocks are incorrect. They don't call up the page of the relevant block.
E.g. for https://nano.org/en/explore/block/7893C2A6F0286864F681E22042C8AF772926B2A392303BC02B96BE33678610B0 the Previous link in my Chrome has the URL https://nano.org/en/explore/block/7893C2A6F0286864F681E22042C8AF772926B2A392303BC02B96BE33678610B0#undefined, instead of https://nano.org/en/explore/block/F074E885EB8EDB902C1F1140084B0CE28608FF1B1A88D6C71E0968020EF0C286. There's a similar issue for a Source link.

Secondly, the labels for the different block values, like Balance and Work, get drawn in white (on a white background) when you hover over them or the associated value

**Comment by paulmelis** [comment]
Also, source and destination accounts get replaced by a well-known name when one is available. For example in https://nano.org/en/explore/block/848543E11923036E55EF717B32B4303BE14F74E25DB7CD7E912EB8329202584A the source is identified as "BitGrail Representative 2". But when you then click the name to go to the BG rep 2 account it no longer is identified with the know name. This would be a nice addition.

**Comment by rkeene** [comment]
Is this relevant now that nanode is the official block explorer ?

**Comment by icarusglider** [comment]
No, not relevant and was fixed just prior to the switchover.

**Comment by zhyatt** [comment]
Closing out as fixed
