### ISSUE TITLE
V10.0 macOS GUI - missing decimal separator

### ISSUE THREAD

**Issue by eirikrye** [nanocurrency/raiblocks#625]
The Mxrb unit displayed in the new V10.0 GUI wallet is 1e28 raw instead of the correct 1e30 raw.

Similarly, the kxrb unit is 1e25 raw instead of 1e27, and xrb displays as 1e22.

Either that, or it's supposed to display with 2 decimal points, but the decimal separator is missing :-)

Operating system: macOS

**Comment by androm3da** [comment]
Which locale are you using?

**Comment by eirikrye** [comment]
[~]$ defaults read -g AppleLocale
en_NO
[~]$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
[rye@vnfxa ~]$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

**Comment by eirikrye** [comment]
I tried changing to en_US in the region settings, but I am seeing the same issue.

This account has a balance of 8.65 NANO:

<img width="555" alt="screen shot 2018-02-15 at 10 47 37 pm" src="https://user-images.githubusercontent.com/597264/36282701-4b0d68fa-12a2-11e8-8e6b-6843cd7fc807.png">

**Comment by veltrop** [comment]
I'm having the same issue. It shows receives in kxrb, account total in kxrb, but sends in mxrb.

AppleLocale is en_US

$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

**Comment by renesq** [comment]
European style on Windows is just fine. Both triplet-grouping and decimal separator seem to be correct,  ![balance](https://user-images.githubusercontent.com/35303112/36285407-b51ba122-12ab-11e8-90e3-bff2a44d1286.png)  
BUT i can't send decimals anymore, neither dot or comma works. Only whole integers go through (in all unit settings). 
![senderror](https://user-images.githubusercontent.com/35303112/36286321-84916c04-12af-11e8-9176-96b7e644796c.png)

**Comment by dbachm123** [comment]
Fixed in https://github.com/nanocurrency/raiblocks/releases/tag/10.0.1 !?
