### ISSUE TITLE
Update Repository name, description, and url to Nano

### ISSUE THREAD

**Issue by Stormtv** [nanocurrency/raiblocks#627]
**Description of bug:**
Repository is currently called "raiblocks"

Topic line is "RaiBlocks is a cryptocurrency"

Website url for project is "http://raiblocks.net"

**Describe the results you expected:**
Repository should be called "nano"

Topic line should be "Nano is a cryptocurrency", maybe add key features of the cryptocurrency such as DAG / Block Lattice / Feeless / Instant

Website url for project should be "https://nano.org"

This should help with SEO when searching for nano source code / github

**Comment by marting87** [comment]
Something like this: 

 **Nano is a feeless, instant, high throughput cryptocurrency**

or:
 **Nano (formerly known as RaiBlocks) is a feeless, instant, high throughput cryptocurrency**

To clearify why the repo is called _raiblocks_
