### ISSUE TITLE
Formalize release process

### ISSUE THREAD

**Issue by androm3da** [nanocurrency/raiblocks#628]
We did `10.0` release and found some hiccups/speed bumps.  During this release cycle, many more developers were involved than were involved in previous releases.

We will need to formalize a process around releases, including steps, roles and responsibilities.

If we had to do a release in a hurry to fix a critical/widespread issue, we would probably face some challenges.  So near the top of our wishlist for release process should be to have a process that's as automated as possible.

**Comment by androm3da** [comment]
Among the roles needed is a Release Manager.  This will be someone who is executive/administrative, facilitating: (1) coordinating release content (rejecting/accepting appropriate features/fixes), (2) the actual steps of the release process itself, (3) preserving overall project schedule goals for releases.

If no one else prefers this role, I will nominate myself.

**Comment by androm3da** [comment]
Items to go in a release checklist:

- testing / evaluation procedures (beyond existing automated test suite)
- don't use the patch version number, just the major and minor
- expected tag format
- expected branching scheme for dev/releases

**Comment by rkeene** [comment]
There is now such a document internally, and it will eventually live on the wiki.
