### ISSUE TITLE
Fresh wallet does not create open block

### ISSUE THREAD

**Issue by stefonarch** [nanocurrency/raiblocks#638]
**Description of bug:**

**Steps to reproduce the issue:**
1.Starting nano_wallet with default configuration, export seed, close it, import a presynced ledger, sync and reimport seed
Same result importing a seed generated with 
`cat /dev/urandom |tr -dc '0-9A-F'|head -c${1:-64}
`
2.Send some amount to account(s)

**Describe the results you received:**
Funds never arrive and  blockexplorers says: "account not opened yet".

**Describe the results you expected:**
Account are opened on creation and funds are arriving.

**Additional information you deem important (e.g. issue happens only occasionally):**
Reproduced twice
**Environment**:
arch linux 64bit  
git build

**logs**
There are a lot of them, did a search with "open" , no results.
If necessary I can repeat the seed import.

**Comment by PlasmaPower** [comment]
Can your node see the send block? Go to advanced->block viewer and enter the hash.

Also, try advanced->search for receivables.

**Comment by stefonarch** [comment]
I was looking now at the blockexplorer, it seems that it was never sent. I'll test again.
The "open" block is kind of the first "receive" block?

**Comment by PlasmaPower** [comment]
Yep, exactly.

**Comment by stefonarch** [comment]
Ok, it happened while testing Canoe beta, and it did not broadcast probably because the desktop wallet eats all upload when synced, mentioned [here](https://github.com/nanocurrency/raiblocks/issues/533#issuecomment-366438163). Sorry for the noise, closing.
