### ISSUE TITLE
Slow sync/High memory usage

### ISSUE THREAD

**Issue by longfellowone** [nanocurrency/raiblocks#641]
Pulled latest docker image from nanocurrency/node. I assume this is the new v10 node?

4GB ram node running at 90% RAM usage, 2x CPU peaking at 70% usage. Been almost 48 hours and sync still not complete

"count": "4973818",
"unchecked": "1179423"

![image](https://user-images.githubusercontent.com/36570412/36343158-73ecfcd8-13bd-11e8-8655-e231e4bbbee6.png)

**Comment by Sovxx** [comment]
Same issue here, but on win10 64 with HDD

**Comment by terah** [comment]
Here is my node resource usage here - I updated to 10.0 on Sat 10AM in the timezone the graph is in.

![Resource graph](https://www.dropbox.com/s/eoy6xsaik2mye1y/Screenshot%202018-02-18%2013.12.53.png?dl=1)

**Comment by procrasti** [comment]
I think it is possible to cut down on the memory usage during bootstrap by flushing the unchecked cache more frequently.

I moved the flush code into the inner loop of rai::bootstrap_attempt::run, flushing every 1000 loops or so, and was able to get through the bootstrap with less than 1G of memory.

**Comment by rkeene** [comment]
Most of these issues will be resolved by lazy bootstrapping (#995), which will largely negate the need for an storing blocks that have not been validated on disk.

There are further improvements for network I/O, disk I/O, CPU utilization, and RAM utilization.

I am going to close this ticket so we can track the individual improvements directly.  Please let me know if you have any additional questions.
