### ISSUE TITLE
Build fails with "no match for call to ...distributed_work::stop()..."

### ISSUE THREAD

**Issue by dncohen** [nanocurrency/raiblocks#642]
**Description of bug:**

**Steps to reproduce the issue:**
Attempting to follow build instructions (https://github.com/nanocurrency/raiblocks/wiki/Build-Instructions)  - BTW on that page, `make rai_wallet` should be changed to `make nano_wallet`

**Describe the results you received:**
Build fails.  Here's the end of the `make`...

```
/home/user/raiblocks/rai/node/node.cpp:2149:6:   required from here
/home/user/raiblocks/beast/include/boost/beast/core/impl/handler_ptr.ipp:131:5: error: no match for call to ‘({anonymous}::distributed_work::stop()::<lambda()>::<lambda(const boost::system::error_code&, size_t)>) (boost::system::error_code&)’
     p_->handler(std::forward<Args>(args)...);
     ^~
/home/user/raiblocks/rai/node/node.cpp:2148:127: note: candidate: {anonymous}::distributed_work::stop()::<lambda()>::<lambda(const boost::system::error_code&, size_t)>
 , request, [socket](boost::system::error_code const & ec, size_t bytes_transferred) {
                                                                                   ^
/home/user/raiblocks/rai/node/node.cpp:2148:127: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [CMakeFiles/node.dir/build.make:135: CMakeFiles/node.dir/rai/node/node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:378: CMakeFiles/node.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Describe the results you expected:**
I've been able to build earlier versions in the past.  But can't currently build master or V10.0.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

```
uname -a
Linux devel-raiblocks 4.14.13-3.pvops.qubes.x86_64 #1 SMP Tue Jan 30 19:18:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**logs**

**Comment by clemahieu** [comment]
Are all your CMake boost related variables pointing to version 1.66?  I’ve had similar issues if they weren’t updated correctly and was mixing in an old version.

**Comment by dncohen** [comment]
I'm configuring cmake with 

```
cmake -DBOOST_ROOT=$BOOST_ROOT -DQt5_DIR=/usr/lib64/cmake/Qt5 -DRAIBLOCKS_GUI=ON -DACTIVE_NETWORK=rai_live_network
```

```
echo $BOOST_ROOT
/opt/boost_1_66_0
```

**Comment by androm3da** [comment]
Can you upload or paste the unabridged build log?

**Comment by dncohen** [comment]
[make.log](https://github.com/nanocurrency/raiblocks/files/1734107/make.log)

Sure redirected output to attached file.

**Comment by PlasmaPower** [comment]
I have no idea if this is the problem, but could you try `make clean` then `make build`?

**Comment by dncohen** [comment]
I get the same error after `make clean`.  I've tried that and even `git clean -d -f -x`

**Comment by paulmelis** [comment]
I think I had the same issue, which was related to having the beast submodule present in the nano source dir. Boost 1.66.0 has its own version of beast, which conflicts. Removing the beast subdir from the nano source dir and setting BOOST_CUSTOM (think that was what it’s called) to OFF fixed it for me.

**Comment by paulmelis** [comment]
This looks familiar: https://ripple.com/dev-blog/boost-1-66-not-supported-rippled-0-81-0/ :-)

**Comment by dncohen** [comment]
Nice catch @paulmelis , built smoothly after

```
rm -r beast
cmake -DBOOST_ROOT=$BOOST_ROOT -DBOOST_CUSTOM=OFF -DQt5_DIR=/usr/lib64/cmake/Qt5 -DRAIBLOCKS_GUI=ON -DACTIVE_NETWORK=rai_live_network
```

Then I run with

```
QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib64/qt5/plugins/platforms ./nano_wallet
```

Congrats on the Nano rebrand.  It's looking good.
