### ISSUE TITLE
unchecked block count increasing much more

### ISSUE THREAD

**Issue by stefonarch** [nanocurrency/raiblocks#645]
**Description of bug:**

Updated my node to v10 https://github.com/nanocurrency/raiblocks/releases/download/V10.0/rai-10.0.0-Linux.tar.xz

Unchecked block count has much increased, in 12 hours it's more than 3000, blocks are always synced +/- 5blocks

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

Linode server ubuntu 16.04 
1GB Ram
Single core Intel Xeon E5-2680 v3 (-MCP-) cache: 16384 KB bmips: 5001 speed: 2499 MHz (max)

**logs**
http://172.104.246.18/log1.txt
EDIT: added log

EDIT2: 24.feb I don't have this issue anymore, running 2 nodes unchecked blockcount is as before in low values.

**Comment by antesarkkinen** [comment]
Same problem here. 1GB DO droplet with v10 docker nanocurrency/nano. Block count: "count": "6218941", "unchecked": "1309" and increasing (up 7hrs).

**Comment by longfellowone** [comment]
Same here, lagging behind 4000 blocks and climbing. Using new v10 node from nanocurrency/nano

**Comment by stefonarch** [comment]
Added a log.

**Comment by renesq** [comment]
Being in sync while still having a display of multiple unchecked blocks seems a common bug. It may have to do with an inconsistency in node.store.unchecked (especially _unchecked_count_)

**Comment by tkek55** [comment]
same issue here, are u using rai-10.0.0-Linux.tar.xz ?

**Comment by matheus23** [comment]
Same issue here, using v10.0.1 compiled from commit a73ad375a8ac76b94aac735f06d4e6f7b402f91e and rebootstrapped the database.

Had 120k unchecked blocks. Restarting the node seems to reduce the count again.

**Comment by dbachm123** [comment]
I am observing the same issue. Compared to v9, the absolute number of unchecked blocks is comparable after a couple of hours, but the v10 node seems to lag behind significantly. After 24h my v10 node was approx. 8000 blocks behind  in terms of block height ( RPC current block) than other nodes on the web (nanode, nanowatch, etc. ). RPC „clear_unchecked“ or restarting the node fixes that issue immediately. When the node is lagging behind I am also seeing constant 280 MBytes/s. disk I/O.

**Comment by stefonarch** [comment]
Could it be that it depends on network situation? At the moment in half a day my unchecked count is 14 only.

**Comment by dbachm123** [comment]
Maybe, but I did not see a similar pattern with v9. At the time of this post, the block height reported by nanode.co and nanowat.ch differs by approx. 3000 blocks as well ...

**Comment by stefonarch** [comment]
Overnight 2000 unchecked blocks and ~5000 behind, nanowat.ch and nanode.co differ ~6000 at time of writing. Sunday evening evening was even worse, I saw ~10'000 differences with nanowat.ch at the low side, restarted mine it climbed slowly up (as it does now after  a restart). But testing a fresh block on nanowat.ch it showed the right info.
I'll use cron for restart every 6 hours I think for the moment.
.

**Comment by elliottneilclark** [comment]
I'm seeing this as well. 7k unchecked blocks.

**Comment by stefonarch** [comment]
Made an edit, it's a week now that I don't see it anymore.
