### ISSUE TITLE
Can't properly regenerate deterministic keys/accounts after wallet seed import

### ISSUE THREAD

**Issue by micronano** [nanocurrency/raiblocks#648]
**Description of bug:**
I am having a hard time re-generating multiple addresses from a single wallet seed. I am using the dockerized image for v10.0.

**Steps to reproduce the issue:**
1. Create a wallet ({{wallet1}})
`./rai_node --wallet_create`

2. Create 3 accounts for the wallet (take note of the addresses) [{{account_1}}, {{account_2}}, and {{account_3}}]
`./rai_node --account_create --wallet={{wallet1}}`

3. Export the wallet seed ({{wallet1_seed}})
`./rai_node --wallet_decrypt_unsafe --wallet={{wallet1}}`

4. Destroy the wallet
`./rai_node --wallet_destroy --wallet={{wallet1}}`

5. As there is no documented way to create a wallet directly from the seed, I first create a new wallet  ({{wallet2}}) and then change its seed to that of the first wallet
`./rai_node --wallet_create
./rai_node --wallet_change_seed --wallet={{wallet2}} --key={{wallet1_seed}}`

6. Create 3 accounts for the new wallet
`./rai_node --account_create --wallet={{wallet2}}`

7. Compare the resulting 3 addresses with the ones obtained at step 2

**Describe the results you received:**
At step 6, I get {{account_2}} and {{account_3}}, but not {{account_1}}. The third account appearing is probably the account following {{account_3}} in the sequential order. 

**Describe the results you expected:**
Getting all three accounts obtained in step 2.

**Additional information you deem important (e.g. issue happens only occasionally):**
Am I doing something incorrectly? I know that I could import {{account_1}} as an adhoc key, but ideally I'd rather want to only have to back up my wallet seed.

Maybe the index number used for determining the next deterministic key might not be correctly reset when changing the wallet's seed?

Alternatively, si there a documented way to directly import the seed, without having to create a new account and later changing its seed?

**Environment**:
Dockerized image grabbed 1 hour ago on a MacOS system

Thanks for all the great work!

**Comment by comeback** [comment]
I experienced this same issue, but in node v9.0.  Have not tried v10.

**Comment by paulmelis** [comment]
Account recreation seems to work for me with version 10.0:
```
[testnano@llt0022 bin]$ ./rai_node --wallet_create
478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20

[testnano@llt0022 bin]$ ./rai_node --account_create --wallet=478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20
Account: xrb_1ufo9qm7wqty7t9cgwcdhgox6e53q9sytks6qqb66w4cxwgy5ctyitqqe6kd
[testnano@llt0022 bin]$ ./rai_node --account_create --wallet=478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20
Account: xrb_1ssbursi8ktzhzosq3g4rqkxmmzcq8c1cfhjxac3ka9nhxbtre3hnppebmir
[testnano@llt0022 bin]$ ./rai_node --account_create --wallet=478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20
Account: xrb_3zw7niu5u5aqng6eda9uccq8yxkr3rikymtopzezenwcew5pmij13rps9ss3

[testnano@llt0022 bin]$ ./rai_node --wallet_list
Wallet ID: 478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20
xrb_1ssbursi8ktzhzosq3g4rqkxmmzcq8c1cfhjxac3ka9nhxbtre3hnppebmir
xrb_1ufo9qm7wqty7t9cgwcdhgox6e53q9sytks6qqb66w4cxwgy5ctyitqqe6kd
xrb_3zw7niu5u5aqng6eda9uccq8yxkr3rikymtopzezenwcew5pmij13rps9ss3

[testnano@llt0022 bin]$ ./rai_node --wallet_decrypt_unsafe --wallet=5BC7788CB360BDCFAC9F9C484790223FED3C2F4EDDD292AED6F05AA0236D27CD
Seed: BBF26A68806DEB8E1CCB1DE1E7F1632274F92157C096D0912C6FE327F6DA85B2
Pub: xrb_1ssbursi8ktzhzosq3g4rqkxmmzcq8c1cfhjxac3ka9nhxbtre3hnppebmir Prv: DB69DF118587D4B647A18B4C570A785EB2BB46BF8F5340CBD52099F7F52F7E96
Pub: xrb_1ufo9qm7wqty7t9cgwcdhgox6e53q9sytks6qqb66w4cxwgy5ctyitqqe6kd Prv: EB2DAAB4D49686EB7D48D9B84E6FE01DAF9EAEEE8FC3D41905B3EB613AB7A206
Pub: xrb_3zw7niu5u5aqng6eda9uccq8yxkr3rikymtopzezenwcew5pmij13rps9ss3 Prv: 62DEE59B9E9FAE90FC04AB96ACF25E9BC18CAD00FC5AE6678B5DD6722B8852F9

[testnano@llt0022 bin]$ ./rai_node --wallet_destroy --wallet=478A0DA0F24EFC1CF0F67BF8399D7FED993BF27481C50773A000B56A6026BC20
[testnano@llt0022 bin]$ ./rai_node --wallet_list
[testnano@llt0022 bin]$ ./rai_node --wallet_create
2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4

[testnano@llt0022 bin]$ ./rai_node --wallet_change_seed --wallet=2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4 --key=BBF26A68806DEB8E1CCB1DE1E7F1632274F92157C096D0912C6FE327F6DA85B2
[testnano@llt0022 bin]$ ./rai_node --wallet_list
Wallet ID: 2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4
xrb_1ufo9qm7wqty7t9cgwcdhgox6e53q9sytks6qqb66w4cxwgy5ctyitqqe6kd

[testnano@llt0022 bin]$ ./rai_node --account_create --wallet=2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4
Account: xrb_1ssbursi8ktzhzosq3g4rqkxmmzcq8c1cfhjxac3ka9nhxbtre3hnppebmir

[testnano@llt0022 bin]$ ./rai_node --account_create --wallet=2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4
Account: xrb_3zw7niu5u5aqng6eda9uccq8yxkr3rikymtopzezenwcew5pmij13rps9ss3

[testnano@llt0022 bin]$ ./rai_node --wallet_list
Wallet ID: 2A6EB0FAC646C7B6884340CA21A7A6000A95B8C00988BD291ED23538E481E9D4
xrb_1ssbursi8ktzhzosq3g4rqkxmmzcq8c1cfhjxac3ka9nhxbtre3hnppebmir
xrb_1ufo9qm7wqty7t9cgwcdhgox6e53q9sytks6qqb66w4cxwgy5ctyitqqe6kd
xrb_3zw7niu5u5aqng6eda9uccq8yxkr3rikymtopzezenwcew5pmij13rps9ss3
```
