### ISSUE TITLE
Inconsistency in the block explorer

### ISSUE THREAD

**Issue by paulmelis** [nanocurrency/raiblocks#651]
On [this account](https://nano.org/en/explore/account/xrb_13ezf4od79h1tgj9aiu4djzcmmguendtjfuhwfukhuucboua8cpoihmh8byo) the first block listed, [D7C6604C37F23F05D4A98A365DB5B91EFFBEAD3E851EC4A49F579BBB8E88CFF1](https://nano.org/en/explore/block/D7C6604C37F23F05D4A98A365DB5B91EFFBEAD3E851EC4A49F579BBB8E88CFF1), has type "not pocketed". But clicking through to the page for that send block lists it as "Pocketed yes".

**Comment by paulmelis** [comment]
https://nano.org/en/explore/account/xrb_3o3499zpcbfqroo7x4r55pgzofr6ndid7twd7pkqpwwnkqxugbppoqq57y7t shows sends to xrb_1niabkx3gbxit5j5yyqcpas71dkffggbr6zpd3heui8rpoocm5xqbdwq44oh, but the page for that account shows no transactionsm but also no pending deposits.

**Comment by kidandcat** [comment]
It shows well to me, maybe it needed time to refresh?

<img width="1217" alt="screen shot 2018-02-20 at 09 26 06" src="https://user-images.githubusercontent.com/3855826/36413785-25170440-1620-11e8-8162-fee7ef49a343.png">

**Comment by paulmelis** [comment]
That's not what I meant. The block `D7C...` indeed says it's pocketed, but looking at the same block for the account it lists that block as "not pocketed".

![untitled](https://user-images.githubusercontent.com/1408287/36421286-319be740-1638-11e8-960c-e554e8f419cd.png)

**Comment by icarusglider** [comment]
There can be some variance in results at times. The backend of our site load balances between 4 nodes and sometimes one falls behind. Im working to ensure consistency is maintained automatically.
