### ISSUE TITLE
New account not directly visible in list 

### ISSUE THREAD

**Issue by paulmelis** [nanocurrency/raiblocks#656]
**Description of bug:**

I synced a fresh database with nano_wallet and then imported an existing wallet with my seed. This all worked and showed the single account I was using so far. But when I then add an account it does not show up in the list under Accounts. Only after a restart of nano_wallet does it appear. 

Not sure if the fresh installation matters here. I'd rather not add more accounts to test this as you can't remove them.

**Steps to reproduce the issue:**
1. Fresh installation of nano_wallet, including sync
2. Accounts -> Import wallet, enter seed, Import seed
3. Under Settings set password
4. Make sure account is unlocked 
5. Accounts -> Create account

**Describe the results you received:**

New account not visible under Accounts

**Describe the results you expected:**

All accounts visible under Accounts

**Environment**:

Arch Linux, git 8840c9dbefb72aef255744fd5157695201511195

**Comment by mihaifm** [comment]
I can confirm this, it's an obvious bug.
