### ISSUE TITLE
v10.0.1 node never fully syncing

### ISSUE THREAD

**Issue by bkilshaw** [nanocurrency/raiblocks#657]
**Description of bug:**

I am unable to get my node to fully sync. I have re-started the process 5 times on two different servers and have experienced the same issue on both. It seems to grind to a halt around 2,500,000-2,800,000 blocks. 

Both systems are running on Linode 2GB nodes (2GB ram, 1 CPU core, 30GB SSD Storage) and running on Ubuntu 16.04.

I did not experience any issues running a v9 node, although that one I manually built following [this guide](https://github.com/nanocurrency/raiblocks/wiki/Install-Wallet-on-Ubuntu-16.04.3) (which did not work last time I attempted to follow since the v10 launch, it appears the guide has been updated since)

**Steps to reproduce the issue:**
I actually wrote a guide on how to get a node up and running on the wiki. These are the exact steps I have followed: [https://github.com/nanocurrency/raiblocks/wiki/Guide:-Quickstart-to-running-a-node-(Ubuntu-16.04)](https://github.com/nanocurrency/raiblocks/wiki/Guide:-Quickstart-to-running-a-node-(Ubuntu-16.04))

**Describe the results you received:**
The node sync process grinds to a halt once it gets around 2.5-2.8 million blocks in, syncing one block every few minutes.

**Describe the results you expected:**
The node to fully sync in a reasonable amount of time.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have run this process on two separate servers, and restarted the syncing process on both, the issue happens consistently.

**Environment**:
***Node Config***
[https://gist.github.com/bkilshaw/0fff7163b32e729be99c9c423f0b09b8](https://gist.github.com/bkilshaw/0fff7163b32e729be99c9c423f0b09b8)
***Linux Release***
````
:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
````
***Kernel***
````
:~$ uname -a
 Linux localhost 4.14.17-x86_64-linode99 #1 SMP Tue Feb 6 19:09:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
````
***Node Version***
````
:~$ rai_node --version
Version 10.0
````
**logs**
[https://gist.github.com/bkilshaw/cff7bbc349c2fe56e12109575bd29ee8](https://gist.github.com/bkilshaw/cff7bbc349c2fe56e12109575bd29ee8)

**Comment by stefonarch** [comment]
I set up the same  linode dual core  but this time with an arch linux image and was able to sync in 2-3 hr, thought it was CPU that helped. On the ubuntu node 1 core I was never able to full sync.

**Comment by bkilshaw** [comment]
Hm, curious if it is the CPU. I'll set up a beefier machine and see if it makes a difference.

**Comment by bkilshaw** [comment]
Set up a new VPS earlier today and it appears the 2 core system synced fine. All previous tests were single core machines.

Didn't Work => Linode 2GB: 2GB Ram, 1 CPU Core, SSD storage
Working => Linode 4GB: 4GB Ram, 2 CPU cores, SSD Storage
