### ISSUE TITLE
CMake Error at CMakeLists.txt:155 (add_subdirectory)

### ISSUE THREAD

**Issue by iljah** [nanocurrency/raiblocks#658]
**Steps to reproduce the issue:**
1. git clone ...
2. ...
3. cmake .. -DRAIBLOCKS_GUI=ON -DBOOST_ROOT=/usr/local

**Describe the results you received:**

CMake Error at CMakeLists.txt:155 (add_subdirectory):
  add_subdirectory given source "miniupnp/miniupnpc" which is not an existing
  directory.

the miniupnp directory in root of git repo is empty, there is no miniupnp in build directory

**Describe the results you expected:**
No error

cmake version 3.9.1 on fedora 25.

**Comment by SergiySW** [comment]
In build directory
```
git submodule init  
git submodule update
```
Or use git clone --recursive
https://github.com/nanocurrency/raiblocks/wiki/Build-rai_node-samples#building-rai_node

**Comment by iljah** [comment]
Oh right, I forgot about --recursive. After some googling there doesn't seem to be a way in cmake to detect whether add_subdirectory failed to print a more useful error. But some kind of check that submodules have been cloned would be nice.
