### ISSUE TITLE
Qt5 not found

### ISSUE THREAD

**Issue by bernhard-h** [nanocurrency/raiblocks#671]
I ran into a problem when starting the nano_wallet on linux. I get following error:

`./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version Qt_5.9 not found (required by ./nano_wallet)`
`./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version Qt_5 not found (required by ./nano_wallet)`
`./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version Qt_5 not found (required by ./nano_wallet)`
`./nano_wallet: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version Qt_5 not found (required by ./nano_wallet)`

I have Qt5 already installed but nano_wallet doesn't detect it.

**Comment by john-oberhauser** [comment]
did you get this to work?

**Comment by bernhard-h** [comment]
I installed version 9 which works fine.
