### ISSUE TITLE
Wallet gives increased NANO value when sending multiple transactions

### ISSUE THREAD

**Issue by timothybeansdoor** [nanocurrency/raiblocks#675]
**Description of bug:**
Wallet gives increased NANO value when sending multiple transactions. I can provide a video if it helps.

 

When sending multiple NANO transactions very quickly (several transactions within 1 minute) to the same address with the same NANO value to be sent, the NANO amount in the sending wallet increases by a single digit NANO value with each new transaction sent.

**Steps to reproduce the issue:**
1. send multiple transations of NANO to the same address very quickly (I was sending 0.1 NANO about 15 times in 1 minute). I was sending to specifically a Kucoin wallet from a web wallet (https://nanowallet.io/)
2. when you continue to send multiple transactions with each transaction the NANO value of your wallet increases (I was using the nanocurrency browser based wallet)
3. After logging out the NANO value returns to normal, so it may be a cosmetic error in the wallet

**Describe the results you received:**

Increased NANO value in wallet that is sending

**Describe the results you expected:**

To send NANO to another recieving wallet

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by androm3da** [comment]
You are using a web wallet?  Can you share the precise URL to this web wallet?

**Comment by timothybeansdoor** [comment]
https://nanowallet.io/

**Comment by androm3da** [comment]
That web wallet claims to offer support via  support@nanowallet.io

Could you try that first?  If that doesn't work, we will see if we can help get in touch.  Please reopen this issue if you need more help.

**Comment by PlasmaPower** [comment]
They have a GitHub repository. Please file the but there.
