### ISSUE TITLE
Xrb_Tip_Bot bug

### ISSUE THREAD

**Issue by AnalogOrange** [nanocurrency/raiblocks#678]
Xrb_Tip_Bot on Discord-Trading
Bug

It is possible to send a big load of small tips to another user,
Example: !tip 1 @colmy  (You can duplicate the tag for more individual tips or copy the whole tip message)

If you do this 100 times or more the tipbot wallet of th receiver will crash.
This means if you'd tip that person after, the XRB_TIP_BOT will confirm your tip,
But the recipient wont receive the tipped amount and xrb_tip_bot will not confirm to the receiver he or she got a tip.
The tipped amount will then stay in the tippers wallet.

**Comment by jamescoxon** [comment]
This is fixed in a recent update (due to poor implementation of the spam limit by myself) - this issue can be closed
