### ISSUE TITLE
Sign the hash of the message instead the message

### ISSUE THREAD

**Issue by Inkeliz** [nanocurrency/raiblocks#693]
The Ed25519 already does a hashing. But instead of simple HASH(M), the Ed25519 does something like HASH(R + PubK + M), basically. This behavior makes the Ed25519 secure, claim to have a “Collision resilience”, it was described in the paper, http://ed25519.cr.yp.to/ed25519-20110926.pdf:

> Hash-function collisions do not break this system. This adds a layer of defense against the possibility of weakness in the selected hash function.

The Nano chooses, without any good reason, to pre-hashing the value of M. In this situation the Ed25519 can’t prevent a collision, because the message is the hash itself. This already know and described in http://ed25519.cr.yp.to/eddsa-20150704.pdf.

We have other source of information, one of them can be [this post](https://crypto.stackexchange.com/questions/55481/does-hash-than-sign-paradigm-apply-to-ecdsa-cryptography) in the Crypto SE:
> You do not have to hash the inputs to Ed25519 because hashing is already part of Ed25519 itself. If you do hash inputs in advance, you become vulnerable to collisions in the hash function you use.

If some vulnerability was found in Blake2, the collision of the signature can happen, since the signature is only the hash, not the content.

It not seems to be a major problem, because the Blake2 is secure, one of the requirement of a hashing functions is to be secure against collision. However, the Nano don’t have any advantage doing the pre-hashing, since the message is already short. Instead we have a disadvantage of "losing one security layer".

---------------------------

I really want to know why Nano/Raiblocks chooses to pre-hashing, or it was just an arbitrary decision of the developer. I already told about it with two members of the _Core Team_, none of them could explain why.

**Comment by PlasmaPower** [comment]
Nano already relies on there being no hash collisions. For example, hashes are used for `previous` and `source` fields. The whole database is built around hashes for lookups. Hashes are fundamental to any cryptocurrency, and making the signatures resistant would solve little.

**Comment by Inkeliz** [comment]
Why it's closed without any explanation?

If the signature already have a hash inside, why do it twice? Also, why relies on the hash of the block since the signature of the hashable is also a hash?!

**Comment by PlasmaPower** [comment]
This may be a better way to do it, but there's little reason to change. Our decision at this time is to keep things how they are.

**Comment by clemahieu** [comment]
Can you code up the change and make a pull request?

**Comment by PlasmaPower** [comment]
Not really possible, all the current hashes are based on the "double hash" method so the whole block lattice depends on it.

**Comment by clemahieu** [comment]
The only thing I can think of is to check both the new and old signing style but that degraded performance in the bad signature case.
