### ISSUE TITLE
docker -- RCP callback does not perfect working in "curl" command  beacuse incomplete output file 

### ISSUE THREAD

**Issue by AlexAtBJ** [nanocurrency/raiblocks#703]
Nano docker using the curl command call RPC Protocol "accounts_create" method and TXT output to a file, but Linux process will be stuck, do you have any other way to create accounts address batch or able to write file to the newly created account to use other commands instead of curl command, is the number of account address to create the scene the address is 10000.

response output still in process but daemon have complete the job in docker. 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 11  742k   11 86667    0   124    564      0  0:22:27  0:02:33  0:19:54

**Comment by paulmelis** [comment]
How long did you wait for the 10,000 accounts to be created? It might take quite a bit of time depending on the value of the `work` parameter in the RPC call.

**Comment by argakiig** [comment]
See https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#accounts-create
You can disable the work generation by setting work to false
