### ISSUE TITLE
RCP suggestion: Ability to find out which wallet an account belongs to

### ISSUE THREAD

**Issue by lukes** [nanocurrency/raiblocks#706]
Hi, 

I'd like to be able to find out which wallet an account belongs to using the RPC. This would be useful for a Ruby library I'm writing, which would allow me to ask the user to provide just their account hash and I could use that to lookup the wallet hash for successive commands.

Thanks!
Luke

**Comment by alexbakker** [comment]
This would break the 'security' of this RPC system. Wallet ID's are used as API keys.

**Comment by lukes** [comment]
I see, thank you, yes you're right. Closing.
