### ISSUE TITLE
Wallet crashes without sudo rights on Ubuntu 17

### ISSUE THREAD

**Issue by mihaifm** [nanocurrency/raiblocks#718]
Running nano_wallet without `sudo` results in an `Aborted (core dumped)` crash on Ubuntu 17.

**Comment by PlasmaPower** [comment]
Duplicate of #124

There's another solution there.

**Comment by mihaifm** [comment]
Thanks. It seems like the crash occurred because I was connected to the machine via xrdp, which is using xorg for display. 
It doesn't occur when logging in normally on the machine. Setting GDK_BACKEND=x11 also solves the problem. I can update the wiki in case someone encounters a similar issue.
