### ISSUE TITLE
"Create account" with locked wallet

### ISSUE THREAD

**Issue by HostFat** [nanocurrency/raiblocks#73]
If the wallet is locked, change the text for 5 seconds to something like this:
"Wallet is locked, unlock it to enable creating a new account"
Then, after the 5 seconds, change the text back to "Create account"

**Comment by riztinejoy19** [comment]
how to create account in raiblock?

**Comment by chelly13** [comment]
How to create account in raiblock?

**Comment by SergiySW** [comment]
https://github.com/clemahieu/raiblocks/commit/e9145669594dac115d2bae38952521f97e8fb82e
