### ISSUE TITLE
UTX callback: Link field is always base32-encoded, even if referencing a block hash

### ISSUE THREAD

**Issue by renesq** [nanocurrency/raiblocks#734]
I find the RPC callback behavior a little odd. Block hashes in the Link field get encoded with base32. 

E.g. Beta network's block `711366594E5E8D17AA1340CEC4D2C7A354F23179DA6E5CEB7C88FEABEED6D043` is a UTX-style receive block, so the Link field references the sender block hash, but RPC callback sends ` \"link\": \"xrb_3u7go5p597us1eieg7un3t44rcpmnuunztgoxfxcyag48pozpzzkmfue3r8j\"` instead, so you have to decode it first in order to get the block hash `ECAEA8EC3397790320C717740E842C2AD3A6F74FE9D5EB7AAF21C235ABFB7FF2`. 

Is this really intentional? I see more reasons against this behavior than in favor of it.

**Comment by PlasmaPower** [comment]
That's because for send utx blocks, link is an account (the destination). Perhaps we should have two fields, `link` and `link_account`. Serializing the block would provide both, while deserializing would only use one.

**Comment by clemahieu** [comment]
Yea this is the result of this field either being an account or a hash and if it's an account we really only want it handled in account format with xrb_ and the checksum.

Putting two fields when serializing to json would be an option.

**Comment by renesq** [comment]
Splitting the serialization is a feasible option. But even using the same field for differently encoded content should work, since hashes are the same length as addresses and only use a slightly different charset (hashes contain 0s and 2s). 

Another food for thought:
If I only make a rep change, does the `link` field show the burn account or is it blank? I know the UTX block type has some trade-offs but we should make callback user-friendly nonetheless. The `is_send` field is a good start. I'm fully aware that you can't specify an exact block type anymore, because one block can contain multiple operations at the same time, like a concurrent send&rep-change.

**Comment by renesq** [comment]
Great, now we at least don't need a blake2b library for processing the callback data anymore, so I closed the issue. Also, when building blocks manually, you need the library anyway, so it doesn't really matter for that use-case. 

The added field will bloat the callback by about 10%, but if TCP bandwidth savings were severe, we could fine-tune many other parameters as well (e.g. leaving unnecessary UTX fields blank in the json instead of 0000ing them).
