### ISSUE TITLE
"Wallet not found" whilst using RPC send action

### ISSUE THREAD

**Issue by Radioz028** [nanocurrency/raiblocks#738]
I can't find any detailed information online; what does this error message mean and how do I solve it? I made the following RPC call:
`{
    "action": "send",
    "wallet": <seedFromSendAccount>,  
    "source": <addressFromSendAccount>,
    "destination": <addressFromReceiveAccount>,
    "amount": "1000000",
    "id":"tx-99999"
}`

And all it returned was:
`{"error":"Wallet not found"}`

I am on Windows running the wallet as a node. I have rpc_enable and allow_control both true. Other RPC functions seem to work fine, I can view account_info for both addresses using RPC and both of them have balances with a history of transactions.

My node's version is:
`{'rpc_version': 1, 'store_version': 10, 'node_vendor': 'RaiBlocks 9.0'}`

Would anybody be able to point me in the right direction? I just need to know what "Wallet not found" means. Thanks.

**Comment by argakiig** [comment]
The wallet is not your seed, if you check the config.json it will tell you the wallet id. Also check the rpc and cli options to list the wallets and addresses
