### ISSUE TITLE
Send RPC command

### ISSUE THREAD

**Issue by i3bitcoin** [nanocurrency/raiblocks#740]
Sometimes Send RPC command doesn't return BLOCK HASH.
It's not good for merchants.. Did anyone face such issue?

Version 10.0.1

**Comment by PlasmaPower** [comment]
What did it return instead?

**Comment by i3bitcoin** [comment]
Returns nothing, even without Error flag.

**Comment by PlasmaPower** [comment]
Nothing as in an empty JSON object or no response at all?

**Comment by i3bitcoin** [comment]
I suppose an empty object, will check once again.

**Comment by i3bitcoin** [comment]
Yes, returns empty JSON object after some delay (3-5 sec.)

**Comment by SergiySW** [comment]
With plain CURL?

**Comment by i3bitcoin** [comment]
Omg... my fault guys... thanks for a quick help. Timeout was set to 5 sec in curl.
Sorry.
