### ISSUE TITLE
Huge outgoing bandwidth increase (up to 100x times) after implementing universal blocks

### ISSUE THREAD

**Issue by nageneril** [nanocurrency/raiblocks#743]
I run a node on a VPS and have been closely monitoring its bandwidth usage since the beginning of February 2018. I'm pretty sure that bandwidth usage is the main nano's scalability issue and its main bottleneck. I use vnstat for this and also my hosting provider has some graphs in the control panel. I regularly compile rai_node from github source. 

Before my rai_node build on Feb 7 2018 there were some bandwidth fluctuations, but since then the bandwidth usage stabilized and was about 3Mbps per 1tx/sec on average throughout all github commits since (I compiled from source once in several days). It was so until Mar 18 2008 when after another regular build (previous was on 5 Mar) I noticed that outgoing traffic increased 100x times! Incoming traffic almost didn't change. I recompiled on Mar 20 and Mar 21.  Outgoing bandwidth decreased but is still 15-50 times higher than before. Why it is so? What in the latest commits is responsible for such a dramatic rise?

Conclusion: if universal blocks means 2 times less ledger size but 20 times more bandwidth then we definitely don't need universal blocks. Even if it means 2 times less ledger size and only 2 times bandwidth increase we still don't need them. Bandwidth is much more expensive than disk size.

My biggest hope that this bandwidth issue is merely temporary and can be fixed. But if bandwidth increase is a necessary requirement for implementing universal blocks then we definitely don't need them.
Some graphs and numbers:
vnstat output:
![image](https://user-images.githubusercontent.com/32071293/37692068-0994be46-2cbf-11e8-9eba-f63c6c10015e.png)
Hosting provider control panel chart:
![image](https://user-images.githubusercontent.com/32071293/37692223-fb27daf4-2cbf-11e8-962b-2edc4f14ee10.png)
Node outgoing traffic per 1tx/sec
![image](https://user-images.githubusercontent.com/32071293/37692106-514895aa-2cbf-11e8-8219-73b07be0419d.png)

**Comment by clemahieu** [comment]
Unlocks themselves don’t need more bandwidth, and no unlocks on live are generated. We did some other changes that are more likely to affect network usage so we’ll take a look.

**Comment by nageneril** [comment]
It's very good news it's not connected with unlocks. Looking forward to knowing what causes this huge increase.

**Comment by termhn** [comment]
We've received a couple other accounts of similar increase but yeah as Colin said, it's not due to ublocks (now state-blocks) themselves. In fact, there have been very few if any state blocks actually transmitted so far.

**Comment by cryptocode** [comment]
@nageneril there is a fix for this on master

**Comment by nageneril** [comment]
Just rebuilt from the latest source. Yes, bandwidth decreased, but my first impression is that it's not a complete fix because outgoing bandwidth still stays 2 times higher than before the changes and incoming increased as well. But that's just after a couple of hours of observation. Need to wait some more time to make a final conclusion.

**Comment by nageneril** [comment]
Now some time has passed and I can definitely say that the fix is not complete. Outgoing traffic is more than 4 times higher than before version 11. That's terrible. What exactly is the cause?
 Here's a chart:
![image](https://user-images.githubusercontent.com/32071293/37872252-d79d8826-3003-11e8-936f-5c15703695de.png)

**Comment by dbachm123** [comment]
Here's another data sample. Update to v11 was on 03/23/2018. Outbound traffic has increased significantly; inbound traffic seemed to have decreased. Total is roughly the same as before.

```
eth0  /  daily

         day         rx      |     tx      |    total    |   avg. rate
     ------------------------+-------------+-------------+---------------
     03/06/2018    52.23 GiB |   11.53 GiB |   63.76 GiB |    6.19 Mbit/s
     03/07/2018    45.04 GiB |    9.65 GiB |   54.68 GiB |    5.31 Mbit/s
     03/08/2018    46.73 GiB |    8.26 GiB |   54.99 GiB |    5.34 Mbit/s
     03/09/2018    43.22 GiB |    8.76 GiB |   51.98 GiB |    5.05 Mbit/s
     03/10/2018    39.79 GiB |   10.35 GiB |   50.15 GiB |    4.87 Mbit/s
     03/11/2018    47.38 GiB |    7.08 GiB |   54.46 GiB |    5.29 Mbit/s
     03/12/2018    52.47 GiB |    8.13 GiB |   60.60 GiB |    5.88 Mbit/s
     03/13/2018    44.15 GiB |    7.74 GiB |   51.89 GiB |    5.04 Mbit/s
     03/14/2018    33.14 GiB |    7.37 GiB |   40.51 GiB |    3.93 Mbit/s
     03/15/2018    28.01 GiB |    7.32 GiB |   35.33 GiB |    3.43 Mbit/s
     03/16/2018    51.46 GiB |    6.45 GiB |   57.91 GiB |    5.62 Mbit/s
     03/17/2018    52.77 GiB |    5.62 GiB |   58.39 GiB |    5.67 Mbit/s
     03/18/2018    37.41 GiB |    7.37 GiB |   44.78 GiB |    4.35 Mbit/s
     03/19/2018    44.64 GiB |    6.95 GiB |   51.59 GiB |    5.01 Mbit/s
     03/20/2018    49.76 GiB |   16.12 GiB |   65.88 GiB |    6.40 Mbit/s
     03/21/2018    47.00 GiB |   20.95 GiB |   67.94 GiB |    6.60 Mbit/s
     03/22/2018    41.34 GiB |   18.69 GiB |   60.03 GiB |    5.83 Mbit/s
     03/23/2018    37.30 GiB |   15.08 GiB |   52.38 GiB |    5.09 Mbit/s
     03/24/2018    44.32 GiB |   14.11 GiB |   58.42 GiB |    5.67 Mbit/s
     03/25/2018    10.79 GiB |   21.05 GiB |   31.84 GiB |    3.09 Mbit/s
     03/26/2018    15.58 GiB |   32.35 GiB |   47.93 GiB |    4.65 Mbit/s
     03/27/2018    13.53 GiB |   26.90 GiB |   40.43 GiB |    3.93 Mbit/s
     03/28/2018    11.40 GiB |   23.31 GiB |   34.70 GiB |    3.37 Mbit/s
     03/29/2018    10.94 GiB |   21.40 GiB |   32.33 GiB |    3.14 Mbit/s
     03/30/2018    15.68 GiB |   32.76 GiB |   48.44 GiB |    4.70 Mbit/s
     03/31/2018    16.62 GiB |   36.18 GiB |   52.79 GiB |    5.13 Mbit/s
     04/01/2018    23.43 GiB |   49.06 GiB |   72.49 GiB |    7.04 Mbit/s
     04/02/2018    23.99 GiB |   51.64 GiB |   75.63 GiB |    7.34 Mbit/s
     04/03/2018    16.74 GiB |   30.97 GiB |   47.71 GiB |    4.63 Mbit/s
     04/04/2018    16.67 GiB |   38.02 GiB |   54.69 GiB |    6.11 Mbit/s
     ------------------------+-------------+-------------+---------------
```

**Comment by argakiig** [comment]
Go ahead and upgrade to the latest release please and let us know how it changes

**Comment by dbachm123** [comment]
Already updated :)

**Comment by argakiig** [comment]
and no noticeable improvement or how are the stats since 11.2?

**Comment by dbachm123** [comment]
I am seeing a very similar pattern in my bandwidth data.

**Comment by clemahieu** [comment]
There were some changes from 10 -> 11 that increase vote relaying that could cause higher traffic but I don't know of any changes from 11.1 -> 11.2 that would cause a bandwidth increase besides network conditions.

Do you know if the traffic increase is TCP or UDP?  Would you be able to turn bootstrap_connections_max down to maybe 16 or 8 and see if that affects your bandwidth?

**Comment by stefonarch** [comment]
Asked to jump in, my first impression was that 11.2 did bring more traffic but also more CPU usage.
The graph, one node I updated some hour ago:
![ubuntuff](https://user-images.githubusercontent.com/10681413/38443624-9fb1db86-39ec-11e8-9621-913758adcfaf.png)

Here ipv6 and ipv4 from the other node, update is the white space ~4 days ago:
![tokyoipv6](https://user-images.githubusercontent.com/10681413/38443645-b839cc04-39ec-11e8-9ef1-211e63aed19a.png)
![tokyoip4](https://user-images.githubusercontent.com/10681413/38443646-b856eb36-39ec-11e8-9a4a-ce4888cd2169.png)

**Comment by nageneril** [comment]
@stefonarch Looks like you upgraded from 10 -> 11. Or was it 11.1 -> 11.2 ?

@clemahieu Yes, 11.1 -> 11.2 has no effect on traffic. It is 10 -> 11.
I changed bootstrap_connections_max to 8 (it was 64 before) and restarted the node - no effect.
Vnstat doesn't show if traffic is TCP or UDP so I used BandwidthD for this. It says that around 90% of total traffic is UDP. Outgoing is UDP only, incoming both UDP and TCP. Here's the numbers and graphs:
![image](https://user-images.githubusercontent.com/32071293/38452272-fc7f36b6-3a40-11e8-84e0-829102b27311.png)
![image](https://user-images.githubusercontent.com/32071293/38452275-11e78436-3a41-11e8-8268-0942b5725cf1.png)

**Comment by stefonarch** [comment]
@nageneril  Upgrade was 11.1 → 11.2

**Comment by rkeene** [comment]
Comment from #745 from @PlasmaPower 

"The recent enormous bandwidth increase was due to a bug and has sense been fixed. There are other options to decrease bandwidth. A simple one is to separate publish and confirm_ack. More complicated ideas are being worked on too."

So this may be resolved.

**Comment by PlasmaPower** [comment]
Yes, the solution I was referring to is now called vote by hash, and will be enabled on September 1st.

**Comment by rkeene** [comment]
I'm going to close this issue based on our testing of vote-by-hash on the beta network.  If there are further problems we can re-open it or create a new issue, depending on the nature of those problems.

Thanks for vote-by-hash @PlasmaPower  !
