### ISSUE TITLE
Huge bandwidth problem of current implementation and Possible solution

### ISSUE THREAD

**Issue by huye0728** [nanocurrency/raiblocks#745]
Problem:
1. In the current implementation, each block needs to do election, so confirm ack messages from about  30 representatives  are rebroadcast and thare are about 1000 nodes. So about 1800 (30 * 2 * 1000^0.5 )messages need to be sent for each block election, bandwidth cost is about 4Mbps (1800 * 256byte per block). 

2. The network will become more decentralized in the future, representatives need to be rebroadcast will obviously increase (eg. 30 -> 300), bandwidth cost is about 40Mbps per block, that`s terrible.

Solution:
    1.If the block not sent to my account, just do election when fork found(new fork notify message need to be rebroadcast immediately, but current election message(confirm ack message) need to send slowly for bandwidth saving, and if account is in election , all the following blocks from the account are dropped)

  2.If the block is sent to my account, do P2P confirm requests to representatives myself only before receive.

  3.There is another benefit from the solution, because for representatives, it is no need to do re-signature, just rebroadcast blocks immediately when first see. I think transactions (send and receive) will complete in less than 3 seconds.

**Comment by PlasmaPower** [comment]
Unfortunately we have plans that will require votes for all blocks even when there isn't a fork. One of those is sentinel mode, where blocks will need confirmation before entering the ledger.

The recent enormous bandwidth increase was due to a bug and has sense been fixed. There are other options to decrease bandwidth. A simple one is to separate publish and confirm_ack. More complicated ideas are being worked on too.

**Comment by huye0728** [comment]
Thanks for reply, can i ask the purpose of election on all blocks, for prunning?

**Comment by AyiSoli** [comment]
I think it could be for users to have finality in their transactions

**Comment by rkeene** [comment]
This issue should be solved by vote stapling and/or active graph.  I am going to close this issue so that those specific improvements can be tracked directly.  Let me know if you have additional questions !
