### ISSUE TITLE
Node v11 - Implementation

### ISSUE THREAD

**Issue by areebmajeed** [nanocurrency/raiblocks#750]
Do you have any documentation on how to implement the JSON RPC for node v11? Do you suggest that I use v11 at all?

Please suggest what I should do on this matter.

**Comment by PlasmaPower** [comment]
RPC documentation is here: https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol

That documentation doesn't include universal blocks, but you don't have to worry about them for now. They aren't enabled on the main net yet.

**Comment by areebmajeed** [comment]
Would it be wise to implement the code for Universal Blocks as well?

**Comment by PlasmaPower** [comment]
No, as it would not be usable until universal blocks are enabled on the main net.

**Comment by areebmajeed** [comment]
I was looking through the code and managed to find all the code relating to contemporary blocks and universal/state blocks.

I will be coding for both types of blocks with compatibility for future. Simple enough, just need to detect the block type and then follow the procedure.

> Account (public address)
> Representative (always included)
> Balance (after sending)
> Amount (change in balance from previous block, can be 0)
> Link (the hash of source block when receiving, or the destination when address sending)

_Link of Interest: https://github.com/nanocurrency/raiblocks/blob/master/rai/lib/blocks.cpp_
