### ISSUE TITLE
Node V11 constatly freezes after 10min of usage and Error receiving block type End of file

### ISSUE THREAD

**Issue by tkek55** [nanocurrency/raiblocks#752]
**Description of bug:**

V11 node is running on linux ubuntu, 2vCore Xeon with 8GB ram, node freezes constatly after 10min, is stucked at block 4545123 and scyns one block every hour roughly, with node 10.0.0 i had no issues, use the github guide to download and run the node: https://github.com/nanocurrency/raiblocks/wiki/Guide:-Quickstart-to-running-a-node-(Ubuntu-16.04) (replaced everyhting with 11.0.0), anyone else with huge perfomance issues?

my log file is also full with this error: Error receiving block type End of file

**Comment by cclafferty** [comment]
I was experiencing this same problem in version 10.0.1 and resolved it by setting `"io_threads": "1"`.  
However I only needed to do this on the tiny 1GB DigitalOcean servers.   

After the update I spun up a fresh 1GB server with io_threads set to 1, it's slow but it's syncing.
I also get "End of file" errors and "Operation canceled" errors all over the place but it doesn't interupt the sync.
  
I have another 4GB spun up at the same tim with io_threads set to 2 and it's just "crashed" with the same error "End of file" notoriously as the last printed error.

When it "crashes" the RPC hangs indefinitely, leading me to believe the program has completely hung.

**Comment by cclafferty** [comment]
I've just realised that if you follow the wiki: [Guide: Quickstart to running a node (Ubuntu 16.04)](https://github.com/nanocurrency/raiblocks/wiki/Guide:-Quickstart-to-running-a-node-(Ubuntu-16.04)) the instructions have you download `libboost-all-dev` however I can confirm that Ubuntu 16.04 only downloads [v1.58 of the boost library](https://packages.ubuntu.com/xenial/libboost-all-dev). 

This project requires v1.66 and therefore that could be the problem.  
I'm spinning up again with the correct version of boost to see if it fixes things. No doubt a lot of people will have the wrong version installed if they followed that guide.

**Comment by cryptocode** [comment]
@cclafferty do you have instructions for getting boost 1.66 on Ubuntu 16.04? Build from source?

**Comment by cclafferty** [comment]
I built from source by cobbling together pieces of scripts in the *docker* folder and the *ci* folder. I'd right it up if I thought it would help however:

I don't think I was right with my assumption that Boost versions were the culprit...  
My 4GB node crashed again with `io_threads > 1` and this time I was running Boost 1.66.

In case anyone wants to try to recreate:  
Digital Ocean **Standard Droplet**
`4 GB 2 vCPUs 80 GB`

I've included my config.json and the short log output. The server hangs when it encounters this error as you can see by the timestamps it's been dead a while. It got about an hours worth of syncing done, total database size 3.1GB. Block count: 2747921

```json
{
    "version": "2",
"rpc_enable": "true",
    "rpc": {
        "address": "::1",
        "port": "7076",
"enable_control": "true",
        "frontier_request_limit": "16384",
        "chain_request_limit": "16384"
    },
    "node": {
        "version": "10",
        "peering_port": "7075",
        "bootstrap_fraction_numerator": "1",
        "receive_minimum": "1000000000000000000000000",
        "logging": {
            "version": "3",
            "ledger": "false",
            "ledger_duplicate": "false",
            "vote": "false",
            "network": "true",
            "network_message": "false",
            "network_publish": "false",
            "network_packet": "false",
            "network_keepalive": "false",
            "node_lifetime_tracing": "false",
            "insufficient_work": "true",
            "log_rpc": "true",
            "bulk_pull": "false",
            "work_generation_time": "true",
            "log_to_cerr": "false",
            "max_size": "16777216",
            "rotation_size": "4194304",
            "flush": "true"
        },
        "work_peers": "",
        "preconfigured_peers": [
            "rai.raiblocks.net"
        ],
        "preconfigured_representatives": [
            "xrb_3arg3asgtigae3xckabaaewkx3bzsh7nwz7jkmjos79ihyaxwphhm6qgjps4",
            "xrb_1stofnrxuz3cai7ze75o174bpm7scwj9jn3nxsn8ntzg784jf1gzn1jjdkou",
            "xrb_1q3hqecaw15cjt7thbtxu3pbzr1eihtzzpzxguoc37bj1wc5ffoh7w74gi6p",
            "xrb_3dmtrrws3pocycmbqwawk6xs7446qxa36fcncush4s1pejk16ksbmakis78m",
            "xrb_3hd4ezdgsp15iemx7h81in7xz5tpxi43b6b41zn3qmwiuypankocw3awes5k",
            "xrb_1awsn43we17c1oshdru4azeqjz9wii41dy8npubm4rg11so7dx3jtqgoeahy",
            "xrb_1anrzcuwe64rwxzcco8dkhpyxpi8kd7zsjc1oeimpc3ppca4mrjtwnqposrs",
            "xrb_1hza3f7wiiqa7ig3jczyxj5yo86yegcmqk3criaz838j91sxcckpfhbhhra1"
        ],
        "inactive_supply": "0",
        "password_fanout": "1024",
"io_threads": "2",
"work_threads": "4",
        "enable_voting": "true",
        "bootstrap_connections": "4",
        "bootstrap_connections_max": "64",
        "callback_address": "",
        "callback_port": "0",
        "callback_target": "",
        "lmdb_max_dbs": "128",
        "state_block_parse_canary": "89F1C0AC4C5AD23964AB880571E3EA67FDC41BD11AB20E67F0A29CF94CD4E24A",
        "state_block_generate_canary": "B6DC4D64801BEC7D81DAA086A5733D251E8CBA0E9226FD6173D97C0569EC2998"
    },
    "opencl_enable": "false",
    "opencl": {
        "platform": "0",
        "device": "0",
        "threads": "1048576"
    }
}
```

```log
$ head
==> /var/rai_node/log/log_2018-03-25_16-33-03.1.log <==
[2018-03-25 16:33:03.562853]: Node starting, version: 11.0
[2018-03-25 16:33:03.562981]: Work pool running 2 threads
[2018-03-25 16:33:03.563021]: Using bootstrap rep weight: xrb_3pczxuorp48td8645bs3m6c3xotxd3idskrenmi65rbrga5zmkemzhwkaznh -> 21,565,568 XRB
[2018-03-25 16:33:03.563051]: Using bootstrap rep weight: xrb_1awsn43we17c1oshdru4azeqjz9wii41dy8npubm4rg11so7dx3jtqgoeahy -> 16,168,827 XRB
[2018-03-25 16:33:03.563065]: Using bootstrap rep weight: xrb_3dmtrrws3pocycmbqwawk6xs7446qxa36fcncush4s1pejk16ksbmakis78m -> 15,610,182 XRB
[2018-03-25 16:33:03.563078]: Using bootstrap rep weight: xrb_3arg3asgtigae3xckabaaewkx3bzsh7nwz7jkmjos79ihyaxwphhm6qgjps4 -> 9,651,795 XRB
[2018-03-25 16:33:03.563090]: Using bootstrap rep weight: xrb_1stofnrxuz3cai7ze75o174bpm7scwj9jn3nxsn8ntzg784jf1gzn1jjdkou -> 8,502,208 XRB
[2018-03-25 16:33:03.563103]: Using bootstrap rep weight: xrb_3hd4ezdgsp15iemx7h81in7xz5tpxi43b6b41zn3qmwiuypankocw3awes5k -> 7,098,453 XRB
[2018-03-25 16:33:03.563114]: Using bootstrap rep weight: xrb_1rs5rtyeo1owjt6cz9ypdkqyydq656kai8t35haiioapts39x96br5u4mbdw -> 6,650,963 XRB
[2018-03-25 16:33:03.563126]: Using bootstrap rep weight: xrb_1q3hqecaw15cjt7thbtxu3pbzr1eihtzzpzxguoc37bj1wc5ffoh7w74gi6p -> 5,926,217 XRB



$ tail
==> /var/rai_node/log/log_2018-03-25_16-33-03.1.log <==
[2018-03-25 17:35:42.085377]: Connection established to [::ffff:51.255.74.8]:7275
[2018-03-25 17:35:42.090667]: Connection established to [::ffff:163.172.82.118]:7075
[2018-03-25 17:35:42.107944]: Connection established to [::ffff:217.170.197.82]:7075
[2018-03-25 17:35:42.210713]: Connection established to [::ffff:104.131.128.194]:7075
[2018-03-25 17:35:42.226900]: Connection established to [2600:3c01::f03c:91ff:fe47:157e]:7075
[2018-03-25 17:35:43.081173]: Frontier sending finished
[2018-03-25 17:35:43.462455]: Frontier sending finished
[2018-03-25 17:35:43.672405]: Completed frontier request, 354810 out of sync accounts according to [::ffff:46.101.32.113]:7075
[2018-03-25 17:35:44.008496]: Requesting account xrb_13a8p7og57nwakhowbug6yqt5o9g8ygotdketd6fn8yaehtzh1awxt3n3qz3 from [::ffff:185.45.113.106]:7075. 354809 accounts in queue
[2018-03-25 17:35:44.009020]: Error receiving block type End of file
```

**Comment by tkek55** [comment]
@cclafferty i downloaded version 10 again, which synced fast to the current block count, then deleted it and got the v11 via github follwoing this guide: https://github.com/nanocurrency/raiblocks/wiki/Build-rai_node-samples#ubuntu-1604-on-digital-ocean-droplet-5month-1gb-ram-1-core-25gb-ssd (really good for later upgragding), no my node works really well again. i guess V11 had huge issues with syncing, but with a finished data file it works very well now.

**Comment by areebmajeed** [comment]
I can confirm that we're facing the same problem with v11

**Comment by areebmajeed** [comment]
Using node v10 has indeed fixed the problem.

**Comment by argakiig** [comment]
Please check on the latest 11.1 release and see if the issue is resolved

**Comment by cclafferty** [comment]
I can confirm a sync completed unattended with version 11.1. Thank you

**Comment by benk210** [comment]
Same issue for me. Running windows. Tried fresh install. Database bootstrapped pretty quickly to within 8000 blocks of being syncronized, then craps out with the last message in the logs: Error receiving block type End of file.  Upon reopening the same thing error within 5 minutes.

**Comment by clemahieu** [comment]
V12.1 shouldn't freeze.
