### ISSUE TITLE
Wait for sync before backing up seed?

### ISSUE THREAD

**Issue by xrbfannn** [nanocurrency/raiblocks#755]
Should i wait for the wallet to synchronice before entering the seed to retreive my raiblocks?
---------------------------------------------------
BUG BOUNTY REPORT INFORMATION
---------------------------------------------------

In the interest of further improving the security of the network, we have launched the RaiBlocks Bug Bounty Program.

WARNING! Don't disclose any information for the Raiblocks bug bounty. First, please read the article about our Bug Bounty Program.

https://www.reddit.com/r/RaiBlocks/comments/7makm7/announcing_the_raiblocks_bug_bounty_program/

---------------------------------------------------
NORMAL BUG REPORT INFORMATION
---------------------------------------------------

If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

-->

**Description of bug:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by SergiySW** [comment]
Yes

**Comment by rkeene** [comment]
This appears to have been a question that was asked and answered, but I'll add a note that with lazy bootstrapping (#995) the wait should be drastically reduced.
