### ISSUE TITLE
Unable to Receive a Block (And/Or Open an Address)

### ISSUE THREAD

**Issue by areebmajeed** [nanocurrency/raiblocks#757]
My wallet is unlocked and the node fully synced. If I create a block with offline signing and then try to publish it, it responds with:

> [error] => Unreceivable

If I try with RPC "receive" method, it responds with:

>   [block] => 0000000000000000000000000000000000000000000000000000000000000000

**Comment by areebmajeed** [comment]
I am positive that I am using the right parameters, details while creating the receive block.

**Comment by areebmajeed** [comment]
Oh, I forgot to mention that I am actually trying to make an "open" block which is similar to "receive" block since the address is all fresh with only one non-pocketed transaction. It's not working :/

**Comment by areebmajeed** [comment]
>  

        $pKey = self::NodeTalk(array(
            'action' => 'account_key',
            'account' => $address
        ))['key'];

        $isOpen = self::NodeTalk(array(
            "action" => "block_create",
            "type" => "open",
            "previous" => $pKey,
            "account" => $address,
            "wallet" => App::loadSiteVar('node_wallet'),
            "representative" => "xrb_1hza3f7wiiqa7ig3jczyxj5yo86yegcmqk3criaz838j91sxcckpfhbhhra1",
            "source" => $block
        ));

        $isPublished = self::NodeTalk(array(
            "action" => "process",
            "block" => $isOpen['block']
        ));

        print_r($isPublished);

        $isPublished = self::NodeTalk(array(
            "action" => "receive",
            "account" => $address,
            "wallet" => App::loadSiteVar('node_wallet'),
            "block" => $block
        ));

        print_r($isPublished);


Response:

> (
    [error] => Unreceivable
)
Array
(
    [block] => 0000000000000000000000000000000000000000000000000000000000000000
)

**Comment by areebmajeed** [comment]
Also, tried node v10 which produced same outputs.

**Comment by areebmajeed** [comment]
In the log file, I have "[2018-03-27 11:38:46.075407]: Unable to receive, wallet locked".

But, the wallet is open and I just unlocked it again using the RPC function: password_enter with produced valid: 1 output.

**Comment by areebmajeed** [comment]
Alright, there's a breakthrough. The address I was trying to receive for was an imported address from other wallet file, I tried with a fresh address generated right on this server - worked seamlessly.

Anyone got an explanation for this? I had simply used the wallet import function of the node, and had copied an old [walletname].json file.

**Comment by cclafferty** [comment]
If you called `wallet_import` via the command line then the currently running daemon will not know about the wallet. The daemon must be restarted before it sees this other wallet.

An alternative method for import which works whilst the daemon is running is to use the RPC command "wallet_create" followed by "wallet_change_seed" to insert your backed up seed into a fresh wallet. This should work for you

**Comment by areebmajeed** [comment]
I restarted the server a million times :D

**Comment by cclafferty** [comment]
Can you see if the RPC method works as an alternative for you? I've just resorted to ignoring the command line options now since the majority of interest is for RPC anyway, they're more likely to work consistently.

**Comment by areebmajeed** [comment]
I, unfortunately, removed the account and wallet file. But, regardless, it could save lots of headaches in future for others.

**Comment by Sayplaydiv** [comment]
I encountered the same problem and asked for help.

**Comment by lucaspojo** [comment]
I have the same problem : { error: 'Unreceivable' }
