### ISSUE TITLE
Add options for Docker & Node "operating modes" (Exchange, Reps, etc)

### ISSUE THREAD

**Issue by bradennapier** [nanocurrency/raiblocks#762]
We need to look at adding switches to the docker container and/or node that will configure things for specific use-cases.  Specifically considering things like `-E` or `-R` for exchange and rep modes.

- These will likely be used to signal specific "analytics" be handled 
- These may / should provide sensible defaults where they make sense 
- These should be optional but recommended 

Anything else to add @rkeene ?

**Comment by zhyatt** [comment]
Closing out as exchange node integrations ironed out over releases since ticket opened.
