### ISSUE TITLE
Current block + unchecked blocks greater than total blocks 

### ISSUE THREAD

**Issue by df-andrews** [nanocurrency/raiblocks#781]
**Description of bug:**

Current block + unchecked blocks total to something greater than the current 
Count from https://www.nanode.co/blocks at time of writing. 7,526,602
Current block my node is at: 7526527
Current uncheck blocks is at: 575

Shouldn't the total blocks always be equal to the current block plus the unchecked blocks? 
I attempted to clear unchecked blocks. Which seemed to fix the issue but its back up to a few hundred over after about 40 minutes 

http://104.131.186.33/

Used the following command to get a live block count from the RPC server. 
curl -d '{ "action" : "block_count" }'

**Steps to reproduce the issue:**
1. Installed docker node 
2. Let run for >24hours 

**Describe the results you received:**
Block count seems incorrect and a large number of blocks are marked as unchecked.

**Describe the results you expected:**
Current block and unchecked to equal total blocks. Expected node to eventually run through all the unchecked blocks.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

Ubuntu 16.04.3
Docker version 17.12.0-ce, build c97c6d6
Node version 11.2 

**logs**

Log full of 
[2018-04-05 04:33:01.059488]: Block BLOCK_ID was republished to peers

**Comment by tkek55** [comment]
nanodes node also has unchecked blocks, which means their blocknumber there is there count not count+unchecked so you shouldnt worry
