### ISSUE TITLE
RPC stop_node doesn't stop rai_node process

### ISSUE THREAD

**Issue by stefonarch** [nanocurrency/raiblocks#782]
**Description of bug:**

v11.2
RPC call "stop_node" results "success", restarting rai_node 2 processes rai_node can be seen.
**Steps to reproduce the issue:**
1. RPC call "stop_node"
2. 

> ps | grep rai

 will show a rai_node process

**Describe the results you expected:**
stop_node should stop the node.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:
arch linux server 4gb ram dual core

**logs**

**Comment by dbachm123** [comment]
Confirmed. 
`curl -g -d '{"action": "stop"}'` stops the node, i.e. it does no longer check blocks, vote, or respond to RPC, but does not terminate the rai_node process.

**Comment by stefonarch** [comment]
Fixed now.
