### ISSUE TITLE
rai_node Wallet-Backups instructions in the Wiki contain errors

### ISSUE THREAD

**Issue by mschink** [nanocurrency/raiblocks#795]
https://github.com/nanocurrency/raiblocks/wiki/Wallet-Backups

The Docker container section contains some old commands that are no longer compatible with the latest nanocurrency/nano Docker container. If a noob drops by, he might be put off running a node since these instructions generate errors and headaches. :)

I don't think I can issue a pull request to a Wiki page. Is it open for editing? Who approves changes?

**Comment by SergiySW** [comment]
Updated
