### ISSUE TITLE
work_peers chaining

### ISSUE THREAD

**Issue by SergiySW** [nanocurrency/raiblocks#80]
Add option to resend work_generate to other work_peers from config
It will help to create remote PoW pools for exchanges and other big services

**Comment by SergiySW** [comment]
Additional: work_peer launch mode for rai_node. It doesn't need blockchain only config.json

**Comment by rkeene** [comment]
With the work server project, do we need to do this ?

**Comment by SergiySW** [comment]
We already have separate work_peer (server)

**Comment by SergiySW** [comment]
Also "work_generate" now has "use_peers" activated by default, so chaining is enabled.
Can be closed

**Comment by rkeene** [comment]
Thanks !
