### ISSUE TITLE
Nano node V12.1 (Classic Wallet) for OSX is crashing all the time.

### ISSUE THREAD

**Issue by alandefreitas** [nanocurrency/raiblocks#825]
After updating to V12.1, the node always runs for a few minutes and then I get a "Nano quit unexpectedly" error. It seems like a segmentation fault. 

Process: nano_wallet [2157] Path: /Applications/Nano.app/Contents/MacOS/nano_wallet Identifier: net.raiblocks.rai_wallet Version: 0 Code Type: X86-64 (Native) Parent Process: ??? [1] Responsible: nano_wallet [2157] Date/Time: 2018-04-25 13:49:19.907 -0300 OS Version: Mac OS X 10.13.4 (17E199)

Crashed Thread: 10
Exception Type: EXC_BAD_ACCESS (SIGBUS) Exception Codes: KERN_PROTECTION_FAILURE at 0x000070000efbfff8 Exception Note: EXC_CORPSE_NOTIFY
Termination Signal: Bus error: 10 Termination Reason: Namespace SIGNAL, Code 0xa Terminating Process: exc handler [0]
VM Regions Near 0x70000efbfff8: Stack 000070000ef3d000-000070000efbf000 [ 520K] rw-/rwx SM=COW thread 9 --> STACK GUARD 000070000efbf000-000070000efc0000 [ 4K] ---/rwx SM=NUL stack guard for thread 10 Stack 000070000efc0000-000070000f042000 [ 520K] rw-/rwx SM=COW 

thread 10
Thread 10 Crashed: 511 net.raiblocks.rai_wallet 0x00000001093784c4 rai::balance_visitor::receive_block(rai::receive_block const&) + 164

**Comment by AyiSoli** [comment]
Are you using a fresh install or updated one? Sometimes it could help to remove the previous instance completely before installing the new version 

Also try restarting the system to see if it loads

**Comment by SergiySW** [comment]
@cryptocode was it fixed with improved visitor?

**Comment by cryptocode** [comment]
@SergiySW yes indeed (and before that, the temporary stack increase)

**Comment by SergiySW** [comment]
Removing from V18 milestone & project as fixed in previous releases

**Comment by rkeene** [comment]
We can leave it in the V18 project to track work done during that cycle, and either remove the milestone or set it to whatever release fixed this issue
