### ISSUE TITLE
Implement in Golang

### ISSUE THREAD

**Issue by hskang9** [nanocurrency/raiblocks#826]
why not

**Comment by kenzaburo** [comment]
There is a version of Nano in Golang on Github. I have just forked it

**Comment by alexbakker** [comment]
I also started a Nano implementation Go: https://github.com/alexbakker/gonano. I haven't had time to work on it lately, but perhaps someone finds it useful.

**Comment by baryluk** [comment]
I agree, Go is way to go, but as a separate alternative implementation. That will force the protocol to be better documented too.

**Comment by rkeene** [comment]
Additional implementations are a great idea, but for now the Nano implementation that we provide will be implemented in C++.  Documentation to improve the diversity of implementations is also a great idea and is being worked on.
