### ISSUE TITLE
Is there a .NET c# SDK?

### ISSUE THREAD

**Issue by biapar** [nanocurrency/raiblocks#827]
Is there a .NET c# SDK?

**Comment by justdmitry** [comment]
I'm currently making RPC library: [NanoRpcSharp](https://github.com/justdmitry/NanoRpcSharp)

**Comment by clemahieu** [comment]
Cryptocode is looking in to implementing our idea to have the node only communicate through IPC and a shared library and external processes can do binding such as the existing RPC system, direct language bindings, protobuf etc.

Perhaps it would be good to coordinate to avoid rework and make sure everyone is on the same page.

**Comment by justdmitry** [comment]
@clemahieu where should I look for details?

**Comment by cryptocode** [comment]
@justdmitry Can you DM me over at Discord?

**Comment by cryptocode** [comment]
Closing. I believe this question was discussed on Discord, and there's an IPC PR now.
