### ISSUE TITLE
why nano supply is full pre-generated

### ISSUE THREAD

**Issue by mari-gold** [nanocurrency/raiblocks#836]
If a coin wants to build a strong and big network infrastructor you need some sort of a 
reward for the security and work nodes /  mineres eg validators do.
for example, why the supply isnt released slowly by every valid transaction container. 

Wouldnt that be possible?

**Comment by clemahieu** [comment]
This isn't about a specific bug so I'm going to close it.

We intentionally don't have an in-protocol reward system and instead focus on making the cost of running a representative trivial such that its expense can be incorporated in to other operating expenses.  In-protocol rewards through inflation make the currency less valuable as a store of value a per-transaction fees in-protocol make it less valuable as a transfer of value, both of which we don't want to induce.
