### ISSUE TITLE
make nano_wallet error c++

### ISSUE THREAD

**Issue by pr0x7t** [nanocurrency/raiblocks#853]
**Description of bug:**
[  7%] Built target blake2
[  7%] Built target ed25519
[  7%] Built target lmdb
[  7%] Building CXX object CMakeFiles/qt.dir/rai/qt/qt.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
make[3]: *** [CMakeFiles/qt.dir/rai/qt/qt.cpp.o] Error 1
make[2]: *** [CMakeFiles/qt.dir/all] Error 2
make[1]: *** [CMakeFiles/nano_wallet.dir/rule] Error 2
make: *** [nano_wallet] Error 2

**Steps to reproduce the issue:**
1.Install dependencies
2.Build Boost 1.66.0
3.Install QT5
4.Build nano_wallet

**Describe the results you received:**
Fail to build.

**Describe the results you expected:**
Makefile successful.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

- OS information  ubuntu 14.04 LTS
- (Linux) Kernel (e.g. `uname -a`): Linux 3.13.0-145-generic #194-Ubuntu SMP x86_64 GNU/Linux

- Node version 12.1
- (docker node) docker version 

**logs**

**Comment by cryptocode** [comment]
You need a C++14 compliant compiler.

**Comment by pr0x7t** [comment]
I have the newest version of g++ and cmake installed, forgive my ignorance and thanks for assisting.

**Comment by cryptocode** [comment]
That's odd. Could you try replacing the line with -std=c++14 with

`set(CMAKE_CXX_STANDARD 14)`

as a test?

**Comment by argakiig** [comment]
specifically which version of G++? you may have to use `c++1y` instead of c++14 with older versions 
https://stackoverflow.com/questions/31965413/compile-c14-code-with-g

**Comment by pr0x7t** [comment]
Thank you for the link, looks promising!
