### ISSUE TITLE
Rai_node compile error on Power 8 cpu

### ISSUE THREAD

**Issue by Igortorrente** [nanocurrency/raiblocks#856]
### Compile error rai_node 

I try compile latests version of rai_node, but unfortunately occurred a compilation error. I follow your [tutorial](https://github.com/nanocurrency/raiblocks/wiki/Build-rai_node-samples) to build it.
**Description of bug:**
``` bash
[ 80%] Building CXX object CMakeFiles/node.dir/rai/plat/posix/openclapi.cpp.o
/home/fedora/raiblocks/rai/node/openclwork.hpp:26:7: error: expected unqualified-id before '__attribute__'
  std::vector<cl_device_id> devices;
       ^~~~~~
/home/fedora/raiblocks/rai/node/openclwork.hpp:33:7: error: expected unqualified-id before '__attribute__'
  std::vector<rai::opencl_platform> platforms;
       ^~~~~~
make[3]: *** [CMakeFiles/node.dir/build.make:63: CMakeFiles/node.dir/rai/plat/posix/openclapi.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:367: CMakeFiles/node.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:465: CMakeFiles/rai_node.dir/rule] Error 2
make: *** [Makefile:316: rai_node] Error 2`
```
**Steps to reproduce the issue:**
1.Install dependencies
2.Build Boost 1.66.0
3.Build rai_node

**Describe the results you received:**
Fail to build.

**Describe the results you expected:**
Makefile successful.

**Environment:**
- Fedora 28 ppc64le
- Linux 4.16.3-301.fc28.ppc64le
- Git commit 84a6b5160e2d81cf86b23a81f5a52d29553e7287
- Without docker

edit1: Same on ubuntu 16.04 ppc64le.

**Comment by baryluk** [comment]
What is the compiler, compiler version and standard library version?

**Comment by Igortorrente** [comment]
### Fedora 28:
- GCC 8.1.1-1.fc28
- Glibc (GNU libc) 2.27
### Ubuntu 16.04
- GCC 5.3.1-1ubuntu1
- GLIBC 2.23-0ubuntu10

**Comment by cryptocode** [comment]
@Igortorrente Could you try adding `set(CMAKE_CXX_STANDARD 14)` after the `project` line at the top of CMakeLists.txt?

You can also try adding an explicit `#include <vector>` at the top of  `rai/plat/posix/openclapi.cpp`
