### ISSUE TITLE
Slow PC unable to sync

### ISSUE THREAD

**Issue by lukefor** [nanocurrency/raiblocks#872]
**Description of bug:**

Only once in a blue moon does my node start up correctly. 99% of the time it does not fully sync and sits maxxing out the disk with reads and spamming:

- Aborting frontier req because it was too slow
- frontier_req failed, reattempting
- Error sending frontier pair: Connection reset by peer
- Error sending frontier pair: Broken pipe

While spamming these it seems to receive and handle brand new blocks correctly, but it never receives the blocks between when it was last stopped and when it was started. It does not seem to matter how many blocks are missing - 10000 behind or an entire fresh bootstrap behave the exact same way. I have tried leaving it for several days 24/7 with no change.

In the rare case where it does start correctly, it stays working and synced 24/7 until restarted.

The bug has been present since I started trying to run a node around version 10, have tried all versions since in the hopes it would be fixed.

**Steps to reproduce the issue:**

1. Set up node on a very slow machine (CPU and disk)
2. Start node and watch logs/stats

**Environment**:

- OS: Arch Linux
- CPU: Intel(R) Celeron(R) CPU 220  @ 1.20GHz (single core)
- RAM: 2 GB DDR2
- Disk: Hitachi Deskstar 7K1000
- Node version: 14.0 (master)
- Kernel: 4.16.8
- Direct connection to internet (with ipv6)

**logs**

[log_2018-05-15_19-06-48.674.log](https://github.com/nanocurrency/raiblocks/files/2006422/log_2018-05-15_19-06-48.674.log)

**Comment by lukefor** [comment]
Transferred the config and data.ldb to another (much faster) server and it synced fine straight away, so whatever the issue is seems to be performance based

**Comment by kennedybaird** [comment]
I am having this same issue on my Dell XPS 13 9360 (i7, 16GB ram) with the 13.0 release.

I have a slow (ish) connection - around 1mbit.

However it *seems* to be better on 12.1, but still isn't getting new blocks.

I have manually bootstrapped as well.

This is running nano_wallet on linux.

**Comment by lukefor** [comment]
Same situation on version 14

**Comment by zhyatt** [comment]
Closing out as resolved in v17.
