### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by huye0728** [nanocurrency/raiblocks#888]
In construtor of rai::uint128_union from string,  if the string is invalid,  it will construct a uint128_union  with random data, i think it is better to set to zero in this situation. (uint256_union&uint512_union have the same problem)

```c++
rai::uint128_union::uint128_union (std::string const & string_a)
{
    decode_hex (string_a);
}

bool rai::uint128_union::decode_hex (std::string const & text)
{
    auto error (text.size () > 32);
    if (!error)
    {
        std::stringstream stream (text);
        stream << std::hex << std::noshowbase;
        rai::uint128_t number_l;
        try
        {
            stream >> number_l;
            *this = number_l;
            if (!stream.eof ())
            {
                error = true;
            }
        }
        catch (std::runtime_error &)
        {
            error = true;
        }
    }
    return error;
}
```

**Comment by PlasmaPower** [comment]
I'm pretty sure that since this is a union, it will be zero initialized by default.

**Comment by huye0728** [comment]
i did a test, here is result:
-----------------------------------------code---------------------------------
int main()
{
    rai::uint128_union t1("01234567890123456789012345678901");
    std::cout<<t1.to_string()<<std::endl;
    
    rai::uint128_union t2("012345678901234567890123456789012345");
    std::cout<<t2.to_string()<<std::endl;
        
    return 0;
}

---------------------output------------------------
[root@US1 nano]# ./a.out 
01234567890123456789012345678901
03000000000000000400000000000000
[root@US1 nano]#

**Comment by PlasmaPower** [comment]
It looks like this constructor is only used with a constant argument, so it's not an immediate issue. In many of the uses, it would be inconvenient to use decode_hex directly. Maybe we should throw an exception if decode_hex fails.

**Comment by cryptocode** [comment]
uint128_union taking a string is never used and should be removed.

Since we're "kinda" not using exceptions except internally in functions, `ledger_constants` (the only user of the string constructor for uint256_union) could be rewritten to use decode_hex explicitly and check the bool return value. In other words, remove the string c'tor there as well.
