### ISSUE TITLE
RPC: Raw history does not return full block details

### ISSUE THREAD

**Issue by rotilho** [nanocurrency/raiblocks#893]
As the https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#account-history states:

> raw: if set to true instead of the default false, instead of outputting a simplified send or receive explanation of blocks (intended for wallets), output all parameters of the block itself as seen in block_create or other APIs returning blocks. It still includes the "account" and "amount" properties you'd see without this option. State/universal blocks in the raw history will also have a subtype field indicating their equivalent "old" block. Unfortunately, the "account" parameter for open blocks is the account of the source block, not the account of the open block, to preserve similarity with the non-raw history.

However when calling account history with raw=true the returned json with state block does not have `previous `and `balance` fields.

EDIT: send, change and receive also don't have `previous`

**Comment by SergiySW** [comment]
Closed with https://github.com/nanocurrency/raiblocks/commit/7db52ddab57da2f87905c079a26dec8025dcfccf
