### ISSUE TITLE
Nano wallet v13 on macOS High Sierra unstable after syncing 10 Millionth block

### ISSUE THREAD

**Issue by llehs** [nanocurrency/raiblocks#899]
The wallet now constantly crashes after syncing past the 10 millionth block.  Below is a snippet of apple's crash report.  The nano logs do not seem to have anything meaningful relating to the crash. 

```
Process:               nano_wallet [39153]
Path:                  /Applications/Nano.app/Contents/MacOS/nano_wallet
Identifier:            net.raiblocks.rai_wallet
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nano_wallet [39153]
User ID:               501

Date/Time:             2018-05-30 11:01:54.109 -0400
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Bridge OS Version:     3.0 (14Y664)

Time Awake Since Boot: 1100000 seconds
Time Since Wake:       850 seconds

System Integrity Protection: enabled

Crashed Thread:        15

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x000070000a663ff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [0]

VM Regions Near 0x70000a663ff8:
    MALLOC_NANO            000060c000000000-000060c000400000 [ 4096K] rw-/rwx SM=PRV  
--> STACK GUARD            000070000a663000-000070000a664000 [    4K] ---/rwx SM=NUL  stack guard for thread 15
    Stack                  000070000a664000-000070000a6e6000 [  520K] rw-/rwx SM=COW  thread 15
```

**Comment by jeanfrancoisdrapeau** [comment]
Also having problems in Windows 10 since the 10M blocks mark. "nano_wallet" v13 crashes a few seconds after starting up

**Comment by leberschnitzel** [comment]
I see the same problem on the Windows Beta Wallet and the Windows Classic Wallet v13.

**Comment by dbachm123** [comment]
Same on Mac OS X Beta and Classic wallet.

**Comment by neffers-gridcoin** [comment]
Same problem on 2 Windows 10 PCs running v13

**Comment by argakiig** [comment]
We are aware of the issue, and are looking into a resolution, We experienced a similar issue previously and are working toward a more permanent solution for now

**Comment by llehs** [comment]
I'm not sure why, but the wallet is now stable with no changes made on my end.  Very strange considering the wallet was crashing without fail when trying to sync after block 10M, now all of the sudden it's fully synced without any issue.

**Comment by llehs** [comment]
Closing since v14 has been released.
