### ISSUE TITLE
Memory leak in Linux node version? 

### ISSUE THREAD

**Issue by requestingrequester** [nanocurrency/raiblocks#901]
The node still eats up all memory until it crashes. In my case, 2gb. I had presynced the node so I don't think it was bootstrapping.

**Steps to reproduce the issue:**
1. Download official node release
2. Wait a few hours
3. Run out of memory

**Environment**:

This: Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
And I also had the same problem running Debian on a Raspi 3.
Node version: The most recent one as of now, it says 13.0
Docker: Not using docker 

**logs**

Logs seem to contain nothing noteworthy.

**Comment by baryluk** [comment]
Could be related to https://github.com/nanocurrency/raiblocks/issues/813 , but maybe not.

**Comment by Shrey33** [comment]
@requestingrequester can you provide the logs ?

**Comment by rkeene** [comment]
This should be resolved by the memory leak fixes supplied in V17.0 !  See #1338 for additional details.
