### ISSUE TITLE
Post installation issue.

### ISSUE THREAD

**Issue by mstonepc** [nanocurrency/raiblocks#907]
Hello. I followed this guide:  https://github.com/nanocurrency/raiblocks/wiki/Guide:-Quickstart-to-running-a-node-(Ubuntu-16.04) 

It seems like i was able to set everything up successfully, however It seems to be just stuck on Block: 1.
Is there anything else I'm missing?

**Comment by argakiig** [comment]
What are you using to poll for block count? RPC or CLI.
RPC will show both unchecked and checked blocks, which you should see unchecked increment
CLI will only show checked.
It can take a bit of time for blocks to start to confirm as it bootstraps accounts at random from other peers

**Comment by mstonepc** [comment]
Well per those instructions, RPC is enabled, so I'm assuming it's using RPC.   Running:
`rai_node --debug_block_count `
Still returns "Block count: 1", 24 hours later after it's been running.

**Comment by argakiig** [comment]
That's not rpc, that's cli. If you have rpc enabled please use `curl -d '{"action":"block_count"}' [::1]:7076 if using default config.json options

**Comment by mstonepc** [comment]
curl: (7) Failed to connect to ::1 port 7076: Connection refuse

I apologize for requiring so much help here, it's my first time trying to run a node. I did have RPC enabled per the settings.. the CLI command is giving me block count: 1, and trying to curl gives me that error above..   It doesn't look like it's listening on 7076 either..

netstat -a | grep 7076 

^ That's returning nothing.
I guess if i can't figure this out today, i'll roll this back, and try w/ the official distro from nano, but these issues are coming from following those instructions to the T.

**Comment by mstonepc** [comment]
Someone in discord pointed out that i may have installed a bad version, since that guide i referenced is a few versions back. Doing the process again w/ the new version fixed my issue :).
