### ISSUE TITLE
how to connect my node ip ::1:7076 to my NodeJS api ?? 

### ISSUE THREAD

**Issue by summitruhela** [nanocurrency/raiblocks#917]
**Description of bug:**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

**logs**

**Comment by summitruhela** [comment]
how

**Comment by clemahieu** [comment]
Tech support is in discord. Chat.nano.org
