### ISSUE TITLE
Add --unchecked-clear CLI command/option

### ISSUE THREAD

**Issue by justdmitry** [nanocurrency/raiblocks#923]
This one is [available in RPC](https://github.com/nanocurrency/raiblocks/wiki/RPC-protocol#clear-unchecked-blocks), but require control mode. Having similar CLI command will remove need on node twice restarting (to enable control before clear and disable after).

**Comment by SergiySW** [comment]
https://github.com/nanocurrency/raiblocks/pull/915

**Comment by justdmitry** [comment]
Ooops, my bad. This one is duplicate. Thank you.
