### ISSUE TITLE
RPC calls for getting POW from external sources

### ISSUE THREAD

**Issue by HostFat** [nanocurrency/raiblocks#95]
There should be one or more RPC calls where it is possible to ask a POW from an external source to both confirming an incoming block/transaction adding a POW to an outgoing block/transaction.

So, then it will be possible to develop a POW generator in javascript.
This last thing will be used by services to ask to their users to generate the POW directly from their browsers.
Then after the browser had generated it, it will be sent back to the node, that it will finish the operation (receiving/sending blocks)

**Comment by HostFat** [comment]
This can be useful even if it is possible from the GUI directly.

There should be a panel where it is possible to enter a block data, already signed, but "without the POW".

Then the node will make itself the POW and broadcast the block.

**Comment by jaimehgb** [comment]
When sending or changing representative it should be enough a command to build the block and return it as Json with the PoW field empty. Then calculate the PoW the way it is desired, update the Json and broadcast the block with the already existing command to do so. There should be a setting to stop the node generating PoW for receive blocks so if a block is received while the other block is waiting for PoW, as both blocks will have the same previous block, only one of them would be accepted by the network.

To receive blocks,  using the 'pending' and 'retrieve block' commands should be enough to build the receive blocks and process the PoW manually. A new command to retrieve the next pending block already built with just the PoW field missing would be great though. Like before, node should stop generating PoW automatically to avoid forks while these blocks wait for their PoW.
