### ISSUE TITLE
[bug]is the judgement true:max_vote->sequence > vote_a->sequence? then it may be a replay, not a vote

### ISSUE THREAD

**Issue by huye0728** [nanocurrency/raiblocks#962]
https://github.com/nanocurrency/raiblocks/blob/ef86a5e4c5d5d8225c648934ef1abc6033c418f2/rai/node/node.cpp#L1224

**Comment by PlasmaPower** [comment]
Yeah, though this shouldn't matter since the last vote should be active.

**Comment by PlasmaPower** [comment]
Created #964 to flip this
