### ISSUE TITLE
Testing RaiBlocks locally

### ISSUE THREAD

**Issue by LotfiKobrosly** [nanocurrency/raiblocks#972]
**Description of bug:**

Trying to test RaiBlocks technology localy using Docker, I followed the steps https://github.com/nanocurrency/raiblocks/wiki/Build-rai_node-samples for Ubuntu 16.04 (until just before the cmake command) and the I referred to https://github.com/nanocurrency/raiblocks/wiki/Build-Instructions, in order to change CMAKE variables and do local offline testing.

**Issues that occurred**
1. How to build Qt? (specified in the steps of the second link): there's only qt.conf and now qt.build nor qt.src (I am new to programming btw)
2. When I skip that step, I continue with the steps and change other CMAKE variables, but I have an error while running `make rai_node` which is `make: *** No rule to make target` even though I did run `cmake -DBOOST_ROOT=../[boost]/ -G "Unix Makefiles"`

Can anyone help please? That would be appreciated

**Environment**:

- Microsoft Windows 7 Entreprise
- (docker node) docker4WL (container running a ubuntu bash)

**Comment by zhyatt** [comment]
Closing out as old issue.  If you are still working to build the wallet and need assistance our community is active on Discord and may be able to more readily help there.
