### ISSUE TITLE
Establishing a private network

### ISSUE THREAD

**Issue by LotfiKobrosly** [nanocurrency/raiblocks#975]
Is there a way to establish a private network (by changing the config.json file for example) in order to make tests on it? It is to stress test it and verify some of its prowesses offline, research purposes.

Thank you very much!

**Comment by giovangonzalez** [comment]
Hi there, did you achieved creating a private network? I'm working on that but I can't get confirmed the blocks.
Thanks

**Comment by rkeene** [comment]
See also #1099 -- which is similar, but not the same.

**Comment by zhyatt** [comment]
@LotfiKobrosly Glad to hear you got it working.  Closing out as complete.
