### ISSUE TITLE
Build rai_node samples testnet erro

### ISSUE THREAD

**Issue by wesleysd1989** [nanocurrency/raiblocks#979]
OS: ubuntu 18.04 64bits
step by step:
1 - sudo apt-get update && sudo apt-get upgrade   
2- sudo apt-get install git cmake g++ curl wget
3- wget -O boost_1_66_0.tar.gz 
4- https://netix.dl.sourceforge.net/project/boost/boost/1.66.0/boost_1_66_0.tar.gz   
5- tar xzvf boost_1_66_0.tar.gz   
6- cd boost_1_66_0   
7- ./bootstrap.sh --with-libraries=filesystem,iostreams,log,program_options,thread   
8- ./b2 --prefix=../[boost] link=static install   
9- cd ..
10- git clone --recursive https://github.com/nanocurrency/raiblocks.git rai_build   
11- cd rai_build   
12- cmake -DBOOST_ROOT=../[boost]/ -DACTIVE_NETWORK=rai_test_network -G "Unix Makefiles"
no error
13 - make rai_node
error output
[ 88%] Building CXX object rai/node/CMakeFiles/node.dir/bootstrap.cpp.o
/home/m3n0r/nano/rai_build/rai/node/bootstrap.cpp: In constructor ‘__gnu_cxx::__normal_iterator<_Iterator, _Container>::__normal_iterator(const _Iterator&) [with _Iterator = boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >*; _Container = std::vector<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> >, std::allocator<boost::io::detail::format_item<char, std::char_traits<char>, std::allocator<char> > > >]’:
/home/m3n0r/nano/rai_build/rai/node/bootstrap.cpp:2095:1: internal compiler error: Falha de segmentação
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
rai/node/CMakeFiles/node.dir/build.make:86: recipe for target 'rai/node/CMakeFiles/node.dir/bootstrap.cpp.o' failed
make[3]: *** [rai/node/CMakeFiles/node.dir/bootstrap.cpp.o] Error 1
CMakeFiles/Makefile2:739: recipe for target 'rai/node/CMakeFiles/node.dir/all' failed
make[2]: *** [rai/node/CMakeFiles/node.dir/all] Error 2
CMakeFiles/Makefile2:815: recipe for target 'rai/rai_node/CMakeFiles/rai_node.dir/rule' failed
make[1]: *** [rai/rai_node/CMakeFiles/rai_node.dir/rule] Error 2
Makefile:394: recipe for target 'rai_node' failed
make: *** [rai_node] Error 2

**Comment by PlasmaPower** [comment]
Looks like a GCC bug. Try compiling with clang.

**Comment by wesleysd1989** [comment]
ty, for suport

i use
sudo apt-get install clang
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-6.0 100
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-6.0 100

and work hard now.
