### ISSUE TITLE
Bulk Pull by Account Support

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/raiblocks#988]
Add support for a new bootstrapping command called "bulk_pull_account" which accepts as arguments:
1. Account (256-bits)
2. Minimum Pending Amount (128 bits)
3. Flags (8-bits)

The _Account_ argument is the public key of an account which we are interested in.  The "bulk_pull_account" command will request that the remote node return all blocks related to this account.  This includes the frontier for the account and information related to transactions destined for that account that have not yet been received with receiving blocks (pending).

The _Minimum Pending Amount_ argument is the minimum amount that must be pending in a single transaction for an account or block hash to be included in the _pending_ result section.

The _Flags_ argument is a bitfield which is a mask of the following options OR'd together:
- 0x01: PENDING_ADDRESS_ONLY: The presence of this flag indicates that the result should only include the account public keys in the _pending_ section;  The absence of this flag indicates that the _pending_ section should be comprised of tuples containing the block hash and amount for all pending receives

The result will be in the format of
```
struct frontierInformation {
        blockHash_t frontierHash
        rawAmount_t frontierBalance
}
union pending {
     struct addressOnly[] {
          address_t sendingAccount
     }
     struct hashBalanceTuple[] {
          blockHash_t sendingBlockHash
          rawAmount_t sendingBlockAmount
     }
}
```
Where blockHash_t and address_t are a 256-bit bitfield, and rawAmount_t is a 128-bit bitfield.

The pending section will terminate with a final entry where all entries have a value of 0.  That is, for the case where the PENDING_ADDRESS_ONLY flag is set the result will terminate with a value of a 256-bits 0, and otherwise it will terminate with a value of 384 (256+128) bits of 0.

**Comment by slact** [comment]
Yes!

**Comment by Inkeliz** [comment]
Wait. There's a new field, `Flags (8-bits)`? Why create a `Flag` when already have the `Extesions (16-bit)` in the header?

**Comment by rkeene** [comment]
@Inkeliz Because if we use extension bits for this then those bits cannot be used for many things since those things may apply also to `bulk_pull_account`.
